syscalls = [
	[
	'NtWorkerFactoryWorkerReady', # 0x0
	'NtAcceptConnectPort', # 0x1
	'NtMapUserPhysicalPagesScatter', # 0x2
	'NtWaitForSingleObject', # 0x3
	'NtCallbackReturn', # 0x4
	'NtReadFile', # 0x5
	'NtDeviceIoControlFile', # 0x6
	'NtWriteFile', # 0x7
	'NtRemoveIoCompletion', # 0x8
	'NtReleaseSemaphore', # 0x9
	'NtReplyWaitReceivePort', # 0xa
	'NtReplyPort', # 0xb
	'NtSetInformationThread', # 0xc
	'NtSetEvent', # 0xd
	'NtClose', # 0xe
	'NtQueryObject', # 0xf
	'NtQueryInformationFile', # 0x10
	'NtOpenKey', # 0x11
	'NtEnumerateValueKey', # 0x12
	'NtFindAtom', # 0x13
	'NtQueryDefaultLocale', # 0x14
	'NtQueryKey', # 0x15
	'NtQueryValueKey', # 0x16
	'NtAllocateVirtualMemory', # 0x17
	'NtQueryInformationProcess', # 0x18
	'NtWaitForMultipleObjects32', # 0x19
	'NtWriteFileGather', # 0x1a
	'NtSetInformationProcess', # 0x1b
	'NtCreateKey', # 0x1c
	'NtFreeVirtualMemory', # 0x1d
	'NtImpersonateClientOfPort', # 0x1e
	'NtReleaseMutant', # 0x1f
	'NtQueryInformationToken', # 0x20
	'NtRequestWaitReplyPort', # 0x21
	'NtQueryVirtualMemory', # 0x22
	'NtOpenThreadToken', # 0x23
	'NtQueryInformationThread', # 0x24
	'NtOpenProcess', # 0x25
	'NtSetInformationFile', # 0x26
	'NtMapViewOfSection', # 0x27
	'NtAccessCheckAndAuditAlarm', # 0x28
	'NtUnmapViewOfSection', # 0x29
	'NtReplyWaitReceivePortEx', # 0x2a
	'NtTerminateProcess', # 0x2b
	'NtSetEventBoostPriority', # 0x2c
	'NtReadFileScatter', # 0x2d
	'NtOpenThreadTokenEx', # 0x2e
	'NtOpenProcessTokenEx', # 0x2f
	'NtQueryPerformanceCounter', # 0x30
	'NtEnumerateKey', # 0x31
	'NtOpenFile', # 0x32
	'NtDelayExecution', # 0x33
	'NtQueryDirectoryFile', # 0x34
	'NtQuerySystemInformation', # 0x35
	'NtOpenSection', # 0x36
	'NtQueryTimer', # 0x37
	'NtFsControlFile', # 0x38
	'NtWriteVirtualMemory', # 0x39
	'NtCloseObjectAuditAlarm', # 0x3a
	'NtDuplicateObject', # 0x3b
	'NtQueryAttributesFile', # 0x3c
	'NtClearEvent', # 0x3d
	'NtReadVirtualMemory', # 0x3e
	'NtOpenEvent', # 0x3f
	'NtAdjustPrivilegesToken', # 0x40
	'NtDuplicateToken', # 0x41
	'NtContinue', # 0x42
	'NtQueryDefaultUILanguage', # 0x43
	'NtQueueApcThread', # 0x44
	'NtYieldExecution', # 0x45
	'NtAddAtom', # 0x46
	'NtCreateEvent', # 0x47
	'NtQueryVolumeInformationFile', # 0x48
	'NtCreateSection', # 0x49
	'NtFlushBuffersFile', # 0x4a
	'NtApphelpCacheControl', # 0x4b
	'NtCreateProcessEx', # 0x4c
	'NtCreateThread', # 0x4d
	'NtIsProcessInJob', # 0x4e
	'NtProtectVirtualMemory', # 0x4f
	'NtQuerySection', # 0x50
	'NtResumeThread', # 0x51
	'NtTerminateThread', # 0x52
	'NtReadRequestData', # 0x53
	'NtCreateFile', # 0x54
	'NtQueryEvent', # 0x55
	'NtWriteRequestData', # 0x56
	'NtOpenDirectoryObject', # 0x57
	'NtAccessCheckByTypeAndAuditAlarm', # 0x58
	'UNKNOWN', # 0x59
	'NtWaitForMultipleObjects', # 0x5a
	'NtSetInformationObject', # 0x5b
	'NtCancelIoFile', # 0x5c
	'NtTraceEvent', # 0x5d
	'NtPowerInformation', # 0x5e
	'NtSetValueKey', # 0x5f
	'NtCancelTimer', # 0x60
	'NtSetTimer', # 0x61
	'NtAccessCheck', # 0x62
	'NtAccessCheckByType', # 0x63
	'NtAccessCheckByTypeResultList', # 0x64
	'NtAccessCheckByTypeResultListAndAuditAlarm', # 0x65
	'NtAccessCheckByTypeResultListAndAuditAlarmByHandle', # 0x66
	'NtAddAtomEx', # 0x67
	'NtAddBootEntry', # 0x68
	'NtAddDriverEntry', # 0x69
	'NtAdjustGroupsToken', # 0x6a
	'NtAdjustTokenClaimsAndDeviceGroups', # 0x6b
	'NtAlertResumeThread', # 0x6c
	'NtAlertThread', # 0x6d
	'NtAlertThreadByThreadId', # 0x6e
	'NtAllocateLocallyUniqueId', # 0x6f
	'NtAllocateReserveObject', # 0x70
	'NtAllocateUserPhysicalPages', # 0x71
	'NtAllocateUuids', # 0x72
	'NtAlpcAcceptConnectPort', # 0x73
	'NtAlpcCancelMessage', # 0x74
	'NtAlpcConnectPort', # 0x75
	'NtAlpcConnectPortEx', # 0x76
	'NtAlpcCreatePort', # 0x77
	'NtAlpcCreatePortSection', # 0x78
	'NtAlpcCreateResourceReserve', # 0x79
	'NtAlpcCreateSectionView', # 0x7a
	'NtAlpcCreateSecurityContext', # 0x7b
	'NtAlpcDeletePortSection', # 0x7c
	'NtAlpcDeleteResourceReserve', # 0x7d
	'NtAlpcDeleteSectionView', # 0x7e
	'NtAlpcDeleteSecurityContext', # 0x7f
	'NtAlpcDisconnectPort', # 0x80
	'NtAlpcImpersonateClientOfPort', # 0x81
	'NtAlpcOpenSenderProcess', # 0x82
	'NtAlpcOpenSenderThread', # 0x83
	'NtAlpcQueryInformation', # 0x84
	'NtAlpcQueryInformationMessage', # 0x85
	'NtAlpcRevokeSecurityContext', # 0x86
	'NtAlpcSendWaitReceivePort', # 0x87
	'NtAlpcSetInformation', # 0x88
	'NtAreMappedFilesTheSame', # 0x89
	'NtAssignProcessToJobObject', # 0x8a
	'NtAssociateWaitCompletionPacket', # 0x8b
	'NtCancelIoFileEx', # 0x8c
	'NtCancelSynchronousIoFile', # 0x8d
	'NtCancelTimer2', # 0x8e
	'NtCancelWaitCompletionPacket', # 0x8f
	'NtCommitComplete', # 0x90
	'NtCommitEnlistment', # 0x91
	'NtCommitTransaction', # 0x92
	'NtCompactKeys', # 0x93
	'NtCompareTokens', # 0x94
	'NtCompleteConnectPort', # 0x95
	'NtCompressKey', # 0x96
	'NtConnectPort', # 0x97
	'NtCreateDebugObject', # 0x98
	'NtCreateDirectoryObject', # 0x99
	'NtCreateDirectoryObjectEx', # 0x9a
	'NtCreateEnlistment', # 0x9b
	'NtCreateEventPair', # 0x9c
	'NtCreateIRTimer', # 0x9d
	'NtCreateIoCompletion', # 0x9e
	'NtCreateJobObject', # 0x9f
	'NtCreateJobSet', # 0xa0
	'NtCreateKeyTransacted', # 0xa1
	'NtCreateKeyedEvent', # 0xa2
	'NtCreateLowBoxToken', # 0xa3
	'NtCreateMailslotFile', # 0xa4
	'NtCreateMutant', # 0xa5
	'NtCreateNamedPipeFile', # 0xa6
	'NtCreatePagingFile', # 0xa7
	'NtCreatePort', # 0xa8
	'NtCreatePrivateNamespace', # 0xa9
	'NtCreateProcess', # 0xaa
	'NtCreateProfile', # 0xab
	'NtCreateProfileEx', # 0xac
	'NtCreateResourceManager', # 0xad
	'NtCreateSemaphore', # 0xae
	'NtCreateSymbolicLinkObject', # 0xaf
	'NtCreateThreadEx', # 0xb0
	'NtCreateTimer', # 0xb1
	'NtCreateTimer2', # 0xb2
	'NtCreateToken', # 0xb3
	'NtCreateTokenEx', # 0xb4
	'NtCreateTransaction', # 0xb5
	'NtCreateTransactionManager', # 0xb6
	'NtCreateUserProcess', # 0xb7
	'NtCreateWaitCompletionPacket', # 0xb8
	'NtCreateWaitablePort', # 0xb9
	'NtCreateWnfStateName', # 0xba
	'NtCreateWorkerFactory', # 0xbb
	'NtDebugActiveProcess', # 0xbc
	'NtDebugContinue', # 0xbd
	'NtDeleteAtom', # 0xbe
	'NtDeleteBootEntry', # 0xbf
	'NtDeleteDriverEntry', # 0xc0
	'NtDeleteFile', # 0xc1
	'NtDeleteKey', # 0xc2
	'NtDeleteObjectAuditAlarm', # 0xc3
	'NtDeletePrivateNamespace', # 0xc4
	'NtDeleteValueKey', # 0xc5
	'NtDeleteWnfStateData', # 0xc6
	'NtDeleteWnfStateName', # 0xc7
	'NtDisableLastKnownGood', # 0xc8
	'NtDisplayString', # 0xc9
	'NtDrawText', # 0xca
	'NtEnableLastKnownGood', # 0xcb
	'NtEnumerateBootEntries', # 0xcc
	'NtEnumerateDriverEntries', # 0xcd
	'NtEnumerateSystemEnvironmentValuesEx', # 0xce
	'NtEnumerateTransactionObject', # 0xcf
	'NtExtendSection', # 0xd0
	'NtFilterBootOption', # 0xd1
	'NtFilterToken', # 0xd2
	'NtFilterTokenEx', # 0xd3
	'NtFlushBuffersFileEx', # 0xd4
	'NtFlushInstallUILanguage', # 0xd5
	'NtFlushInstructionCache', # 0xd6
	'NtFlushKey', # 0xd7
	'NtFlushProcessWriteBuffers', # 0xd8
	'NtFlushVirtualMemory', # 0xd9
	'NtFlushWriteBuffer', # 0xda
	'NtFreeUserPhysicalPages', # 0xdb
	'NtFreezeRegistry', # 0xdc
	'NtFreezeTransactions', # 0xdd
	'NtGetCachedSigningLevel', # 0xde
	'NtGetCompleteWnfStateSubscription', # 0xdf
	'NtGetContextThread', # 0xe0
	'NtGetCurrentProcessorNumber', # 0xe1
	'NtGetDevicePowerState', # 0xe2
	'NtGetMUIRegistryInfo', # 0xe3
	'NtGetNextProcess', # 0xe4
	'NtGetNextThread', # 0xe5
	'NtGetNlsSectionPtr', # 0xe6
	'NtGetNotificationResourceManager', # 0xe7
	'NtGetWriteWatch', # 0xe8
	'NtImpersonateAnonymousToken', # 0xe9
	'NtImpersonateThread', # 0xea
	'NtInitializeNlsFiles', # 0xeb
	'NtInitializeRegistry', # 0xec
	'NtInitiatePowerAction', # 0xed
	'NtIsSystemResumeAutomatic', # 0xee
	'NtIsUILanguageComitted', # 0xef
	'NtListenPort', # 0xf0
	'NtLoadDriver', # 0xf1
	'NtLoadKey', # 0xf2
	'NtLoadKey2', # 0xf3
	'NtLoadKeyEx', # 0xf4
	'NtLockFile', # 0xf5
	'NtLockProductActivationKeys', # 0xf6
	'NtLockRegistryKey', # 0xf7
	'NtLockVirtualMemory', # 0xf8
	'NtMakePermanentObject', # 0xf9
	'NtMakeTemporaryObject', # 0xfa
	'NtMapCMFModule', # 0xfb
	'NtMapUserPhysicalPages', # 0xfc
	'NtModifyBootEntry', # 0xfd
	'NtModifyDriverEntry', # 0xfe
	'NtNotifyChangeDirectoryFile', # 0xff
	'NtNotifyChangeKey', # 0x100
	'NtNotifyChangeMultipleKeys', # 0x101
	'NtNotifyChangeSession', # 0x102
	'NtOpenEnlistment', # 0x103
	'NtOpenEventPair', # 0x104
	'NtOpenIoCompletion', # 0x105
	'NtOpenJobObject', # 0x106
	'NtOpenKeyEx', # 0x107
	'NtOpenKeyTransacted', # 0x108
	'NtOpenKeyTransactedEx', # 0x109
	'NtOpenKeyedEvent', # 0x10a
	'NtOpenMutant', # 0x10b
	'NtOpenObjectAuditAlarm', # 0x10c
	'NtOpenPrivateNamespace', # 0x10d
	'NtOpenProcessToken', # 0x10e
	'NtOpenResourceManager', # 0x10f
	'NtOpenSemaphore', # 0x110
	'NtOpenSession', # 0x111
	'NtOpenSymbolicLinkObject', # 0x112
	'NtOpenThread', # 0x113
	'NtOpenTimer', # 0x114
	'NtOpenTransaction', # 0x115
	'NtOpenTransactionManager', # 0x116
	'NtPlugPlayControl', # 0x117
	'NtPrePrepareComplete', # 0x118
	'NtPrePrepareEnlistment', # 0x119
	'NtPrepareComplete', # 0x11a
	'NtPrepareEnlistment', # 0x11b
	'NtPrivilegeCheck', # 0x11c
	'NtPrivilegeObjectAuditAlarm', # 0x11d
	'NtPrivilegedServiceAuditAlarm', # 0x11e
	'NtPropagationComplete', # 0x11f
	'NtPropagationFailed', # 0x120
	'NtPulseEvent', # 0x121
	'NtQueryBootEntryOrder', # 0x122
	'NtQueryBootOptions', # 0x123
	'NtQueryDebugFilterState', # 0x124
	'NtQueryDirectoryObject', # 0x125
	'NtQueryDriverEntryOrder', # 0x126
	'NtQueryEaFile', # 0x127
	'NtQueryFullAttributesFile', # 0x128
	'NtQueryInformationAtom', # 0x129
	'NtQueryInformationEnlistment', # 0x12a
	'NtQueryInformationJobObject', # 0x12b
	'NtQueryInformationPort', # 0x12c
	'NtQueryInformationResourceManager', # 0x12d
	'NtQueryInformationTransaction', # 0x12e
	'NtQueryInformationTransactionManager', # 0x12f
	'NtQueryInformationWorkerFactory', # 0x130
	'NtQueryInstallUILanguage', # 0x131
	'NtQueryIntervalProfile', # 0x132
	'NtQueryIoCompletion', # 0x133
	'NtQueryLicenseValue', # 0x134
	'NtQueryMultipleValueKey', # 0x135
	'NtQueryMutant', # 0x136
	'NtQueryOpenSubKeys', # 0x137
	'NtQueryOpenSubKeysEx', # 0x138
	'NtQueryPortInformationProcess', # 0x139
	'NtQueryQuotaInformationFile', # 0x13a
	'NtQuerySecurityAttributesToken', # 0x13b
	'NtQuerySecurityObject', # 0x13c
	'NtQuerySemaphore', # 0x13d
	'NtQuerySymbolicLinkObject', # 0x13e
	'NtQuerySystemEnvironmentValue', # 0x13f
	'NtQuerySystemEnvironmentValueEx', # 0x140
	'NtQuerySystemInformationEx', # 0x141
	'NtQueryTimerResolution', # 0x142
	'NtQueryWnfStateData', # 0x143
	'NtQueryWnfStateNameInformation', # 0x144
	'NtQueueApcThreadEx', # 0x145
	'NtRaiseException', # 0x146
	'NtRaiseHardError', # 0x147
	'NtReadOnlyEnlistment', # 0x148
	'NtRecoverEnlistment', # 0x149
	'NtRecoverResourceManager', # 0x14a
	'NtRecoverTransactionManager', # 0x14b
	'NtRegisterProtocolAddressInformation', # 0x14c
	'NtRegisterThreadTerminatePort', # 0x14d
	'NtReleaseKeyedEvent', # 0x14e
	'NtReleaseWorkerFactoryWorker', # 0x14f
	'NtRemoveIoCompletionEx', # 0x150
	'NtRemoveProcessDebug', # 0x151
	'NtRenameKey', # 0x152
	'NtRenameTransactionManager', # 0x153
	'NtReplaceKey', # 0x154
	'NtReplacePartitionUnit', # 0x155
	'NtReplyWaitReplyPort', # 0x156
	'NtRequestPort', # 0x157
	'NtResetEvent', # 0x158
	'NtResetWriteWatch', # 0x159
	'NtRestoreKey', # 0x15a
	'NtResumeProcess', # 0x15b
	'NtRollbackComplete', # 0x15c
	'NtRollbackEnlistment', # 0x15d
	'NtRollbackTransaction', # 0x15e
	'NtRollforwardTransactionManager', # 0x15f
	'NtSaveKey', # 0x160
	'NtSaveKeyEx', # 0x161
	'NtSaveMergedKeys', # 0x162
	'NtSecureConnectPort', # 0x163
	'NtSerializeBoot', # 0x164
	'NtSetBootEntryOrder', # 0x165
	'NtSetBootOptions', # 0x166
	'NtSetCachedSigningLevel', # 0x167
	'NtSetContextThread', # 0x168
	'NtSetDebugFilterState', # 0x169
	'NtSetDefaultHardErrorPort', # 0x16a
	'NtSetDefaultLocale', # 0x16b
	'NtSetDefaultUILanguage', # 0x16c
	'NtSetDriverEntryOrder', # 0x16d
	'NtSetEaFile', # 0x16e
	'NtSetHighEventPair', # 0x16f
	'NtSetHighWaitLowEventPair', # 0x170
	'NtSetIRTimer', # 0x171
	'NtSetInformationDebugObject', # 0x172
	'NtSetInformationEnlistment', # 0x173
	'NtSetInformationJobObject', # 0x174
	'NtSetInformationKey', # 0x175
	'NtSetInformationResourceManager', # 0x176
	'NtSetInformationToken', # 0x177
	'NtSetInformationTransaction', # 0x178
	'NtSetInformationTransactionManager', # 0x179
	'NtSetInformationVirtualMemory', # 0x17a
	'NtSetInformationWorkerFactory', # 0x17b
	'NtSetIntervalProfile', # 0x17c
	'NtSetIoCompletion', # 0x17d
	'NtSetIoCompletionEx', # 0x17e
	'NtSetLdtEntries', # 0x17f
	'NtSetLowEventPair', # 0x180
	'NtSetLowWaitHighEventPair', # 0x181
	'NtSetQuotaInformationFile', # 0x182
	'NtSetSecurityObject', # 0x183
	'NtSetSystemEnvironmentValue', # 0x184
	'NtSetSystemEnvironmentValueEx', # 0x185
	'NtSetSystemInformation', # 0x186
	'NtSetSystemPowerState', # 0x187
	'NtSetSystemTime', # 0x188
	'NtSetThreadExecutionState', # 0x189
	'NtSetTimer2', # 0x18a
	'NtSetTimerEx', # 0x18b
	'NtSetTimerResolution', # 0x18c
	'NtSetUuidSeed', # 0x18d
	'NtSetVolumeInformationFile', # 0x18e
	'NtSetWnfProcessNotificationEvent', # 0x18f
	'NtShutdownSystem', # 0x190
	'NtShutdownWorkerFactory', # 0x191
	'NtSignalAndWaitForSingleObject', # 0x192
	'NtSinglePhaseReject', # 0x193
	'NtStartProfile', # 0x194
	'NtStopProfile', # 0x195
	'NtSubscribeWnfStateChange', # 0x196
	'NtSuspendProcess', # 0x197
	'NtSuspendThread', # 0x198
	'NtSystemDebugControl', # 0x199
	'NtTerminateJobObject', # 0x19a
	'NtTestAlert', # 0x19b
	'NtThawRegistry', # 0x19c
	'NtThawTransactions', # 0x19d
	'NtTraceControl', # 0x19e
	'NtTranslateFilePath', # 0x19f
	'NtUmsThreadYield', # 0x1a0
	'NtUnloadDriver', # 0x1a1
	'NtUnloadKey', # 0x1a2
	'NtUnloadKey2', # 0x1a3
	'NtUnloadKeyEx', # 0x1a4
	'NtUnlockFile', # 0x1a5
	'NtUnlockVirtualMemory', # 0x1a6
	'NtUnmapViewOfSectionEx', # 0x1a7
	'NtUnsubscribeWnfStateChange', # 0x1a8
	'NtUpdateWnfStateData', # 0x1a9
	'NtVdmControl', # 0x1aa
	'NtWaitForAlertByThreadId', # 0x1ab
	'NtWaitForDebugEvent', # 0x1ac
	'NtWaitForKeyedEvent', # 0x1ad
	'NtWaitForWorkViaWorkerFactory', # 0x1ae
	'NtWaitHighEventPair', # 0x1af
	'NtWaitLowEventPair', # 0x1b0
	],
	[
	'NtUserYieldTask', # 0x0
	'NtUserSetSensorPresence', # 0x1
	'NtUserGetThreadState', # 0x2
	'NtUserPeekMessage', # 0x3
	'NtUserCallOneParam', # 0x4
	'NtUserGetKeyState', # 0x5
	'NtUserInvalidateRect', # 0x6
	'NtUserCallNoParam', # 0x7
	'NtUserGetMessage', # 0x8
	'NtUserMessageCall', # 0x9
	'NtGdiBitBlt', # 0xa
	'NtGdiGetCharSet', # 0xb
	'NtUserGetDC', # 0xc
	'NtGdiSelectBitmap', # 0xd
	'NtUserWaitMessage', # 0xe
	'NtUserTranslateMessage', # 0xf
	'NtUserGetProp', # 0x10
	'NtUserPostMessage', # 0x11
	'NtUserQueryWindow', # 0x12
	'NtUserTranslateAccelerator', # 0x13
	'NtGdiFlush', # 0x14
	'NtUserRedrawWindow', # 0x15
	'NtUserWindowFromPoint', # 0x16
	'NtUserCallMsgFilter', # 0x17
	'NtUserValidateTimerCallback', # 0x18
	'NtUserBeginPaint', # 0x19
	'NtUserSetTimer', # 0x1a
	'NtUserEndPaint', # 0x1b
	'NtUserSetCursor', # 0x1c
	'NtUserKillTimer', # 0x1d
	'NtUserBuildHwndList', # 0x1e
	'NtUserSelectPalette', # 0x1f
	'NtUserCallNextHookEx', # 0x20
	'NtUserHideCaret', # 0x21
	'NtGdiIntersectClipRect', # 0x22
	'NtUserCallHwndLock', # 0x23
	'NtUserGetProcessWindowStation', # 0x24
	'NtGdiDeleteObjectApp', # 0x25
	'NtUserSetWindowPos', # 0x26
	'NtUserShowCaret', # 0x27
	'NtUserEndDeferWindowPosEx', # 0x28
	'NtUserCallHwndParamLock', # 0x29
	'NtUserVkKeyScanEx', # 0x2a
	'NtGdiSetDIBitsToDeviceInternal', # 0x2b
	'NtUserCallTwoParam', # 0x2c
	'NtGdiGetRandomRgn', # 0x2d
	'NtUserCopyAcceleratorTable', # 0x2e
	'NtUserNotifyWinEvent', # 0x2f
	'NtGdiExtSelectClipRgn', # 0x30
	'NtUserIsClipboardFormatAvailable', # 0x31
	'NtUserSetScrollInfo', # 0x32
	'NtGdiStretchBlt', # 0x33
	'NtUserCreateCaret', # 0x34
	'NtGdiRectVisible', # 0x35
	'NtGdiCombineRgn', # 0x36
	'NtGdiGetDCObject', # 0x37
	'NtUserDispatchMessage', # 0x38
	'NtUserRegisterWindowMessage', # 0x39
	'NtGdiExtTextOutW', # 0x3a
	'NtGdiSelectFont', # 0x3b
	'NtGdiRestoreDC', # 0x3c
	'NtGdiSaveDC', # 0x3d
	'NtUserGetForegroundWindow', # 0x3e
	'NtUserShowScrollBar', # 0x3f
	'NtUserFindExistingCursorIcon', # 0x40
	'NtGdiGetDCDword', # 0x41
	'NtGdiGetRegionData', # 0x42
	'NtGdiLineTo', # 0x43
	'NtUserSystemParametersInfo', # 0x44
	'NtGdiGetAppClipBox', # 0x45
	'NtUserGetAsyncKeyState', # 0x46
	'NtUserGetCPD', # 0x47
	'NtUserRemoveProp', # 0x48
	'NtGdiDoPalette', # 0x49
	'NtGdiPolyPolyDraw', # 0x4a
	'NtUserSetCapture', # 0x4b
	'NtUserEnumDisplayMonitors', # 0x4c
	'NtGdiCreateCompatibleBitmap', # 0x4d
	'NtUserSetProp', # 0x4e
	'NtGdiGetTextCharsetInfo', # 0x4f
	'NtUserSBGetParms', # 0x50
	'NtUserGetIconInfo', # 0x51
	'NtUserExcludeUpdateRgn', # 0x52
	'NtUserSetFocus', # 0x53
	'NtGdiExtGetObjectW', # 0x54
	'NtUserGetUpdateRect', # 0x55
	'NtGdiCreateCompatibleDC', # 0x56
	'NtUserGetClipboardSequenceNumber', # 0x57
	'NtGdiCreatePen', # 0x58
	'NtUserShowWindow', # 0x59
	'NtUserGetKeyboardLayoutList', # 0x5a
	'NtGdiPatBlt', # 0x5b
	'NtUserMapVirtualKeyEx', # 0x5c
	'NtUserSetWindowLong', # 0x5d
	'NtGdiHfontCreate', # 0x5e
	'NtUserMoveWindow', # 0x5f
	'NtUserPostThreadMessage', # 0x60
	'NtUserDrawIconEx', # 0x61
	'NtUserGetSystemMenu', # 0x62
	'NtGdiDrawStream', # 0x63
	'NtUserInternalGetWindowText', # 0x64
	'NtUserGetWindowDC', # 0x65
	'NtGdiD3dDrawPrimitives2', # 0x66
	'NtGdiInvertRgn', # 0x67
	'NtGdiGetRgnBox', # 0x68
	'NtGdiGetAndSetDCDword', # 0x69
	'NtGdiMaskBlt', # 0x6a
	'NtGdiGetWidthTable', # 0x6b
	'NtUserScrollDC', # 0x6c
	'NtUserGetObjectInformation', # 0x6d
	'NtGdiCreateBitmap', # 0x6e
	'NtUserFindWindowEx', # 0x6f
	'NtGdiPolyPatBlt', # 0x70
	'NtUserUnhookWindowsHookEx', # 0x71
	'NtGdiGetNearestColor', # 0x72
	'NtGdiTransformPoints', # 0x73
	'NtGdiGetDCPoint', # 0x74
	'NtGdiCreateDIBBrush', # 0x75
	'NtGdiGetTextMetricsW', # 0x76
	'NtUserCreateWindowEx', # 0x77
	'NtUserSetParent', # 0x78
	'NtUserGetKeyboardState', # 0x79
	'NtUserToUnicodeEx', # 0x7a
	'NtUserGetControlBrush', # 0x7b
	'NtUserGetClassName', # 0x7c
	'NtGdiAlphaBlend', # 0x7d
	'NtGdiDdBlt', # 0x7e
	'NtGdiOffsetRgn', # 0x7f
	'NtUserDefSetText', # 0x80
	'NtGdiGetTextFaceW', # 0x81
	'NtGdiStretchDIBitsInternal', # 0x82
	'NtUserSendInput', # 0x83
	'NtUserGetThreadDesktop', # 0x84
	'NtGdiCreateRectRgn', # 0x85
	'NtGdiGetDIBitsInternal', # 0x86
	'NtUserGetUpdateRgn', # 0x87
	'NtGdiDeleteClientObj', # 0x88
	'NtUserGetIconSize', # 0x89
	'NtUserFillWindow', # 0x8a
	'NtGdiExtCreateRegion', # 0x8b
	'NtGdiComputeXformCoefficients', # 0x8c
	'NtUserSetWindowsHookEx', # 0x8d
	'NtUserNotifyProcessCreate', # 0x8e
	'NtGdiUnrealizeObject', # 0x8f
	'NtUserGetTitleBarInfo', # 0x90
	'NtGdiRectangle', # 0x91
	'NtUserSetThreadDesktop', # 0x92
	'NtUserGetDCEx', # 0x93
	'NtUserGetScrollBarInfo', # 0x94
	'NtGdiGetTextExtent', # 0x95
	'NtUserSetWindowFNID', # 0x96
	'NtGdiSetLayout', # 0x97
	'NtUserCalcMenuBar', # 0x98
	'NtUserThunkedMenuItemInfo', # 0x99
	'NtGdiExcludeClipRect', # 0x9a
	'NtGdiCreateDIBSection', # 0x9b
	'NtGdiGetDCforBitmap', # 0x9c
	'NtUserDestroyCursor', # 0x9d
	'NtUserDestroyWindow', # 0x9e
	'NtUserCallHwndParam', # 0x9f
	'NtGdiCreateDIBitmapInternal', # 0xa0
	'NtUserOpenWindowStation', # 0xa1
	'NtGdiDdDeleteSurfaceObject', # 0xa2
	'NtGdiDdCanCreateSurface', # 0xa3
	'NtGdiDdCreateSurface', # 0xa4
	'NtUserSetCursorIconData', # 0xa5
	'NtGdiDdDestroySurface', # 0xa6
	'NtUserCloseDesktop', # 0xa7
	'NtUserOpenDesktop', # 0xa8
	'NtUserSetProcessWindowStation', # 0xa9
	'NtUserGetAtomName', # 0xaa
	'NtGdiDdResetVisrgn', # 0xab
	'NtGdiExtCreatePen', # 0xac
	'NtGdiCreatePaletteInternal', # 0xad
	'NtGdiSetBrushOrg', # 0xae
	'NtUserBuildNameList', # 0xaf
	'NtGdiSetPixel', # 0xb0
	'NtUserRegisterClassExWOW', # 0xb1
	'NtGdiCreatePatternBrushInternal', # 0xb2
	'NtUserGetAncestor', # 0xb3
	'NtGdiGetOutlineTextMetricsInternalW', # 0xb4
	'NtGdiSetBitmapBits', # 0xb5
	'NtUserCloseWindowStation', # 0xb6
	'NtUserGetDoubleClickTime', # 0xb7
	'NtUserEnableScrollBar', # 0xb8
	'NtGdiCreateSolidBrush', # 0xb9
	'NtUserGetClassInfoEx', # 0xba
	'NtGdiCreateClientObj', # 0xbb
	'NtUserUnregisterClass', # 0xbc
	'NtUserDeleteMenu', # 0xbd
	'NtGdiRectInRegion', # 0xbe
	'NtUserScrollWindowEx', # 0xbf
	'NtGdiGetPixel', # 0xc0
	'NtUserSetClassLong', # 0xc1
	'NtUserGetMenuBarInfo', # 0xc2
	'NtGdiDdCreateSurfaceEx', # 0xc3
	'NtGdiDdCreateSurfaceObject', # 0xc4
	'NtGdiGetNearestPaletteIndex', # 0xc5
	'NtGdiDdLockD3D', # 0xc6
	'NtGdiDdUnlockD3D', # 0xc7
	'NtGdiGetCharWidthW', # 0xc8
	'NtUserInvalidateRgn', # 0xc9
	'NtUserGetClipboardOwner', # 0xca
	'NtUserSetWindowRgn', # 0xcb
	'NtUserBitBltSysBmp', # 0xcc
	'NtGdiGetCharWidthInfo', # 0xcd
	'NtUserValidateRect', # 0xce
	'NtUserCloseClipboard', # 0xcf
	'NtUserOpenClipboard', # 0xd0
	'NtGdiGetStockObject', # 0xd1
	'NtUserSetClipboardData', # 0xd2
	'NtUserEnableMenuItem', # 0xd3
	'NtUserAlterWindowStyle', # 0xd4
	'NtGdiFillRgn', # 0xd5
	'NtUserGetWindowPlacement', # 0xd6
	'NtGdiModifyWorldTransform', # 0xd7
	'NtGdiGetFontData', # 0xd8
	'NtUserGetOpenClipboardWindow', # 0xd9
	'NtUserSetThreadState', # 0xda
	'NtGdiOpenDCW', # 0xdb
	'NtUserTrackMouseEvent', # 0xdc
	'NtGdiGetTransform', # 0xdd
	'NtUserDestroyMenu', # 0xde
	'NtGdiGetBitmapBits', # 0xdf
	'NtUserConsoleControl', # 0xe0
	'NtUserSetActiveWindow', # 0xe1
	'NtUserSetInformationThread', # 0xe2
	'NtUserSetWindowPlacement', # 0xe3
	'NtUserGetControlColor', # 0xe4
	'NtGdiSetMetaRgn', # 0xe5
	'NtGdiSetMiterLimit', # 0xe6
	'NtGdiSetVirtualResolution', # 0xe7
	'NtGdiGetRasterizerCaps', # 0xe8
	'NtUserSetWindowWord', # 0xe9
	'NtUserGetClipboardFormatName', # 0xea
	'NtUserRealInternalGetMessage', # 0xeb
	'NtUserCreateLocalMemHandle', # 0xec
	'NtUserAttachThreadInput', # 0xed
	'NtGdiCreateHalftonePalette', # 0xee
	'NtUserPaintMenuBar', # 0xef
	'NtUserSetKeyboardState', # 0xf0
	'NtGdiCombineTransform', # 0xf1
	'NtUserCreateAcceleratorTable', # 0xf2
	'NtUserGetCursorFrameInfo', # 0xf3
	'NtUserGetAltTabInfo', # 0xf4
	'NtUserGetCaretBlinkTime', # 0xf5
	'NtGdiQueryFontAssocInfo', # 0xf6
	'NtUserProcessConnect', # 0xf7
	'NtUserEnumDisplayDevices', # 0xf8
	'NtUserEmptyClipboard', # 0xf9
	'NtUserGetClipboardData', # 0xfa
	'NtUserRemoveMenu', # 0xfb
	'NtGdiSetBoundsRect', # 0xfc
	'NtGdiGetBitmapDimension', # 0xfd
	'NtUserConvertMemHandle', # 0xfe
	'NtUserDestroyAcceleratorTable', # 0xff
	'NtUserGetGUIThreadInfo', # 0x100
	'NtGdiCloseFigure', # 0x101
	'NtUserSetWindowsHookAW', # 0x102
	'NtUserSetMenuDefaultItem', # 0x103
	'NtUserCheckMenuItem', # 0x104
	'NtUserSetWinEventHook', # 0x105
	'NtUserUnhookWinEvent', # 0x106
	'NtUserLockWindowUpdate', # 0x107
	'NtUserSetSystemMenu', # 0x108
	'NtUserThunkedMenuInfo', # 0x109
	'NtGdiBeginPath', # 0x10a
	'NtGdiEndPath', # 0x10b
	'NtGdiFillPath', # 0x10c
	'NtUserCallHwnd', # 0x10d
	'NtUserDdeInitialize', # 0x10e
	'NtUserModifyUserStartupInfoFlags', # 0x10f
	'NtUserCountClipboardFormats', # 0x110
	'NtGdiAddFontMemResourceEx', # 0x111
	'NtGdiEqualRgn', # 0x112
	'NtGdiGetSystemPaletteUse', # 0x113
	'NtGdiRemoveFontMemResourceEx', # 0x114
	'NtUserEnumDisplaySettings', # 0x115
	'NtUserPaintDesktop', # 0x116
	'NtGdiExtEscape', # 0x117
	'NtGdiSetBitmapDimension', # 0x118
	'NtGdiSetFontEnumeration', # 0x119
	'NtUserChangeClipboardChain', # 0x11a
	'NtUserSetClipboardViewer', # 0x11b
	'NtUserShowWindowAsync', # 0x11c
	'NtGdiCreateColorSpace', # 0x11d
	'NtGdiDeleteColorSpace', # 0x11e
	'NtUserActivateKeyboardLayout', # 0x11f
	'NtBindCompositionSurface', # 0x120
	'NtCompositionInputThread', # 0x121
	'NtCreateCompositionInputSink', # 0x122
	'NtCreateCompositionSurfaceHandle', # 0x123
	'NtDCompositionAddCrossDeviceVisualChild', # 0x124
	'NtDCompositionAddVisualChild', # 0x125
	'NtDCompositionBeginFrame', # 0x126
	'NtDCompositionCommitChannel', # 0x127
	'NtDCompositionConfirmFrame', # 0x128
	'NtDCompositionConnectPipe', # 0x129
	'NtDCompositionCreateAndBindSharedSection', # 0x12a
	'NtDCompositionCreateChannel', # 0x12b
	'NtDCompositionCreateConnection', # 0x12c
	'NtDCompositionCreateDwmChannel', # 0x12d
	'NtDCompositionCreateResource', # 0x12e
	'NtDCompositionCurrentBatchId', # 0x12f
	'NtDCompositionDestroyChannel', # 0x130
	'NtDCompositionDestroyConnection', # 0x131
	'NtDCompositionDiscardFrame', # 0x132
	'NtDCompositionDuplicateHandleToProcess', # 0x133
	'NtDCompositionDwmSyncFlush', # 0x134
	'NtDCompositionGetChannels', # 0x135
	'NtDCompositionGetConnectionBatch', # 0x136
	'NtDCompositionGetDeletedResources', # 0x137
	'NtDCompositionGetFrameLegacyTokens', # 0x138
	'NtDCompositionGetFrameStatistics', # 0x139
	'NtDCompositionGetFrameSurfaceUpdates', # 0x13a
	'NtDCompositionOpenSharedResource', # 0x13b
	'NtDCompositionOpenSharedResourceHandle', # 0x13c
	'NtDCompositionReferenceSharedResourceOnDwmChannel', # 0x13d
	'NtDCompositionRegisterThumbnailVisual', # 0x13e
	'NtDCompositionReleaseAllResources', # 0x13f
	'NtDCompositionReleaseResource', # 0x140
	'NtDCompositionRemoveCrossDeviceVisualChild', # 0x141
	'NtDCompositionRemoveVisualChild', # 0x142
	'NtDCompositionReplaceVisualChildren', # 0x143
	'NtDCompositionRetireFrame', # 0x144
	'NtDCompositionSetChannelCommitCompletionEvent', # 0x145
	'NtDCompositionSetDebugCounter', # 0x146
	'NtDCompositionSetResourceAnimationProperty', # 0x147
	'NtDCompositionSetResourceBufferProperty', # 0x148
	'NtDCompositionSetResourceDeletedNotificationTag', # 0x149
	'NtDCompositionSetResourceFloatProperty', # 0x14a
	'NtDCompositionSetResourceHandleProperty', # 0x14b
	'NtDCompositionSetResourceIntegerProperty', # 0x14c
	'NtDCompositionSetResourceReferenceArrayProperty', # 0x14d
	'NtDCompositionSetResourceReferenceProperty', # 0x14e
	'NtDCompositionSignalGpuFence', # 0x14f
	'NtDCompositionSubmitDWMBatch', # 0x150
	'NtDCompositionSynchronize', # 0x151
	'NtDCompositionTelemetryAnimationScenarioBegin', # 0x152
	'NtDCompositionTelemetryAnimationScenarioReference', # 0x153
	'NtDCompositionTelemetryAnimationScenarioUnreference', # 0x154
	'NtDCompositionTelemetrySetApplicationId', # 0x155
	'NtDCompositionTelemetryTouchInteractionBegin', # 0x156
	'NtDCompositionTelemetryTouchInteractionEnd', # 0x157
	'NtDCompositionTelemetryTouchInteractionUpdate', # 0x158
	'NtDCompositionWaitForChannel', # 0x159
	'NtDuplicateCompositionInputSink', # 0x15a
	'NtGdiAbortDoc', # 0x15b
	'NtGdiAbortPath', # 0x15c
	'NtGdiAddEmbFontToDC', # 0x15d
	'NtGdiAddFontResourceW', # 0x15e
	'NtGdiAddRemoteFontToDC', # 0x15f
	'NtGdiAddRemoteMMInstanceToDC', # 0x160
	'NtGdiAngleArc', # 0x161
	'NtGdiAnyLinkedFonts', # 0x162
	'NtGdiArcInternal', # 0x163
	'NtGdiBRUSHOBJ_DeleteRbrush', # 0x164
	'NtGdiBRUSHOBJ_hGetColorTransform', # 0x165
	'NtGdiBRUSHOBJ_pvAllocRbrush', # 0x166
	'NtGdiBRUSHOBJ_pvGetRbrush', # 0x167
	'NtGdiBRUSHOBJ_ulGetBrushColor', # 0x168
	'NtGdiBeginGdiRendering', # 0x169
	'NtGdiCLIPOBJ_bEnum', # 0x16a
	'NtGdiCLIPOBJ_cEnumStart', # 0x16b
	'NtGdiCLIPOBJ_ppoGetPath', # 0x16c
	'NtGdiCancelDC', # 0x16d
	'NtGdiChangeGhostFont', # 0x16e
	'NtGdiCheckBitmapBits', # 0x16f
	'NtGdiClearBitmapAttributes', # 0x170
	'NtGdiClearBrushAttributes', # 0x171
	'NtGdiColorCorrectPalette', # 0x172
	'NtGdiConfigureOPMProtectedOutput', # 0x173
	'NtGdiConvertMetafileRect', # 0x174
	'NtGdiCreateBitmapFromDxSurface', # 0x175
	'NtGdiCreateBitmapFromDxSurface2', # 0x176
	'NtGdiCreateColorTransform', # 0x177
	'NtGdiCreateEllipticRgn', # 0x178
	'NtGdiCreateHatchBrushInternal', # 0x179
	'NtGdiCreateMetafileDC', # 0x17a
	'NtGdiCreateOPMProtectedOutputs', # 0x17b
	'NtGdiCreateRoundRectRgn', # 0x17c
	'NtGdiCreateServerMetaFile', # 0x17d
	'NtGdiCreateSessionMappedDIBSection', # 0x17e
	'NtGdiD3dContextCreate', # 0x17f
	'NtGdiD3dContextDestroy', # 0x180
	'NtGdiD3dContextDestroyAll', # 0x181
	'NtGdiD3dValidateTextureStageState', # 0x182
	'NtGdiDDCCIGetCapabilitiesString', # 0x183
	'NtGdiDDCCIGetCapabilitiesStringLength', # 0x184
	'NtGdiDDCCIGetTimingReport', # 0x185
	'NtGdiDDCCIGetVCPFeature', # 0x186
	'NtGdiDDCCISaveCurrentSettings', # 0x187
	'NtGdiDDCCISetVCPFeature', # 0x188
	'NtGdiDdAddAttachedSurface', # 0x189
	'NtGdiDdAlphaBlt', # 0x18a
	'NtGdiDdAttachSurface', # 0x18b
	'NtGdiDdBeginMoCompFrame', # 0x18c
	'NtGdiDdCanCreateD3DBuffer', # 0x18d
	'NtGdiDdColorControl', # 0x18e
	'NtGdiDdCreateD3DBuffer', # 0x18f
	'NtGdiDdCreateDirectDrawObject', # 0x190
	'NtGdiDdCreateFullscreenSprite', # 0x191
	'NtGdiDdCreateMoComp', # 0x192
	'NtGdiDdDDIAcquireKeyedMutex', # 0x193
	'NtGdiDdDDIAcquireKeyedMutex2', # 0x194
	'NtGdiDdDDICacheHybridQueryValue', # 0x195
	'NtGdiDdDDICheckExclusiveOwnership', # 0x196
	'NtGdiDdDDICheckMonitorPowerState', # 0x197
	'NtGdiDdDDICheckMultiPlaneOverlaySupport', # 0x198
	'NtGdiDdDDICheckOcclusion', # 0x199
	'NtGdiDdDDICheckSharedResourceAccess', # 0x19a
	'NtGdiDdDDICheckVidPnExclusiveOwnership', # 0x19b
	'NtGdiDdDDICloseAdapter', # 0x19c
	'NtGdiDdDDIConfigureSharedResource', # 0x19d
	'NtGdiDdDDICreateAllocation', # 0x19e
	'NtGdiDdDDICreateContext', # 0x19f
	'NtGdiDdDDICreateDCFromMemory', # 0x1a0
	'NtGdiDdDDICreateDevice', # 0x1a1
	'NtGdiDdDDICreateKeyedMutex', # 0x1a2
	'NtGdiDdDDICreateKeyedMutex2', # 0x1a3
	'NtGdiDdDDICreateOutputDupl', # 0x1a4
	'NtGdiDdDDICreateOverlay', # 0x1a5
	'NtGdiDdDDICreateSynchronizationObject', # 0x1a6
	'NtGdiDdDDIDestroyAllocation', # 0x1a7
	'NtGdiDdDDIDestroyContext', # 0x1a8
	'NtGdiDdDDIDestroyDCFromMemory', # 0x1a9
	'NtGdiDdDDIDestroyDevice', # 0x1aa
	'NtGdiDdDDIDestroyKeyedMutex', # 0x1ab
	'NtGdiDdDDIDestroyOutputDupl', # 0x1ac
	'NtGdiDdDDIDestroyOverlay', # 0x1ad
	'NtGdiDdDDIDestroySynchronizationObject', # 0x1ae
	'NtGdiDdDDIEnumAdapters', # 0x1af
	'NtGdiDdDDIEscape', # 0x1b0
	'NtGdiDdDDIFlipOverlay', # 0x1b1
	'NtGdiDdDDIGetCachedHybridQueryValue', # 0x1b2
	'NtGdiDdDDIGetContextInProcessSchedulingPriority', # 0x1b3
	'NtGdiDdDDIGetContextSchedulingPriority', # 0x1b4
	'NtGdiDdDDIGetDeviceState', # 0x1b5
	'NtGdiDdDDIGetDisplayModeList', # 0x1b6
	'NtGdiDdDDIGetMultisampleMethodList', # 0x1b7
	'NtGdiDdDDIGetOverlayState', # 0x1b8
	'NtGdiDdDDIGetPresentHistory', # 0x1b9
	'NtGdiDdDDIGetPresentQueueEvent', # 0x1ba
	'NtGdiDdDDIGetProcessSchedulingPriorityClass', # 0x1bb
	'NtGdiDdDDIGetRuntimeData', # 0x1bc
	'NtGdiDdDDIGetScanLine', # 0x1bd
	'NtGdiDdDDIGetSharedPrimaryHandle', # 0x1be
	'NtGdiDdDDIGetSharedResourceAdapterLuid', # 0x1bf
	'NtGdiDdDDIInvalidateActiveVidPn', # 0x1c0
	'NtGdiDdDDILock', # 0x1c1
	'NtGdiDdDDINetDispGetNextChunkInfo', # 0x1c2
	'NtGdiDdDDINetDispQueryMiracastDisplayDeviceStatus', # 0x1c3
	'NtGdiDdDDINetDispQueryMiracastDisplayDeviceSupport', # 0x1c4
	'NtGdiDdDDINetDispStartMiracastDisplayDevice', # 0x1c5
	'NtGdiDdDDINetDispStopMiracastDisplayDevice', # 0x1c6
	'NtGdiDdDDIOfferAllocations', # 0x1c7
	'NtGdiDdDDIOpenAdapterFromDeviceName', # 0x1c8
	'NtGdiDdDDIOpenAdapterFromHdc', # 0x1c9
	'NtGdiDdDDIOpenAdapterFromLuid', # 0x1ca
	'NtGdiDdDDIOpenKeyedMutex', # 0x1cb
	'NtGdiDdDDIOpenKeyedMutex2', # 0x1cc
	'NtGdiDdDDIOpenNtHandleFromName', # 0x1cd
	'NtGdiDdDDIOpenResource', # 0x1ce
	'NtGdiDdDDIOpenResourceFromNtHandle', # 0x1cf
	'NtGdiDdDDIOpenSyncObjectFromNtHandle', # 0x1d0
	'NtGdiDdDDIOpenSynchronizationObject', # 0x1d1
	'NtGdiDdDDIOutputDuplGetFrameInfo', # 0x1d2
	'NtGdiDdDDIOutputDuplGetMetaData', # 0x1d3
	'NtGdiDdDDIOutputDuplGetPointerShapeData', # 0x1d4
	'NtGdiDdDDIOutputDuplPresent', # 0x1d5
	'NtGdiDdDDIOutputDuplReleaseFrame', # 0x1d6
	'NtGdiDdDDIPinDirectFlipResources', # 0x1d7
	'NtGdiDdDDIPollDisplayChildren', # 0x1d8
	'NtGdiDdDDIPresent', # 0x1d9
	'NtGdiDdDDIPresentMultiPlaneOverlay', # 0x1da
	'NtGdiDdDDIQueryAdapterInfo', # 0x1db
	'NtGdiDdDDIQueryAllocationResidency', # 0x1dc
	'NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName', # 0x1dd
	'NtGdiDdDDIQueryResourceInfo', # 0x1de
	'NtGdiDdDDIQueryResourceInfoFromNtHandle', # 0x1df
	'NtGdiDdDDIQueryStatistics', # 0x1e0
	'NtGdiDdDDIReclaimAllocations', # 0x1e1
	'NtGdiDdDDIReleaseKeyedMutex', # 0x1e2
	'NtGdiDdDDIReleaseKeyedMutex2', # 0x1e3
	'NtGdiDdDDIReleaseProcessVidPnSourceOwners', # 0x1e4
	'NtGdiDdDDIRender', # 0x1e5
	'NtGdiDdDDISetAllocationPriority', # 0x1e6
	'NtGdiDdDDISetContextInProcessSchedulingPriority', # 0x1e7
	'NtGdiDdDDISetContextSchedulingPriority', # 0x1e8
	'NtGdiDdDDISetDisplayMode', # 0x1e9
	'NtGdiDdDDISetDisplayPrivateDriverFormat', # 0x1ea
	'NtGdiDdDDISetGammaRamp', # 0x1eb
	'NtGdiDdDDISetProcessSchedulingPriorityClass', # 0x1ec
	'NtGdiDdDDISetQueuedLimit', # 0x1ed
	'NtGdiDdDDISetStereoEnabled', # 0x1ee
	'NtGdiDdDDISetVidPnSourceOwner', # 0x1ef
	'NtGdiDdDDISetVidPnSourceOwner1', # 0x1f0
	'NtGdiDdDDIShareObjects', # 0x1f1
	'NtGdiDdDDISharedPrimaryLockNotification', # 0x1f2
	'NtGdiDdDDISharedPrimaryUnLockNotification', # 0x1f3
	'NtGdiDdDDISignalSynchronizationObject', # 0x1f4
	'NtGdiDdDDIUnlock', # 0x1f5
	'NtGdiDdDDIUnpinDirectFlipResources', # 0x1f6
	'NtGdiDdDDIUpdateOverlay', # 0x1f7
	'NtGdiDdDDIWaitForIdle', # 0x1f8
	'NtGdiDdDDIWaitForSynchronizationObject', # 0x1f9
	'NtGdiDdDDIWaitForVerticalBlankEvent', # 0x1fa
	'NtGdiDdDDIWaitForVerticalBlankEvent2', # 0x1fb
	'NtGdiDdDeleteDirectDrawObject', # 0x1fc
	'NtGdiDdDestroyD3DBuffer', # 0x1fd
	'NtGdiDdDestroyFullscreenSprite', # 0x1fe
	'NtGdiDdDestroyMoComp', # 0x1ff
	'NtGdiDdEndMoCompFrame', # 0x200
	'NtGdiDdFlip', # 0x201
	'NtGdiDdFlipToGDISurface', # 0x202
	'NtGdiDdGetAvailDriverMemory', # 0x203
	'NtGdiDdGetBltStatus', # 0x204
	'NtGdiDdGetDC', # 0x205
	'NtGdiDdGetDriverInfo', # 0x206
	'NtGdiDdGetDriverState', # 0x207
	'NtGdiDdGetDxHandle', # 0x208
	'NtGdiDdGetFlipStatus', # 0x209
	'NtGdiDdGetInternalMoCompInfo', # 0x20a
	'NtGdiDdGetMoCompBuffInfo', # 0x20b
	'NtGdiDdGetMoCompFormats', # 0x20c
	'NtGdiDdGetMoCompGuids', # 0x20d
	'NtGdiDdGetScanLine', # 0x20e
	'NtGdiDdLock', # 0x20f
	'NtGdiDdNotifyFullscreenSpriteUpdate', # 0x210
	'NtGdiDdQueryDirectDrawObject', # 0x211
	'NtGdiDdQueryMoCompStatus', # 0x212
	'NtGdiDdQueryVisRgnUniqueness', # 0x213
	'NtGdiDdReenableDirectDrawObject', # 0x214
	'NtGdiDdReleaseDC', # 0x215
	'NtGdiDdRenderMoComp', # 0x216
	'NtGdiDdSetColorKey', # 0x217
	'NtGdiDdSetExclusiveMode', # 0x218
	'NtGdiDdSetGammaRamp', # 0x219
	'NtGdiDdSetOverlayPosition', # 0x21a
	'NtGdiDdUnattachSurface', # 0x21b
	'NtGdiDdUnlock', # 0x21c
	'NtGdiDdUpdateOverlay', # 0x21d
	'NtGdiDdWaitForVerticalBlank', # 0x21e
	'NtGdiDeleteColorTransform', # 0x21f
	'NtGdiDescribePixelFormat', # 0x220
	'NtGdiDestroyOPMProtectedOutput', # 0x221
	'NtGdiDestroyPhysicalMonitor', # 0x222
	'NtGdiDoBanding', # 0x223
	'NtGdiDrawEscape', # 0x224
	'NtGdiDvpAcquireNotification', # 0x225
	'NtGdiDvpCanCreateVideoPort', # 0x226
	'NtGdiDvpColorControl', # 0x227
	'NtGdiDvpCreateVideoPort', # 0x228
	'NtGdiDvpDestroyVideoPort', # 0x229
	'NtGdiDvpFlipVideoPort', # 0x22a
	'NtGdiDvpGetVideoPortBandwidth', # 0x22b
	'NtGdiDvpGetVideoPortConnectInfo', # 0x22c
	'NtGdiDvpGetVideoPortField', # 0x22d
	'NtGdiDvpGetVideoPortFlipStatus', # 0x22e
	'NtGdiDvpGetVideoPortInputFormats', # 0x22f
	'NtGdiDvpGetVideoPortLine', # 0x230
	'NtGdiDvpGetVideoPortOutputFormats', # 0x231
	'NtGdiDvpGetVideoSignalStatus', # 0x232
	'NtGdiDvpReleaseNotification', # 0x233
	'NtGdiDvpUpdateVideoPort', # 0x234
	'NtGdiDvpWaitForVideoPortSync', # 0x235
	'NtGdiDwmCreatedBitmapRemotingOutput', # 0x236
	'NtGdiDxgGenericThunk', # 0x237
	'NtGdiEllipse', # 0x238
	'NtGdiEnableEudc', # 0x239
	'NtGdiEndDoc', # 0x23a
	'NtGdiEndGdiRendering', # 0x23b
	'NtGdiEndPage', # 0x23c
	'NtGdiEngAlphaBlend', # 0x23d
	'NtGdiEngAssociateSurface', # 0x23e
	'NtGdiEngBitBlt', # 0x23f
	'NtGdiEngCheckAbort', # 0x240
	'NtGdiEngComputeGlyphSet', # 0x241
	'NtGdiEngCopyBits', # 0x242
	'NtGdiEngCreateBitmap', # 0x243
	'NtGdiEngCreateClip', # 0x244
	'NtGdiEngCreateDeviceBitmap', # 0x245
	'NtGdiEngCreateDeviceSurface', # 0x246
	'NtGdiEngCreatePalette', # 0x247
	'NtGdiEngDeleteClip', # 0x248
	'NtGdiEngDeletePalette', # 0x249
	'NtGdiEngDeletePath', # 0x24a
	'NtGdiEngDeleteSurface', # 0x24b
	'NtGdiEngEraseSurface', # 0x24c
	'NtGdiEngFillPath', # 0x24d
	'NtGdiEngGradientFill', # 0x24e
	'NtGdiEngLineTo', # 0x24f
	'NtGdiEngLockSurface', # 0x250
	'NtGdiEngMarkBandingSurface', # 0x251
	'NtGdiEngPaint', # 0x252
	'NtGdiEngPlgBlt', # 0x253
	'NtGdiEngStretchBlt', # 0x254
	'NtGdiEngStretchBltROP', # 0x255
	'NtGdiEngStrokeAndFillPath', # 0x256
	'NtGdiEngStrokePath', # 0x257
	'NtGdiEngTextOut', # 0x258
	'NtGdiEngTransparentBlt', # 0x259
	'NtGdiEngUnlockSurface', # 0x25a
	'NtGdiEnumFonts', # 0x25b
	'NtGdiEnumObjects', # 0x25c
	'NtGdiEudcLoadUnloadLink', # 0x25d
	'NtGdiExtFloodFill', # 0x25e
	'NtGdiFONTOBJ_cGetAllGlyphHandles', # 0x25f
	'NtGdiFONTOBJ_cGetGlyphs', # 0x260
	'NtGdiFONTOBJ_pQueryGlyphAttrs', # 0x261
	'NtGdiFONTOBJ_pfdg', # 0x262
	'NtGdiFONTOBJ_pifi', # 0x263
	'NtGdiFONTOBJ_pvTrueTypeFontFile', # 0x264
	'NtGdiFONTOBJ_pxoGetXform', # 0x265
	'NtGdiFONTOBJ_vGetInfo', # 0x266
	'NtGdiFlattenPath', # 0x267
	'NtGdiFontIsLinked', # 0x268
	'NtGdiForceUFIMapping', # 0x269
	'NtGdiFrameRgn', # 0x26a
	'NtGdiFullscreenControl', # 0x26b
	'NtGdiGetBoundsRect', # 0x26c
	'NtGdiGetCOPPCompatibleOPMInformation', # 0x26d
	'NtGdiGetCertificate', # 0x26e
	'NtGdiGetCertificateSize', # 0x26f
	'NtGdiGetCharABCWidthsW', # 0x270
	'NtGdiGetCharacterPlacementW', # 0x271
	'NtGdiGetColorAdjustment', # 0x272
	'NtGdiGetColorSpaceforBitmap', # 0x273
	'NtGdiGetCurrentDpiInfo', # 0x274
	'NtGdiGetDeviceCaps', # 0x275
	'NtGdiGetDeviceCapsAll', # 0x276
	'NtGdiGetDeviceGammaRamp', # 0x277
	'NtGdiGetDeviceWidth', # 0x278
	'NtGdiGetDhpdev', # 0x279
	'NtGdiGetETM', # 0x27a
	'NtGdiGetEmbUFI', # 0x27b
	'NtGdiGetEmbedFonts', # 0x27c
	'NtGdiGetEudcTimeStampEx', # 0x27d
	'NtGdiGetFontFileData', # 0x27e
	'NtGdiGetFontFileInfo', # 0x27f
	'NtGdiGetFontResourceInfoInternalW', # 0x280
	'NtGdiGetFontUnicodeRanges', # 0x281
	'NtGdiGetGlyphIndicesW', # 0x282
	'NtGdiGetGlyphIndicesWInternal', # 0x283
	'NtGdiGetGlyphOutline', # 0x284
	'NtGdiGetKerningPairs', # 0x285
	'NtGdiGetLinkedUFIs', # 0x286
	'NtGdiGetMiterLimit', # 0x287
	'NtGdiGetMonitorID', # 0x288
	'NtGdiGetNumberOfPhysicalMonitors', # 0x289
	'NtGdiGetOPMInformation', # 0x28a
	'NtGdiGetOPMRandomNumber', # 0x28b
	'NtGdiGetObjectBitmapHandle', # 0x28c
	'NtGdiGetPath', # 0x28d
	'NtGdiGetPerBandInfo', # 0x28e
	'NtGdiGetPhysicalMonitorDescription', # 0x28f
	'NtGdiGetPhysicalMonitors', # 0x290
	'NtGdiGetRealizationInfo', # 0x291
	'NtGdiGetServerMetaFileBits', # 0x292
	'NtGdiGetSpoolMessage', # 0x293
	'NtGdiGetStats', # 0x294
	'NtGdiGetStringBitmapW', # 0x295
	'NtGdiGetSuggestedOPMProtectedOutputArraySize', # 0x296
	'NtGdiGetTextExtentExW', # 0x297
	'NtGdiGetUFI', # 0x298
	'NtGdiGetUFIPathname', # 0x299
	'NtGdiGradientFill', # 0x29a
	'NtGdiHLSurfGetInformation', # 0x29b
	'NtGdiHLSurfSetInformation', # 0x29c
	'NtGdiHT_Get8BPPFormatPalette', # 0x29d
	'NtGdiHT_Get8BPPMaskPalette', # 0x29e
	'NtGdiIcmBrushInfo', # 0x29f
	'NtGdiInit', # 0x2a0
	'NtGdiInitSpool', # 0x2a1
	'NtGdiMakeFontDir', # 0x2a2
	'NtGdiMakeInfoDC', # 0x2a3
	'NtGdiMakeObjectUnXferable', # 0x2a4
	'NtGdiMakeObjectXferable', # 0x2a5
	'NtGdiMirrorWindowOrg', # 0x2a6
	'NtGdiMonoBitmap', # 0x2a7
	'NtGdiMoveTo', # 0x2a8
	'NtGdiOffsetClipRgn', # 0x2a9
	'NtGdiPATHOBJ_bEnum', # 0x2aa
	'NtGdiPATHOBJ_bEnumClipLines', # 0x2ab
	'NtGdiPATHOBJ_vEnumStart', # 0x2ac
	'NtGdiPATHOBJ_vEnumStartClipLines', # 0x2ad
	'NtGdiPATHOBJ_vGetBounds', # 0x2ae
	'NtGdiPathToRegion', # 0x2af
	'NtGdiPlgBlt', # 0x2b0
	'NtGdiPolyDraw', # 0x2b1
	'NtGdiPolyTextOutW', # 0x2b2
	'NtGdiPtInRegion', # 0x2b3
	'NtGdiPtVisible', # 0x2b4
	'NtGdiQueryFonts', # 0x2b5
	'NtGdiRemoveFontResourceW', # 0x2b6
	'NtGdiRemoveMergeFont', # 0x2b7
	'NtGdiResetDC', # 0x2b8
	'NtGdiResizePalette', # 0x2b9
	'NtGdiRoundRect', # 0x2ba
	'NtGdiSTROBJ_bEnum', # 0x2bb
	'NtGdiSTROBJ_bEnumPositionsOnly', # 0x2bc
	'NtGdiSTROBJ_bGetAdvanceWidths', # 0x2bd
	'NtGdiSTROBJ_dwGetCodePage', # 0x2be
	'NtGdiSTROBJ_vEnumStart', # 0x2bf
	'NtGdiScaleViewportExtEx', # 0x2c0
	'NtGdiScaleWindowExtEx', # 0x2c1
	'NtGdiSelectBrush', # 0x2c2
	'NtGdiSelectClipPath', # 0x2c3
	'NtGdiSelectPen', # 0x2c4
	'NtGdiSetBitmapAttributes', # 0x2c5
	'NtGdiSetBrushAttributes', # 0x2c6
	'NtGdiSetColorAdjustment', # 0x2c7
	'NtGdiSetColorSpace', # 0x2c8
	'NtGdiSetDeviceGammaRamp', # 0x2c9
	'NtGdiSetFontXform', # 0x2ca
	'NtGdiSetIcmMode', # 0x2cb
	'NtGdiSetLinkedUFIs', # 0x2cc
	'NtGdiSetMagicColors', # 0x2cd
	'NtGdiSetOPMSigningKeyAndSequenceNumbers', # 0x2ce
	'NtGdiSetPUMPDOBJ', # 0x2cf
	'NtGdiSetPixelFormat', # 0x2d0
	'NtGdiSetRectRgn', # 0x2d1
	'NtGdiSetSizeDevice', # 0x2d2
	'NtGdiSetSystemPaletteUse', # 0x2d3
	'NtGdiSetTextJustification', # 0x2d4
	'NtGdiSetUMPDSandboxState', # 0x2d5
	'NtGdiStartDoc', # 0x2d6
	'NtGdiStartPage', # 0x2d7
	'NtGdiStrokeAndFillPath', # 0x2d8
	'NtGdiStrokePath', # 0x2d9
	'NtGdiSwapBuffers', # 0x2da
	'NtGdiTransparentBlt', # 0x2db
	'NtGdiUMPDEngFreeUserMem', # 0x2dc
	'NtGdiUnloadPrinterDriver', # 0x2dd
	'NtGdiUnmapMemFont', # 0x2de
	'NtGdiUpdateColors', # 0x2df
	'NtGdiUpdateTransform', # 0x2e0
	'NtGdiWidenPath', # 0x2e1
	'NtGdiXFORMOBJ_bApplyXform', # 0x2e2
	'NtGdiXFORMOBJ_iGetXform', # 0x2e3
	'NtGdiXLATEOBJ_cGetPalette', # 0x2e4
	'NtGdiXLATEOBJ_hGetColorTransform', # 0x2e5
	'NtGdiXLATEOBJ_iXlate', # 0x2e6
	'NtNotifyPresentToCompositionSurface', # 0x2e7
	'NtOpenCompositionSurfaceDirtyRegion', # 0x2e8
	'NtOpenCompositionSurfaceSectionInfo', # 0x2e9
	'NtOpenCompositionSurfaceSwapChainHandleInfo', # 0x2ea
	'NtQueryCompositionInputSink', # 0x2eb
	'NtQueryCompositionInputSinkLuid', # 0x2ec
	'NtQueryCompositionSurfaceBinding', # 0x2ed
	'NtQueryCompositionSurfaceRenderingRealization', # 0x2ee
	'NtQueryCompositionSurfaceStatistics', # 0x2ef
	'NtSetCompositionSurfaceBufferCompositionMode', # 0x2f0
	'NtSetCompositionSurfaceIndependentFlipInfo', # 0x2f1
	'NtSetCompositionSurfaceOutOfFrameDirectFlipNotification', # 0x2f2
	'NtSetCompositionSurfaceStatistics', # 0x2f3
	'NtTokenManagerCreateCompositionTokenHandle', # 0x2f4
	'NtTokenManagerDeleteOutstandingDirectFlipTokens', # 0x2f5
	'NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates', # 0x2f6
	'NtTokenManagerOpenEvent', # 0x2f7
	'NtTokenManagerOpenSection', # 0x2f8
	'NtTokenManagerThread', # 0x2f9
	'NtUnBindCompositionSurface', # 0x2fa
	'NtUpdateInputSinkTransforms', # 0x2fb
	'NtUserAcquireIAMKey', # 0x2fc
	'NtUserAddClipboardFormatListener', # 0x2fd
	'NtUserAssociateInputContext', # 0x2fe
	'NtUserAutoPromoteMouseInPointer', # 0x2ff
	'NtUserAutoRotateScreen', # 0x300
	'NtUserBlockInput', # 0x301
	'NtUserBuildHimcList', # 0x302
	'NtUserBuildPropList', # 0x303
	'NtUserCalculatePopupWindowPosition', # 0x304
	'NtUserCallHwndOpt', # 0x305
	'NtUserCanBrokerForceForeground', # 0x306
	'NtUserChangeDisplaySettings', # 0x307
	'NtUserChangeWindowMessageFilterEx', # 0x308
	'NtUserCheckAccessForIntegrityLevel', # 0x309
	'NtUserCheckProcessForClipboardAccess', # 0x30a
	'NtUserCheckProcessSession', # 0x30b
	'NtUserCheckWindowThreadDesktop', # 0x30c
	'NtUserChildWindowFromPointEx', # 0x30d
	'NtUserClearForeground', # 0x30e
	'NtUserClipCursor', # 0x30f
	'NtUserCompositionInputSinkLuidFromPoint', # 0x310
	'NtUserCreateDCompositionHwndTarget', # 0x311
	'NtUserCreateDesktopEx', # 0x312
	'NtUserCreateInputContext', # 0x313
	'NtUserCreateWindowStation', # 0x314
	'NtUserCtxDisplayIOCtl', # 0x315
	'NtUserDeferWindowPosAndBand', # 0x316
	'NtUserDelegateCapturePointers', # 0x317
	'NtUserDelegateInput', # 0x318
	'NtUserDestroyDCompositionHwndTarget', # 0x319
	'NtUserDestroyInputContext', # 0x31a
	'NtUserDisableImmersiveOwner', # 0x31b
	'NtUserDisableProcessWindowFiltering', # 0x31c
	'NtUserDisableThreadIme', # 0x31d
	'NtUserDiscardPointerFrameMessages', # 0x31e
	'NtUserDisplayConfigGetDeviceInfo', # 0x31f
	'NtUserDisplayConfigSetDeviceInfo', # 0x320
	'NtUserDoSoundConnect', # 0x321
	'NtUserDoSoundDisconnect', # 0x322
	'NtUserDragDetect', # 0x323
	'NtUserDragObject', # 0x324
	'NtUserDrawAnimatedRects', # 0x325
	'NtUserDrawCaption', # 0x326
	'NtUserDrawCaptionTemp', # 0x327
	'NtUserDrawMenuBarTemp', # 0x328
	'NtUserDwmGetRemoteSessionOcclusionEvent', # 0x329
	'NtUserDwmGetRemoteSessionOcclusionState', # 0x32a
	'NtUserDwmStartRedirection', # 0x32b
	'NtUserDwmStopRedirection', # 0x32c
	'NtUserDwmValidateWindow', # 0x32d
	'NtUserEnableIAMAccess', # 0x32e
	'NtUserEnableMouseInPointer', # 0x32f
	'NtUserEnableMouseInputForCursorSuppression', # 0x330
	'NtUserEnableTouchPad', # 0x331
	'NtUserEndMenu', # 0x332
	'NtUserEvent', # 0x333
	'NtUserFlashWindowEx', # 0x334
	'NtUserFrostCrashedWindow', # 0x335
	'NtUserGetAppImeLevel', # 0x336
	'NtUserGetAutoRotationState', # 0x337
	'NtUserGetCIMSSM', # 0x338
	'NtUserGetCaretPos', # 0x339
	'NtUserGetClipCursor', # 0x33a
	'NtUserGetClipboardAccessToken', # 0x33b
	'NtUserGetClipboardViewer', # 0x33c
	'NtUserGetComboBoxInfo', # 0x33d
	'NtUserGetCurrentInputMessageSource', # 0x33e
	'NtUserGetCursorDims', # 0x33f
	'NtUserGetCursorInfo', # 0x340
	'NtUserGetDesktopID', # 0x341
	'NtUserGetDisplayAutoRotationPreferences', # 0x342
	'NtUserGetDisplayAutoRotationPreferencesByProcessId', # 0x343
	'NtUserGetDisplayConfigBufferSizes', # 0x344
	'NtUserGetDpiForMonitor', # 0x345
	'NtUserGetGestureConfig', # 0x346
	'NtUserGetGestureExtArgs', # 0x347
	'NtUserGetGestureInfo', # 0x348
	'NtUserGetGuiResources', # 0x349
	'NtUserGetHimetricScaleFactorFromPixelLocation', # 0x34a
	'NtUserGetImeHotKey', # 0x34b
	'NtUserGetImeInfoEx', # 0x34c
	'NtUserGetInputLocaleInfo', # 0x34d
	'NtUserGetInternalWindowPos', # 0x34e
	'NtUserGetKeyNameText', # 0x34f
	'NtUserGetKeyboardLayoutName', # 0x350
	'NtUserGetLayeredWindowAttributes', # 0x351
	'NtUserGetListBoxInfo', # 0x352
	'NtUserGetMenuIndex', # 0x353
	'NtUserGetMenuItemRect', # 0x354
	'NtUserGetMouseMovePointsEx', # 0x355
	'NtUserGetOwnerTransformedMonitorRect', # 0x356
	'NtUserGetPhysicalDeviceRect', # 0x357
	'NtUserGetPointerCursorId', # 0x358
	'NtUserGetPointerDevice', # 0x359
	'NtUserGetPointerDeviceCursors', # 0x35a
	'NtUserGetPointerDeviceProperties', # 0x35b
	'NtUserGetPointerDeviceRects', # 0x35c
	'NtUserGetPointerDevices', # 0x35d
	'NtUserGetPointerInfoList', # 0x35e
	'NtUserGetPointerInputTransform', # 0x35f
	'NtUserGetPointerType', # 0x360
	'NtUserGetPrecisionTouchPadConfiguration', # 0x361
	'NtUserGetPriorityClipboardFormat', # 0x362
	'NtUserGetProcessDpiAwareness', # 0x363
	'NtUserGetProcessUIContextInformation', # 0x364
	'NtUserGetQueueEventStatus', # 0x365
	'NtUserGetRawInputBuffer', # 0x366
	'NtUserGetRawInputData', # 0x367
	'NtUserGetRawInputDeviceInfo', # 0x368
	'NtUserGetRawInputDeviceList', # 0x369
	'NtUserGetRawPointerDeviceData', # 0x36a
	'NtUserGetRegisteredRawInputDevices', # 0x36b
	'NtUserGetTopLevelWindow', # 0x36c
	'NtUserGetTouchInputInfo', # 0x36d
	'NtUserGetTouchValidationStatus', # 0x36e
	'NtUserGetUpdatedClipboardFormats', # 0x36f
	'NtUserGetWOWClass', # 0x370
	'NtUserGetWindowBand', # 0x371
	'NtUserGetWindowCompositionAttribute', # 0x372
	'NtUserGetWindowCompositionInfo', # 0x373
	'NtUserGetWindowDisplayAffinity', # 0x374
	'NtUserGetWindowFeedbackSetting', # 0x375
	'NtUserGetWindowMinimizeRect', # 0x376
	'NtUserGetWindowRgnEx', # 0x377
	'NtUserGhostWindowFromHungWindow', # 0x378
	'NtUserHandleDelegatedInput', # 0x379
	'NtUserHardErrorControl', # 0x37a
	'NtUserHidePointerContactVisualization', # 0x37b
	'NtUserHiliteMenuItem', # 0x37c
	'NtUserHungWindowFromGhostWindow', # 0x37d
	'NtUserHwndQueryRedirectionInfo', # 0x37e
	'NtUserHwndSetRedirectionInfo', # 0x37f
	'NtUserImpersonateDdeClientWindow', # 0x380
	'NtUserInitTask', # 0x381
	'NtUserInitialize', # 0x382
	'NtUserInitializeClientPfnArrays', # 0x383
	'NtUserInitializeTouchInjection', # 0x384
	'NtUserInjectGesture', # 0x385
	'NtUserInjectTouchInput', # 0x386
	'NtUserInternalClipCursor', # 0x387
	'NtUserInternalGetWindowIcon', # 0x388
	'NtUserIsMouseInPointerEnabled', # 0x389
	'NtUserIsMouseInputEnabled', # 0x38a
	'NtUserIsTopLevelWindow', # 0x38b
	'NtUserIsTouchWindow', # 0x38c
	'NtUserLayoutCompleted', # 0x38d
	'NtUserLinkDpiCursor', # 0x38e
	'NtUserLoadKeyboardLayoutEx', # 0x38f
	'NtUserLockWindowStation', # 0x390
	'NtUserLockWorkStation', # 0x391
	'NtUserLogicalToPerMonitorDPIPhysicalPoint', # 0x392
	'NtUserLogicalToPhysicalPoint', # 0x393
	'NtUserMNDragLeave', # 0x394
	'NtUserMNDragOver', # 0x395
	'NtUserMagControl', # 0x396
	'NtUserMagGetContextInformation', # 0x397
	'NtUserMagSetContextInformation', # 0x398
	'NtUserMenuItemFromPoint', # 0x399
	'NtUserMinMaximize', # 0x39a
	'NtUserModifyWindowTouchCapability', # 0x39b
	'NtUserNotifyIMEStatus', # 0x39c
	'NtUserOpenInputDesktop', # 0x39d
	'NtUserOpenThreadDesktop', # 0x39e
	'NtUserPaintMonitor', # 0x39f
	'NtUserPerMonitorDPIPhysicalToLogicalPoint', # 0x3a0
	'NtUserPhysicalToLogicalPoint', # 0x3a1
	'NtUserPrintWindow', # 0x3a2
	'NtUserPromoteMouseInPointer', # 0x3a3
	'NtUserPromotePointer', # 0x3a4
	'NtUserQueryBSDRWindow', # 0x3a5
	'NtUserQueryDisplayConfig', # 0x3a6
	'NtUserQueryInformationThread', # 0x3a7
	'NtUserQueryInputContext', # 0x3a8
	'NtUserQuerySendMessage', # 0x3a9
	'NtUserRealChildWindowFromPoint', # 0x3aa
	'NtUserRealWaitMessageEx', # 0x3ab
	'NtUserRegisterBSDRWindow', # 0x3ac
	'NtUserRegisterEdgy', # 0x3ad
	'NtUserRegisterErrorReportingDialog', # 0x3ae
	'NtUserRegisterHotKey', # 0x3af
	'NtUserRegisterPointerDeviceNotifications', # 0x3b0
	'NtUserRegisterPointerInputTarget', # 0x3b1
	'NtUserRegisterRawInputDevices', # 0x3b2
	'NtUserRegisterServicesProcess', # 0x3b3
	'NtUserRegisterSessionPort', # 0x3b4
	'NtUserRegisterTasklist', # 0x3b5
	'NtUserRegisterTouchHitTestingWindow', # 0x3b6
	'NtUserRegisterTouchPadCapable', # 0x3b7
	'NtUserRegisterUserApiHook', # 0x3b8
	'NtUserRemoteConnect', # 0x3b9
	'NtUserRemoteRedrawRectangle', # 0x3ba
	'NtUserRemoteRedrawScreen', # 0x3bb
	'NtUserRemoteStopScreenUpdates', # 0x3bc
	'NtUserRemoveClipboardFormatListener', # 0x3bd
	'NtUserReportInertia', # 0x3be
	'NtUserResolveDesktopForWOW', # 0x3bf
	'NtUserSendEventMessage', # 0x3c0
	'NtUserSetActivationFilter', # 0x3c1
	'NtUserSetActiveProcess', # 0x3c2
	'NtUserSetAppImeLevel', # 0x3c3
	'NtUserSetAutoRotation', # 0x3c4
	'NtUserSetBrokeredForeground', # 0x3c5
	'NtUserSetCalibrationData', # 0x3c6
	'NtUserSetChildWindowNoActivate', # 0x3c7
	'NtUserSetClassWord', # 0x3c8
	'NtUserSetCursorContents', # 0x3c9
	'NtUserSetDisplayAutoRotationPreferences', # 0x3ca
	'NtUserSetDisplayConfig', # 0x3cb
	'NtUserSetDisplayMapping', # 0x3cc
	'NtUserSetFallbackForeground', # 0x3cd
	'NtUserSetGestureConfig', # 0x3ce
	'NtUserSetImeHotKey', # 0x3cf
	'NtUserSetImeInfoEx', # 0x3d0
	'NtUserSetImeOwnerWindow', # 0x3d1
	'NtUserSetImmersiveBackgroundWindow', # 0x3d2
	'NtUserSetInternalWindowPos', # 0x3d3
	'NtUserSetLayeredWindowAttributes', # 0x3d4
	'NtUserSetMenu', # 0x3d5
	'NtUserSetMenuContextHelpId', # 0x3d6
	'NtUserSetMenuFlagRtoL', # 0x3d7
	'NtUserSetMirrorRendering', # 0x3d8
	'NtUserSetObjectInformation', # 0x3d9
	'NtUserSetPrecisionTouchPadConfiguration', # 0x3da
	'NtUserSetProcessDpiAwareness', # 0x3db
	'NtUserSetProcessRestrictionExemption', # 0x3dc
	'NtUserSetProcessUIAccessZorder', # 0x3dd
	'NtUserSetShellWindowEx', # 0x3de
	'NtUserSetSysColors', # 0x3df
	'NtUserSetSystemCursor', # 0x3e0
	'NtUserSetSystemTimer', # 0x3e1
	'NtUserSetThreadInputBlocked', # 0x3e2
	'NtUserSetThreadLayoutHandles', # 0x3e3
	'NtUserSetWindowBand', # 0x3e4
	'NtUserSetWindowCompositionAttribute', # 0x3e5
	'NtUserSetWindowCompositionTransition', # 0x3e6
	'NtUserSetWindowDisplayAffinity', # 0x3e7
	'NtUserSetWindowFeedbackSetting', # 0x3e8
	'NtUserSetWindowRgnEx', # 0x3e9
	'NtUserSetWindowStationUser', # 0x3ea
	'NtUserShowSystemCursor', # 0x3eb
	'NtUserShutdownBlockReasonCreate', # 0x3ec
	'NtUserShutdownBlockReasonQuery', # 0x3ed
	'NtUserShutdownReasonDestroy', # 0x3ee
	'NtUserSignalRedirectionStartComplete', # 0x3ef
	'NtUserSlicerControl', # 0x3f0
	'NtUserSoundSentry', # 0x3f1
	'NtUserSwitchDesktop', # 0x3f2
	'NtUserTestForInteractiveUser', # 0x3f3
	'NtUserTrackPopupMenuEx', # 0x3f4
	'NtUserTransformPoint', # 0x3f5
	'NtUserTransformRect', # 0x3f6
	'NtUserUndelegateInput', # 0x3f7
	'NtUserUnloadKeyboardLayout', # 0x3f8
	'NtUserUnlockWindowStation', # 0x3f9
	'NtUserUnregisterHotKey', # 0x3fa
	'NtUserUnregisterSessionPort', # 0x3fb
	'NtUserUnregisterUserApiHook', # 0x3fc
	'NtUserUpdateDefaultDesktopThumbnail', # 0x3fd
	'NtUserUpdateInputContext', # 0x3fe
	'NtUserUpdateInstance', # 0x3ff
	'NtUserUpdateLayeredWindow', # 0x400
	'NtUserUpdatePerUserSystemParameters', # 0x401
	'NtUserUpdateWindowInputSinkHints', # 0x402
	'NtUserUpdateWindowTransform', # 0x403
	'NtUserUserHandleGrantAccess', # 0x404
	'NtUserValidateHandleSecure', # 0x405
	'NtUserWaitAvailableMessageEx', # 0x406
	'NtUserWaitForInputIdle', # 0x407
	'NtUserWaitForMsgAndEvent', # 0x408
	'NtUserWaitForRedirectionStartComplete', # 0x409
	'NtUserWindowFromPhysicalPoint', # 0x40a
	'NtValidateCompositionSurfaceHandle', # 0x40b
	'NtUserSetClassLongPtr', # 0x40c
	'NtUserSetWindowLongPtr', # 0x40d
	],
]
