syscalls = [
	[
	'NtWorkerFactoryWorkerReady', # 0x0
	'NtMapUserPhysicalPagesScatter', # 0x1
	'NtWaitForSingleObject', # 0x2
	'NtCallbackReturn', # 0x3
	'NtReadFile', # 0x4
	'NtDeviceIoControlFile', # 0x5
	'NtWriteFile', # 0x6
	'NtRemoveIoCompletion', # 0x7
	'NtReleaseSemaphore', # 0x8
	'NtReplyWaitReceivePort', # 0x9
	'NtReplyPort', # 0xa
	'NtSetInformationThread', # 0xb
	'NtSetEvent', # 0xc
	'NtClose', # 0xd
	'NtQueryObject', # 0xe
	'NtQueryInformationFile', # 0xf
	'NtOpenKey', # 0x10
	'NtEnumerateValueKey', # 0x11
	'NtFindAtom', # 0x12
	'NtQueryDefaultLocale', # 0x13
	'NtQueryKey', # 0x14
	'NtQueryValueKey', # 0x15
	'NtAllocateVirtualMemory', # 0x16
	'NtQueryInformationProcess', # 0x17
	'NtWaitForMultipleObjects32', # 0x18
	'NtWriteFileGather', # 0x19
	'NtSetInformationProcess', # 0x1a
	'NtCreateKey', # 0x1b
	'NtFreeVirtualMemory', # 0x1c
	'NtImpersonateClientOfPort', # 0x1d
	'NtReleaseMutant', # 0x1e
	'NtQueryInformationToken', # 0x1f
	'NtRequestWaitReplyPort', # 0x20
	'NtQueryVirtualMemory', # 0x21
	'NtOpenThreadToken', # 0x22
	'NtQueryInformationThread', # 0x23
	'NtOpenProcess', # 0x24
	'NtSetInformationFile', # 0x25
	'NtMapViewOfSection', # 0x26
	'NtAccessCheckAndAuditAlarm', # 0x27
	'NtUnmapViewOfSection', # 0x28
	'NtReplyWaitReceivePortEx', # 0x29
	'NtTerminateProcess', # 0x2a
	'NtSetEventBoostPriority', # 0x2b
	'NtReadFileScatter', # 0x2c
	'NtOpenThreadTokenEx', # 0x2d
	'NtOpenProcessTokenEx', # 0x2e
	'NtQueryPerformanceCounter', # 0x2f
	'NtEnumerateKey', # 0x30
	'NtOpenFile', # 0x31
	'NtDelayExecution', # 0x32
	'NtQueryDirectoryFile', # 0x33
	'NtQuerySystemInformation', # 0x34
	'NtOpenSection', # 0x35
	'NtQueryTimer', # 0x36
	'NtFsControlFile', # 0x37
	'NtWriteVirtualMemory', # 0x38
	'NtCloseObjectAuditAlarm', # 0x39
	'NtDuplicateObject', # 0x3a
	'NtQueryAttributesFile', # 0x3b
	'NtClearEvent', # 0x3c
	'NtReadVirtualMemory', # 0x3d
	'NtOpenEvent', # 0x3e
	'NtAdjustPrivilegesToken', # 0x3f
	'NtDuplicateToken', # 0x40
	'NtContinue', # 0x41
	'NtQueryDefaultUILanguage', # 0x42
	'NtQueueApcThread', # 0x43
	'NtYieldExecution', # 0x44
	'NtAddAtom', # 0x45
	'NtCreateEvent', # 0x46
	'NtQueryVolumeInformationFile', # 0x47
	'NtCreateSection', # 0x48
	'NtFlushBuffersFile', # 0x49
	'NtApphelpCacheControl', # 0x4a
	'NtCreateProcessEx', # 0x4b
	'NtCreateThread', # 0x4c
	'NtIsProcessInJob', # 0x4d
	'NtProtectVirtualMemory', # 0x4e
	'NtQuerySection', # 0x4f
	'NtResumeThread', # 0x50
	'NtTerminateThread', # 0x51
	'NtReadRequestData', # 0x52
	'NtCreateFile', # 0x53
	'NtQueryEvent', # 0x54
	'NtWriteRequestData', # 0x55
	'NtOpenDirectoryObject', # 0x56
	'NtAccessCheckByTypeAndAuditAlarm', # 0x57
	'UNKNOWN', # 0x58
	'NtWaitForMultipleObjects', # 0x59
	'NtSetInformationObject', # 0x5a
	'NtCancelIoFile', # 0x5b
	'NtTraceEvent', # 0x5c
	'NtPowerInformation', # 0x5d
	'NtSetValueKey', # 0x5e
	'NtCancelTimer', # 0x5f
	'NtSetTimer', # 0x60
	'NtAcceptConnectPort', # 0x61
	'NtAccessCheck', # 0x62
	'NtAccessCheckByType', # 0x63
	'NtAccessCheckByTypeResultList', # 0x64
	'NtAccessCheckByTypeResultListAndAuditAlarm', # 0x65
	'NtAccessCheckByTypeResultListAndAuditAlarmByHandle', # 0x66
	'NtAddAtomEx', # 0x67
	'NtAddBootEntry', # 0x68
	'NtAddDriverEntry', # 0x69
	'NtAdjustGroupsToken', # 0x6a
	'NtAdjustTokenClaimsAndDeviceGroups', # 0x6b
	'NtAlertResumeThread', # 0x6c
	'NtAlertThread', # 0x6d
	'NtAlertThreadByThreadId', # 0x6e
	'NtAllocateLocallyUniqueId', # 0x6f
	'NtAllocateReserveObject', # 0x70
	'NtAllocateUserPhysicalPages', # 0x71
	'NtAllocateUuids', # 0x72
	'NtAlpcAcceptConnectPort', # 0x73
	'NtAlpcCancelMessage', # 0x74
	'NtAlpcConnectPort', # 0x75
	'NtAlpcConnectPortEx', # 0x76
	'NtAlpcCreatePort', # 0x77
	'NtAlpcCreatePortSection', # 0x78
	'NtAlpcCreateResourceReserve', # 0x79
	'NtAlpcCreateSectionView', # 0x7a
	'NtAlpcCreateSecurityContext', # 0x7b
	'NtAlpcDeletePortSection', # 0x7c
	'NtAlpcDeleteResourceReserve', # 0x7d
	'NtAlpcDeleteSectionView', # 0x7e
	'NtAlpcDeleteSecurityContext', # 0x7f
	'NtAlpcDisconnectPort', # 0x80
	'NtAlpcImpersonateClientOfPort', # 0x81
	'NtAlpcOpenSenderProcess', # 0x82
	'NtAlpcOpenSenderThread', # 0x83
	'NtAlpcQueryInformation', # 0x84
	'NtAlpcQueryInformationMessage', # 0x85
	'NtAlpcRevokeSecurityContext', # 0x86
	'NtAlpcSendWaitReceivePort', # 0x87
	'NtAlpcSetInformation', # 0x88
	'NtAreMappedFilesTheSame', # 0x89
	'NtAssignProcessToJobObject', # 0x8a
	'NtAssociateWaitCompletionPacket', # 0x8b
	'NtCancelIoFileEx', # 0x8c
	'NtCancelSynchronousIoFile', # 0x8d
	'NtCancelWaitCompletionPacket', # 0x8e
	'NtCommitComplete', # 0x8f
	'NtCommitEnlistment', # 0x90
	'NtCommitTransaction', # 0x91
	'NtCompactKeys', # 0x92
	'NtCompareTokens', # 0x93
	'NtCompleteConnectPort', # 0x94
	'NtCompressKey', # 0x95
	'NtConnectPort', # 0x96
	'NtCreateDebugObject', # 0x97
	'NtCreateDirectoryObject', # 0x98
	'NtCreateDirectoryObjectEx', # 0x99
	'NtCreateEnlistment', # 0x9a
	'NtCreateEventPair', # 0x9b
	'NtCreateIRTimer', # 0x9c
	'NtCreateIoCompletion', # 0x9d
	'NtCreateJobObject', # 0x9e
	'NtCreateJobSet', # 0x9f
	'NtCreateKeyTransacted', # 0xa0
	'NtCreateKeyedEvent', # 0xa1
	'NtCreateLowBoxToken', # 0xa2
	'NtCreateMailslotFile', # 0xa3
	'NtCreateMutant', # 0xa4
	'NtCreateNamedPipeFile', # 0xa5
	'NtCreatePagingFile', # 0xa6
	'NtCreatePort', # 0xa7
	'NtCreatePrivateNamespace', # 0xa8
	'NtCreateProcess', # 0xa9
	'NtCreateProfile', # 0xaa
	'NtCreateProfileEx', # 0xab
	'NtCreateResourceManager', # 0xac
	'NtCreateSemaphore', # 0xad
	'NtCreateSymbolicLinkObject', # 0xae
	'NtCreateThreadEx', # 0xaf
	'NtCreateTimer', # 0xb0
	'NtCreateToken', # 0xb1
	'NtCreateTokenEx', # 0xb2
	'NtCreateTransaction', # 0xb3
	'NtCreateTransactionManager', # 0xb4
	'NtCreateUserProcess', # 0xb5
	'NtCreateWaitCompletionPacket', # 0xb6
	'NtCreateWaitablePort', # 0xb7
	'NtCreateWnfStateName', # 0xb8
	'NtCreateWorkerFactory', # 0xb9
	'NtDebugActiveProcess', # 0xba
	'NtDebugContinue', # 0xbb
	'NtDeleteAtom', # 0xbc
	'NtDeleteBootEntry', # 0xbd
	'NtDeleteDriverEntry', # 0xbe
	'NtDeleteFile', # 0xbf
	'NtDeleteKey', # 0xc0
	'NtDeleteObjectAuditAlarm', # 0xc1
	'NtDeletePrivateNamespace', # 0xc2
	'NtDeleteValueKey', # 0xc3
	'NtDeleteWnfStateData', # 0xc4
	'NtDeleteWnfStateName', # 0xc5
	'NtDisableLastKnownGood', # 0xc6
	'NtDisplayString', # 0xc7
	'NtDrawText', # 0xc8
	'NtEnableLastKnownGood', # 0xc9
	'NtEnumerateBootEntries', # 0xca
	'NtEnumerateDriverEntries', # 0xcb
	'NtEnumerateSystemEnvironmentValuesEx', # 0xcc
	'NtEnumerateTransactionObject', # 0xcd
	'NtExtendSection', # 0xce
	'NtFilterBootOption', # 0xcf
	'NtFilterToken', # 0xd0
	'NtFilterTokenEx', # 0xd1
	'NtFlushBuffersFileEx', # 0xd2
	'NtFlushInstallUILanguage', # 0xd3
	'NtFlushInstructionCache', # 0xd4
	'NtFlushKey', # 0xd5
	'NtFlushProcessWriteBuffers', # 0xd6
	'NtFlushVirtualMemory', # 0xd7
	'NtFlushWriteBuffer', # 0xd8
	'NtFreeUserPhysicalPages', # 0xd9
	'NtFreezeRegistry', # 0xda
	'NtFreezeTransactions', # 0xdb
	'NtGetCachedSigningLevel', # 0xdc
	'NtGetContextThread', # 0xdd
	'NtGetCurrentProcessorNumber', # 0xde
	'NtGetDevicePowerState', # 0xdf
	'NtGetMUIRegistryInfo', # 0xe0
	'NtGetNextProcess', # 0xe1
	'NtGetNextThread', # 0xe2
	'NtGetNlsSectionPtr', # 0xe3
	'NtGetNotificationResourceManager', # 0xe4
	'NtGetWriteWatch', # 0xe5
	'NtImpersonateAnonymousToken', # 0xe6
	'NtImpersonateThread', # 0xe7
	'NtInitializeNlsFiles', # 0xe8
	'NtInitializeRegistry', # 0xe9
	'NtInitiatePowerAction', # 0xea
	'NtIsSystemResumeAutomatic', # 0xeb
	'NtIsUILanguageComitted', # 0xec
	'NtListenPort', # 0xed
	'NtLoadDriver', # 0xee
	'NtLoadKey', # 0xef
	'NtLoadKey2', # 0xf0
	'NtLoadKeyEx', # 0xf1
	'NtLockFile', # 0xf2
	'NtLockProductActivationKeys', # 0xf3
	'NtLockRegistryKey', # 0xf4
	'NtLockVirtualMemory', # 0xf5
	'NtMakePermanentObject', # 0xf6
	'NtMakeTemporaryObject', # 0xf7
	'NtMapCMFModule', # 0xf8
	'NtMapUserPhysicalPages', # 0xf9
	'NtModifyBootEntry', # 0xfa
	'NtModifyDriverEntry', # 0xfb
	'NtNotifyChangeDirectoryFile', # 0xfc
	'NtNotifyChangeKey', # 0xfd
	'NtNotifyChangeMultipleKeys', # 0xfe
	'NtNotifyChangeSession', # 0xff
	'NtOpenEnlistment', # 0x100
	'NtOpenEventPair', # 0x101
	'NtOpenIoCompletion', # 0x102
	'NtOpenJobObject', # 0x103
	'NtOpenKeyEx', # 0x104
	'NtOpenKeyTransacted', # 0x105
	'NtOpenKeyTransactedEx', # 0x106
	'NtOpenKeyedEvent', # 0x107
	'NtOpenMutant', # 0x108
	'NtOpenObjectAuditAlarm', # 0x109
	'NtOpenPrivateNamespace', # 0x10a
	'NtOpenProcessToken', # 0x10b
	'NtOpenResourceManager', # 0x10c
	'NtOpenSemaphore', # 0x10d
	'NtOpenSession', # 0x10e
	'NtOpenSymbolicLinkObject', # 0x10f
	'NtOpenThread', # 0x110
	'NtOpenTimer', # 0x111
	'NtOpenTransaction', # 0x112
	'NtOpenTransactionManager', # 0x113
	'NtPlugPlayControl', # 0x114
	'NtPrePrepareComplete', # 0x115
	'NtPrePrepareEnlistment', # 0x116
	'NtPrepareComplete', # 0x117
	'NtPrepareEnlistment', # 0x118
	'NtPrivilegeCheck', # 0x119
	'NtPrivilegeObjectAuditAlarm', # 0x11a
	'NtPrivilegedServiceAuditAlarm', # 0x11b
	'NtPropagationComplete', # 0x11c
	'NtPropagationFailed', # 0x11d
	'NtPulseEvent', # 0x11e
	'NtQueryBootEntryOrder', # 0x11f
	'NtQueryBootOptions', # 0x120
	'NtQueryDebugFilterState', # 0x121
	'NtQueryDirectoryObject', # 0x122
	'NtQueryDriverEntryOrder', # 0x123
	'NtQueryEaFile', # 0x124
	'NtQueryFullAttributesFile', # 0x125
	'NtQueryInformationAtom', # 0x126
	'NtQueryInformationEnlistment', # 0x127
	'NtQueryInformationJobObject', # 0x128
	'NtQueryInformationPort', # 0x129
	'NtQueryInformationResourceManager', # 0x12a
	'NtQueryInformationTransaction', # 0x12b
	'NtQueryInformationTransactionManager', # 0x12c
	'NtQueryInformationWorkerFactory', # 0x12d
	'NtQueryInstallUILanguage', # 0x12e
	'NtQueryIntervalProfile', # 0x12f
	'NtQueryIoCompletion', # 0x130
	'NtQueryLicenseValue', # 0x131
	'NtQueryMultipleValueKey', # 0x132
	'NtQueryMutant', # 0x133
	'NtQueryOpenSubKeys', # 0x134
	'NtQueryOpenSubKeysEx', # 0x135
	'NtQueryPortInformationProcess', # 0x136
	'NtQueryQuotaInformationFile', # 0x137
	'NtQuerySecurityAttributesToken', # 0x138
	'NtQuerySecurityObject', # 0x139
	'NtQuerySemaphore', # 0x13a
	'NtQuerySymbolicLinkObject', # 0x13b
	'NtQuerySystemEnvironmentValue', # 0x13c
	'NtQuerySystemEnvironmentValueEx', # 0x13d
	'NtQuerySystemInformationEx', # 0x13e
	'NtQueryTimerResolution', # 0x13f
	'NtQueryWnfStateData', # 0x140
	'NtQueryWnfStateNameInformation', # 0x141
	'NtQueueApcThreadEx', # 0x142
	'NtRaiseException', # 0x143
	'NtRaiseHardError', # 0x144
	'NtReadOnlyEnlistment', # 0x145
	'NtRecoverEnlistment', # 0x146
	'NtRecoverResourceManager', # 0x147
	'NtRecoverTransactionManager', # 0x148
	'NtRegisterProtocolAddressInformation', # 0x149
	'NtRegisterThreadTerminatePort', # 0x14a
	'NtReleaseKeyedEvent', # 0x14b
	'NtReleaseWorkerFactoryWorker', # 0x14c
	'NtRemoveIoCompletionEx', # 0x14d
	'NtRemoveProcessDebug', # 0x14e
	'NtRenameKey', # 0x14f
	'NtRenameTransactionManager', # 0x150
	'NtReplaceKey', # 0x151
	'NtReplacePartitionUnit', # 0x152
	'NtReplyWaitReplyPort', # 0x153
	'NtRequestPort', # 0x154
	'NtResetEvent', # 0x155
	'NtResetWriteWatch', # 0x156
	'NtRestoreKey', # 0x157
	'NtResumeProcess', # 0x158
	'NtRollbackComplete', # 0x159
	'NtRollbackEnlistment', # 0x15a
	'NtRollbackTransaction', # 0x15b
	'NtRollforwardTransactionManager', # 0x15c
	'NtSaveKey', # 0x15d
	'NtSaveKeyEx', # 0x15e
	'NtSaveMergedKeys', # 0x15f
	'NtSecureConnectPort', # 0x160
	'NtSerializeBoot', # 0x161
	'NtSetBootEntryOrder', # 0x162
	'NtSetBootOptions', # 0x163
	'NtSetCachedSigningLevel', # 0x164
	'NtSetContextThread', # 0x165
	'NtSetDebugFilterState', # 0x166
	'NtSetDefaultHardErrorPort', # 0x167
	'NtSetDefaultLocale', # 0x168
	'NtSetDefaultUILanguage', # 0x169
	'NtSetDriverEntryOrder', # 0x16a
	'NtSetEaFile', # 0x16b
	'NtSetHighEventPair', # 0x16c
	'NtSetHighWaitLowEventPair', # 0x16d
	'NtSetIRTimer', # 0x16e
	'NtSetInformationDebugObject', # 0x16f
	'NtSetInformationEnlistment', # 0x170
	'NtSetInformationJobObject', # 0x171
	'NtSetInformationKey', # 0x172
	'NtSetInformationResourceManager', # 0x173
	'NtSetInformationToken', # 0x174
	'NtSetInformationTransaction', # 0x175
	'NtSetInformationTransactionManager', # 0x176
	'NtSetInformationVirtualMemory', # 0x177
	'NtSetInformationWorkerFactory', # 0x178
	'NtSetIntervalProfile', # 0x179
	'NtSetIoCompletion', # 0x17a
	'NtSetIoCompletionEx', # 0x17b
	'NtSetLdtEntries', # 0x17c
	'NtSetLowEventPair', # 0x17d
	'NtSetLowWaitHighEventPair', # 0x17e
	'NtSetQuotaInformationFile', # 0x17f
	'NtSetSecurityObject', # 0x180
	'NtSetSystemEnvironmentValue', # 0x181
	'NtSetSystemEnvironmentValueEx', # 0x182
	'NtSetSystemInformation', # 0x183
	'NtSetSystemPowerState', # 0x184
	'NtSetSystemTime', # 0x185
	'NtSetThreadExecutionState', # 0x186
	'NtSetTimerEx', # 0x187
	'NtSetTimerResolution', # 0x188
	'NtSetUuidSeed', # 0x189
	'NtSetVolumeInformationFile', # 0x18a
	'NtShutdownSystem', # 0x18b
	'NtShutdownWorkerFactory', # 0x18c
	'NtSignalAndWaitForSingleObject', # 0x18d
	'NtSinglePhaseReject', # 0x18e
	'NtStartProfile', # 0x18f
	'NtStopProfile', # 0x190
	'NtSubscribeWnfStateChange', # 0x191
	'NtSuspendProcess', # 0x192
	'NtSuspendThread', # 0x193
	'NtSystemDebugControl', # 0x194
	'NtTerminateJobObject', # 0x195
	'NtTestAlert', # 0x196
	'NtThawRegistry', # 0x197
	'NtThawTransactions', # 0x198
	'NtTraceControl', # 0x199
	'NtTranslateFilePath', # 0x19a
	'NtUmsThreadYield', # 0x19b
	'NtUnloadDriver', # 0x19c
	'NtUnloadKey', # 0x19d
	'NtUnloadKey2', # 0x19e
	'NtUnloadKeyEx', # 0x19f
	'NtUnlockFile', # 0x1a0
	'NtUnlockVirtualMemory', # 0x1a1
	'NtUnmapViewOfSectionEx', # 0x1a2
	'NtUnsubscribeWnfStateChange', # 0x1a3
	'NtUpdateWnfStateData', # 0x1a4
	'NtVdmControl', # 0x1a5
	'NtWaitForAlertByThreadId', # 0x1a6
	'NtWaitForDebugEvent', # 0x1a7
	'NtWaitForKeyedEvent', # 0x1a8
	'NtWaitForWnfNotifications', # 0x1a9
	'NtWaitForWorkViaWorkerFactory', # 0x1aa
	'NtWaitHighEventPair', # 0x1ab
	'NtWaitLowEventPair', # 0x1ac
	],
	[
	'NtUserYieldTask', # 0x0
	'NtUserGetThreadState', # 0x1
	'NtUserPeekMessage', # 0x2
	'NtUserCallOneParam', # 0x3
	'NtUserGetKeyState', # 0x4
	'NtUserInvalidateRect', # 0x5
	'NtUserCallNoParam', # 0x6
	'NtUserGetMessage', # 0x7
	'NtUserMessageCall', # 0x8
	'NtGdiBitBlt', # 0x9
	'NtGdiGetCharSet', # 0xa
	'NtUserGetDC', # 0xb
	'NtGdiSelectBitmap', # 0xc
	'NtUserWaitMessage', # 0xd
	'NtUserTranslateMessage', # 0xe
	'NtUserGetProp', # 0xf
	'NtUserPostMessage', # 0x10
	'NtUserQueryWindow', # 0x11
	'NtUserTranslateAccelerator', # 0x12
	'NtGdiFlush', # 0x13
	'NtUserRedrawWindow', # 0x14
	'NtUserWindowFromPoint', # 0x15
	'NtUserCallMsgFilter', # 0x16
	'NtUserValidateTimerCallback', # 0x17
	'NtUserBeginPaint', # 0x18
	'NtUserSetTimer', # 0x19
	'NtUserEndPaint', # 0x1a
	'NtUserSetCursor', # 0x1b
	'NtUserKillTimer', # 0x1c
	'NtUserBuildHwndList', # 0x1d
	'NtUserSelectPalette', # 0x1e
	'NtUserCallNextHookEx', # 0x1f
	'NtUserHideCaret', # 0x20
	'NtGdiIntersectClipRect', # 0x21
	'NtUserCallHwndLock', # 0x22
	'NtUserGetProcessWindowStation', # 0x23
	'NtGdiDeleteObjectApp', # 0x24
	'NtUserSetWindowPos', # 0x25
	'NtUserShowCaret', # 0x26
	'NtUserEndDeferWindowPosEx', # 0x27
	'NtUserCallHwndParamLock', # 0x28
	'NtUserVkKeyScanEx', # 0x29
	'NtGdiSetDIBitsToDeviceInternal', # 0x2a
	'NtUserCallTwoParam', # 0x2b
	'NtGdiGetRandomRgn', # 0x2c
	'NtUserCopyAcceleratorTable', # 0x2d
	'NtUserNotifyWinEvent', # 0x2e
	'NtGdiExtSelectClipRgn', # 0x2f
	'NtUserIsClipboardFormatAvailable', # 0x30
	'NtUserSetScrollInfo', # 0x31
	'NtGdiStretchBlt', # 0x32
	'NtUserCreateCaret', # 0x33
	'NtGdiRectVisible', # 0x34
	'NtGdiCombineRgn', # 0x35
	'NtGdiGetDCObject', # 0x36
	'NtUserDispatchMessage', # 0x37
	'NtUserRegisterWindowMessage', # 0x38
	'NtGdiExtTextOutW', # 0x39
	'NtGdiSelectFont', # 0x3a
	'NtGdiRestoreDC', # 0x3b
	'NtGdiSaveDC', # 0x3c
	'NtUserGetForegroundWindow', # 0x3d
	'NtUserShowScrollBar', # 0x3e
	'NtUserFindExistingCursorIcon', # 0x3f
	'NtGdiGetDCDword', # 0x40
	'NtGdiGetRegionData', # 0x41
	'NtGdiLineTo', # 0x42
	'NtUserSystemParametersInfo', # 0x43
	'NtGdiGetAppClipBox', # 0x44
	'NtUserGetAsyncKeyState', # 0x45
	'NtUserGetCPD', # 0x46
	'NtUserRemoveProp', # 0x47
	'NtGdiDoPalette', # 0x48
	'NtGdiPolyPolyDraw', # 0x49
	'NtUserSetCapture', # 0x4a
	'NtUserEnumDisplayMonitors', # 0x4b
	'NtGdiCreateCompatibleBitmap', # 0x4c
	'NtUserSetProp', # 0x4d
	'NtGdiGetTextCharsetInfo', # 0x4e
	'NtUserSBGetParms', # 0x4f
	'NtUserGetIconInfo', # 0x50
	'NtUserExcludeUpdateRgn', # 0x51
	'NtUserSetFocus', # 0x52
	'NtGdiExtGetObjectW', # 0x53
	'NtUserGetUpdateRect', # 0x54
	'NtGdiCreateCompatibleDC', # 0x55
	'NtUserGetClipboardSequenceNumber', # 0x56
	'NtGdiCreatePen', # 0x57
	'NtUserShowWindow', # 0x58
	'NtUserGetKeyboardLayoutList', # 0x59
	'NtGdiPatBlt', # 0x5a
	'NtUserMapVirtualKeyEx', # 0x5b
	'NtUserSetWindowLong', # 0x5c
	'NtGdiHfontCreate', # 0x5d
	'NtUserMoveWindow', # 0x5e
	'NtUserPostThreadMessage', # 0x5f
	'NtUserDrawIconEx', # 0x60
	'NtUserGetSystemMenu', # 0x61
	'NtGdiDrawStream', # 0x62
	'NtUserInternalGetWindowText', # 0x63
	'NtUserGetWindowDC', # 0x64
	'NtGdiD3dDrawPrimitives2', # 0x65
	'NtGdiInvertRgn', # 0x66
	'NtGdiGetRgnBox', # 0x67
	'NtGdiGetAndSetDCDword', # 0x68
	'NtGdiMaskBlt', # 0x69
	'NtGdiGetWidthTable', # 0x6a
	'NtUserScrollDC', # 0x6b
	'NtUserGetObjectInformation', # 0x6c
	'NtGdiCreateBitmap', # 0x6d
	'NtUserFindWindowEx', # 0x6e
	'NtGdiPolyPatBlt', # 0x6f
	'NtUserUnhookWindowsHookEx', # 0x70
	'NtGdiGetNearestColor', # 0x71
	'NtGdiTransformPoints', # 0x72
	'NtGdiGetDCPoint', # 0x73
	'NtGdiCreateDIBBrush', # 0x74
	'NtGdiGetTextMetricsW', # 0x75
	'NtUserCreateWindowEx', # 0x76
	'NtUserSetParent', # 0x77
	'NtUserGetKeyboardState', # 0x78
	'NtUserToUnicodeEx', # 0x79
	'NtUserGetControlBrush', # 0x7a
	'NtUserGetClassName', # 0x7b
	'NtGdiAlphaBlend', # 0x7c
	'NtGdiDdBlt', # 0x7d
	'NtGdiOffsetRgn', # 0x7e
	'NtUserDefSetText', # 0x7f
	'NtGdiGetTextFaceW', # 0x80
	'NtGdiStretchDIBitsInternal', # 0x81
	'NtUserSendInput', # 0x82
	'NtUserGetThreadDesktop', # 0x83
	'NtGdiCreateRectRgn', # 0x84
	'NtGdiGetDIBitsInternal', # 0x85
	'NtUserGetUpdateRgn', # 0x86
	'NtGdiDeleteClientObj', # 0x87
	'NtUserGetIconSize', # 0x88
	'NtUserFillWindow', # 0x89
	'NtGdiExtCreateRegion', # 0x8a
	'NtGdiComputeXformCoefficients', # 0x8b
	'NtUserSetWindowsHookEx', # 0x8c
	'NtUserNotifyProcessCreate', # 0x8d
	'NtGdiUnrealizeObject', # 0x8e
	'NtUserGetTitleBarInfo', # 0x8f
	'NtGdiRectangle', # 0x90
	'NtUserSetThreadDesktop', # 0x91
	'NtUserGetDCEx', # 0x92
	'NtUserGetScrollBarInfo', # 0x93
	'NtGdiGetTextExtent', # 0x94
	'NtUserSetWindowFNID', # 0x95
	'NtGdiSetLayout', # 0x96
	'NtUserCalcMenuBar', # 0x97
	'NtUserThunkedMenuItemInfo', # 0x98
	'NtGdiExcludeClipRect', # 0x99
	'NtGdiCreateDIBSection', # 0x9a
	'NtGdiGetDCforBitmap', # 0x9b
	'NtUserDestroyCursor', # 0x9c
	'NtUserDestroyWindow', # 0x9d
	'NtUserCallHwndParam', # 0x9e
	'NtGdiCreateDIBitmapInternal', # 0x9f
	'NtUserOpenWindowStation', # 0xa0
	'NtGdiDdDeleteSurfaceObject', # 0xa1
	'NtGdiDdCanCreateSurface', # 0xa2
	'NtGdiDdCreateSurface', # 0xa3
	'NtUserSetCursorIconData', # 0xa4
	'NtGdiDdDestroySurface', # 0xa5
	'NtUserCloseDesktop', # 0xa6
	'NtUserOpenDesktop', # 0xa7
	'NtUserSetProcessWindowStation', # 0xa8
	'NtUserGetAtomName', # 0xa9
	'NtGdiDdResetVisrgn', # 0xaa
	'NtGdiExtCreatePen', # 0xab
	'NtGdiCreatePaletteInternal', # 0xac
	'NtGdiSetBrushOrg', # 0xad
	'NtUserBuildNameList', # 0xae
	'NtGdiSetPixel', # 0xaf
	'NtUserRegisterClassExWOW', # 0xb0
	'NtGdiCreatePatternBrushInternal', # 0xb1
	'NtUserGetAncestor', # 0xb2
	'NtGdiGetOutlineTextMetricsInternalW', # 0xb3
	'NtGdiSetBitmapBits', # 0xb4
	'NtUserCloseWindowStation', # 0xb5
	'NtUserGetDoubleClickTime', # 0xb6
	'NtUserEnableScrollBar', # 0xb7
	'NtGdiCreateSolidBrush', # 0xb8
	'NtUserGetClassInfoEx', # 0xb9
	'NtGdiCreateClientObj', # 0xba
	'NtUserUnregisterClass', # 0xbb
	'NtUserDeleteMenu', # 0xbc
	'NtGdiRectInRegion', # 0xbd
	'NtUserScrollWindowEx', # 0xbe
	'NtGdiGetPixel', # 0xbf
	'NtUserSetClassLong', # 0xc0
	'NtUserGetMenuBarInfo', # 0xc1
	'NtGdiDdCreateSurfaceEx', # 0xc2
	'NtGdiDdCreateSurfaceObject', # 0xc3
	'NtGdiGetNearestPaletteIndex', # 0xc4
	'NtGdiDdLockD3D', # 0xc5
	'NtGdiDdUnlockD3D', # 0xc6
	'NtGdiGetCharWidthW', # 0xc7
	'NtUserInvalidateRgn', # 0xc8
	'NtUserGetClipboardOwner', # 0xc9
	'NtUserSetWindowRgn', # 0xca
	'NtUserBitBltSysBmp', # 0xcb
	'NtGdiGetCharWidthInfo', # 0xcc
	'NtUserValidateRect', # 0xcd
	'NtUserCloseClipboard', # 0xce
	'NtUserOpenClipboard', # 0xcf
	'NtGdiGetStockObject', # 0xd0
	'NtUserSetClipboardData', # 0xd1
	'NtUserEnableMenuItem', # 0xd2
	'NtUserAlterWindowStyle', # 0xd3
	'NtGdiFillRgn', # 0xd4
	'NtUserGetWindowPlacement', # 0xd5
	'NtGdiModifyWorldTransform', # 0xd6
	'NtGdiGetFontData', # 0xd7
	'NtUserGetOpenClipboardWindow', # 0xd8
	'NtUserSetThreadState', # 0xd9
	'NtGdiOpenDCW', # 0xda
	'NtUserTrackMouseEvent', # 0xdb
	'NtGdiGetTransform', # 0xdc
	'NtUserDestroyMenu', # 0xdd
	'NtGdiGetBitmapBits', # 0xde
	'NtUserConsoleControl', # 0xdf
	'NtUserSetActiveWindow', # 0xe0
	'NtUserSetInformationThread', # 0xe1
	'NtUserSetWindowPlacement', # 0xe2
	'NtUserGetControlColor', # 0xe3
	'NtGdiSetMetaRgn', # 0xe4
	'NtGdiSetMiterLimit', # 0xe5
	'NtGdiSetVirtualResolution', # 0xe6
	'NtGdiGetRasterizerCaps', # 0xe7
	'NtUserSetWindowWord', # 0xe8
	'NtUserGetClipboardFormatName', # 0xe9
	'NtUserRealInternalGetMessage', # 0xea
	'NtUserCreateLocalMemHandle', # 0xeb
	'NtUserAttachThreadInput', # 0xec
	'NtGdiCreateHalftonePalette', # 0xed
	'NtUserPaintMenuBar', # 0xee
	'NtUserSetKeyboardState', # 0xef
	'NtGdiCombineTransform', # 0xf0
	'NtUserCreateAcceleratorTable', # 0xf1
	'NtUserGetCursorFrameInfo', # 0xf2
	'NtUserGetAltTabInfo', # 0xf3
	'NtUserGetCaretBlinkTime', # 0xf4
	'NtGdiQueryFontAssocInfo', # 0xf5
	'NtUserProcessConnect', # 0xf6
	'NtUserEnumDisplayDevices', # 0xf7
	'NtUserEmptyClipboard', # 0xf8
	'NtUserGetClipboardData', # 0xf9
	'NtUserRemoveMenu', # 0xfa
	'NtGdiSetBoundsRect', # 0xfb
	'NtGdiGetBitmapDimension', # 0xfc
	'NtUserConvertMemHandle', # 0xfd
	'NtUserDestroyAcceleratorTable', # 0xfe
	'NtUserGetGUIThreadInfo', # 0xff
	'NtGdiCloseFigure', # 0x100
	'NtUserSetWindowsHookAW', # 0x101
	'NtUserSetMenuDefaultItem', # 0x102
	'NtUserCheckMenuItem', # 0x103
	'NtUserSetWinEventHook', # 0x104
	'NtUserUnhookWinEvent', # 0x105
	'NtUserLockWindowUpdate', # 0x106
	'NtUserSetSystemMenu', # 0x107
	'NtUserThunkedMenuInfo', # 0x108
	'NtGdiBeginPath', # 0x109
	'NtGdiEndPath', # 0x10a
	'NtGdiFillPath', # 0x10b
	'NtUserCallHwnd', # 0x10c
	'NtUserDdeInitialize', # 0x10d
	'NtUserModifyUserStartupInfoFlags', # 0x10e
	'NtUserCountClipboardFormats', # 0x10f
	'NtGdiAddFontMemResourceEx', # 0x110
	'NtGdiEqualRgn', # 0x111
	'NtGdiGetSystemPaletteUse', # 0x112
	'NtGdiRemoveFontMemResourceEx', # 0x113
	'NtUserEnumDisplaySettings', # 0x114
	'NtUserPaintDesktop', # 0x115
	'NtGdiExtEscape', # 0x116
	'NtGdiSetBitmapDimension', # 0x117
	'NtGdiSetFontEnumeration', # 0x118
	'NtUserChangeClipboardChain', # 0x119
	'NtUserSetClipboardViewer', # 0x11a
	'NtUserShowWindowAsync', # 0x11b
	'NtGdiCreateColorSpace', # 0x11c
	'NtGdiDeleteColorSpace', # 0x11d
	'NtUserActivateKeyboardLayout', # 0x11e
	'NtBindCompositionSurface', # 0x11f
	'NtCreateCompositionSurfaceHandle', # 0x120
	'NtDCompositionAddCrossDeviceVisualChild', # 0x121
	'NtDCompositionAddVisualChild', # 0x122
	'NtDCompositionBeginFrame', # 0x123
	'NtDCompositionCommitChannel', # 0x124
	'NtDCompositionConfirmFrame', # 0x125
	'NtDCompositionConnectPipe', # 0x126
	'NtDCompositionCreateChannel', # 0x127
	'NtDCompositionCreateConnectionContext', # 0x128
	'NtDCompositionCreateDwmChannel', # 0x129
	'NtDCompositionCreateResource', # 0x12a
	'NtDCompositionCurrentBatchId', # 0x12b
	'NtDCompositionDestroyChannel', # 0x12c
	'NtDCompositionDestroyConnectionContext', # 0x12d
	'NtDCompositionDiscardFrame', # 0x12e
	'NtDCompositionDwmSyncFlush', # 0x12f
	'NtDCompositionGetChannels', # 0x130
	'NtDCompositionGetConnectionContextBatch', # 0x131
	'NtDCompositionGetDeletedResources', # 0x132
	'NtDCompositionGetFrameLegacyTokens', # 0x133
	'NtDCompositionGetFrameStatistics', # 0x134
	'NtDCompositionGetFrameSurfaceUpdates', # 0x135
	'NtDCompositionReleaseAllResources', # 0x136
	'NtDCompositionReleaseResource', # 0x137
	'NtDCompositionRemoveCrossDeviceVisualChild', # 0x138
	'NtDCompositionRemoveVisualChild', # 0x139
	'NtDCompositionReplaceVisualChildren', # 0x13a
	'NtDCompositionRetireFrame', # 0x13b
	'NtDCompositionSetChannelCommitCompletionEvent', # 0x13c
	'NtDCompositionSetResourceAnimationProperty', # 0x13d
	'NtDCompositionSetResourceBufferProperty', # 0x13e
	'NtDCompositionSetResourceDeletedNotificationTag', # 0x13f
	'NtDCompositionSetResourceFloatProperty', # 0x140
	'NtDCompositionSetResourceIntegerProperty', # 0x141
	'NtDCompositionSetResourceReferenceArrayProperty', # 0x142
	'NtDCompositionSetResourceReferenceProperty', # 0x143
	'NtDCompositionSignalGpuFence', # 0x144
	'NtDCompositionSubmitDWMBatch', # 0x145
	'NtDCompositionSynchronize', # 0x146
	'NtDCompositionTelemetryTouchInteractionBegin', # 0x147
	'NtDCompositionTelemetryTouchInteractionEnd', # 0x148
	'NtDCompositionTelemetryTouchInteractionUpdate', # 0x149
	'NtDCompositionValidateAndReferenceSystemVisualForHwndTarget', # 0x14a
	'NtDCompositionWaitForChannel', # 0x14b
	'NtGdiAbortDoc', # 0x14c
	'NtGdiAbortPath', # 0x14d
	'NtGdiAddEmbFontToDC', # 0x14e
	'NtGdiAddFontResourceW', # 0x14f
	'NtGdiAddRemoteFontToDC', # 0x150
	'NtGdiAddRemoteMMInstanceToDC', # 0x151
	'NtGdiAngleArc', # 0x152
	'NtGdiAnyLinkedFonts', # 0x153
	'NtGdiArcInternal', # 0x154
	'NtGdiBRUSHOBJ_DeleteRbrush', # 0x155
	'NtGdiBRUSHOBJ_hGetColorTransform', # 0x156
	'NtGdiBRUSHOBJ_pvAllocRbrush', # 0x157
	'NtGdiBRUSHOBJ_pvGetRbrush', # 0x158
	'NtGdiBRUSHOBJ_ulGetBrushColor', # 0x159
	'NtGdiBeginGdiRendering', # 0x15a
	'NtGdiCLIPOBJ_bEnum', # 0x15b
	'NtGdiCLIPOBJ_cEnumStart', # 0x15c
	'NtGdiCLIPOBJ_ppoGetPath', # 0x15d
	'NtGdiCancelDC', # 0x15e
	'NtGdiChangeGhostFont', # 0x15f
	'NtGdiCheckBitmapBits', # 0x160
	'NtGdiClearBitmapAttributes', # 0x161
	'NtGdiClearBrushAttributes', # 0x162
	'NtGdiColorCorrectPalette', # 0x163
	'NtGdiConfigureOPMProtectedOutput', # 0x164
	'NtGdiConvertMetafileRect', # 0x165
	'NtGdiCreateBitmapFromDxSurface', # 0x166
	'NtGdiCreateBitmapFromDxSurface2', # 0x167
	'NtGdiCreateColorTransform', # 0x168
	'NtGdiCreateEllipticRgn', # 0x169
	'NtGdiCreateHatchBrushInternal', # 0x16a
	'NtGdiCreateMetafileDC', # 0x16b
	'NtGdiCreateOPMProtectedOutputs', # 0x16c
	'NtGdiCreateRoundRectRgn', # 0x16d
	'NtGdiCreateServerMetaFile', # 0x16e
	'NtGdiCreateSessionMappedDIBSection', # 0x16f
	'NtGdiD3dContextCreate', # 0x170
	'NtGdiD3dContextDestroy', # 0x171
	'NtGdiD3dContextDestroyAll', # 0x172
	'NtGdiD3dValidateTextureStageState', # 0x173
	'NtGdiDDCCIGetCapabilitiesString', # 0x174
	'NtGdiDDCCIGetCapabilitiesStringLength', # 0x175
	'NtGdiDDCCIGetTimingReport', # 0x176
	'NtGdiDDCCIGetVCPFeature', # 0x177
	'NtGdiDDCCISaveCurrentSettings', # 0x178
	'NtGdiDDCCISetVCPFeature', # 0x179
	'NtGdiDdAddAttachedSurface', # 0x17a
	'NtGdiDdAlphaBlt', # 0x17b
	'NtGdiDdAttachSurface', # 0x17c
	'NtGdiDdBeginMoCompFrame', # 0x17d
	'NtGdiDdCanCreateD3DBuffer', # 0x17e
	'NtGdiDdColorControl', # 0x17f
	'NtGdiDdCreateD3DBuffer', # 0x180
	'NtGdiDdCreateDirectDrawObject', # 0x181
	'NtGdiDdCreateFullscreenSprite', # 0x182
	'NtGdiDdCreateMoComp', # 0x183
	'NtGdiDdDDIAcquireKeyedMutex', # 0x184
	'NtGdiDdDDIAcquireKeyedMutex2', # 0x185
	'NtGdiDdDDICheckExclusiveOwnership', # 0x186
	'NtGdiDdDDICheckMonitorPowerState', # 0x187
	'NtGdiDdDDICheckOcclusion', # 0x188
	'NtGdiDdDDICheckSharedResourceAccess', # 0x189
	'NtGdiDdDDICheckVidPnExclusiveOwnership', # 0x18a
	'NtGdiDdDDICloseAdapter', # 0x18b
	'NtGdiDdDDIConfigureSharedResource', # 0x18c
	'NtGdiDdDDICreateAllocation', # 0x18d
	'NtGdiDdDDICreateContext', # 0x18e
	'NtGdiDdDDICreateDCFromMemory', # 0x18f
	'NtGdiDdDDICreateDevice', # 0x190
	'NtGdiDdDDICreateKeyedMutex', # 0x191
	'NtGdiDdDDICreateKeyedMutex2', # 0x192
	'NtGdiDdDDICreateOutputDupl', # 0x193
	'NtGdiDdDDICreateOverlay', # 0x194
	'NtGdiDdDDICreateSynchronizationObject', # 0x195
	'NtGdiDdDDIDestroyAllocation', # 0x196
	'NtGdiDdDDIDestroyContext', # 0x197
	'NtGdiDdDDIDestroyDCFromMemory', # 0x198
	'NtGdiDdDDIDestroyDevice', # 0x199
	'NtGdiDdDDIDestroyKeyedMutex', # 0x19a
	'NtGdiDdDDIDestroyOutputDupl', # 0x19b
	'NtGdiDdDDIDestroyOverlay', # 0x19c
	'NtGdiDdDDIDestroySynchronizationObject', # 0x19d
	'NtGdiDdDDIEnumAdapters', # 0x19e
	'NtGdiDdDDIEscape', # 0x19f
	'NtGdiDdDDIFlipOverlay', # 0x1a0
	'NtGdiDdDDIGetContextInProcessSchedulingPriority', # 0x1a1
	'NtGdiDdDDIGetContextSchedulingPriority', # 0x1a2
	'NtGdiDdDDIGetDeviceState', # 0x1a3
	'NtGdiDdDDIGetDisplayModeList', # 0x1a4
	'NtGdiDdDDIGetMultisampleMethodList', # 0x1a5
	'NtGdiDdDDIGetOverlayState', # 0x1a6
	'NtGdiDdDDIGetPresentHistory', # 0x1a7
	'NtGdiDdDDIGetPresentQueueEvent', # 0x1a8
	'NtGdiDdDDIGetProcessSchedulingPriorityClass', # 0x1a9
	'NtGdiDdDDIGetRuntimeData', # 0x1aa
	'NtGdiDdDDIGetScanLine', # 0x1ab
	'NtGdiDdDDIGetSharedPrimaryHandle', # 0x1ac
	'NtGdiDdDDIGetSharedResourceAdapterLuid', # 0x1ad
	'NtGdiDdDDIInvalidateActiveVidPn', # 0x1ae
	'NtGdiDdDDILock', # 0x1af
	'NtGdiDdDDIOfferAllocations', # 0x1b0
	'NtGdiDdDDIOpenAdapterFromDeviceName', # 0x1b1
	'NtGdiDdDDIOpenAdapterFromHdc', # 0x1b2
	'NtGdiDdDDIOpenAdapterFromLuid', # 0x1b3
	'NtGdiDdDDIOpenKeyedMutex', # 0x1b4
	'NtGdiDdDDIOpenKeyedMutex2', # 0x1b5
	'NtGdiDdDDIOpenNtHandleFromName', # 0x1b6
	'NtGdiDdDDIOpenResource', # 0x1b7
	'NtGdiDdDDIOpenResourceFromNtHandle', # 0x1b8
	'NtGdiDdDDIOpenSyncObjectFromNtHandle', # 0x1b9
	'NtGdiDdDDIOpenSynchronizationObject', # 0x1ba
	'NtGdiDdDDIOutputDuplGetFrameInfo', # 0x1bb
	'NtGdiDdDDIOutputDuplGetMetaData', # 0x1bc
	'NtGdiDdDDIOutputDuplGetPointerShapeData', # 0x1bd
	'NtGdiDdDDIOutputDuplPresent', # 0x1be
	'NtGdiDdDDIOutputDuplReleaseFrame', # 0x1bf
	'NtGdiDdDDIPinDirectFlipResources', # 0x1c0
	'NtGdiDdDDIPollDisplayChildren', # 0x1c1
	'NtGdiDdDDIPresent', # 0x1c2
	'NtGdiDdDDIQueryAdapterInfo', # 0x1c3
	'NtGdiDdDDIQueryAllocationResidency', # 0x1c4
	'NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName', # 0x1c5
	'NtGdiDdDDIQueryResourceInfo', # 0x1c6
	'NtGdiDdDDIQueryResourceInfoFromNtHandle', # 0x1c7
	'NtGdiDdDDIQueryStatistics', # 0x1c8
	'NtGdiDdDDIReclaimAllocations', # 0x1c9
	'NtGdiDdDDIReleaseKeyedMutex', # 0x1ca
	'NtGdiDdDDIReleaseKeyedMutex2', # 0x1cb
	'NtGdiDdDDIReleaseProcessVidPnSourceOwners', # 0x1cc
	'NtGdiDdDDIRender', # 0x1cd
	'NtGdiDdDDISetAllocationPriority', # 0x1ce
	'NtGdiDdDDISetContextInProcessSchedulingPriority', # 0x1cf
	'NtGdiDdDDISetContextSchedulingPriority', # 0x1d0
	'NtGdiDdDDISetDisplayMode', # 0x1d1
	'NtGdiDdDDISetDisplayPrivateDriverFormat', # 0x1d2
	'NtGdiDdDDISetGammaRamp', # 0x1d3
	'NtGdiDdDDISetProcessSchedulingPriorityClass', # 0x1d4
	'NtGdiDdDDISetQueuedLimit', # 0x1d5
	'NtGdiDdDDISetStereoEnabled', # 0x1d6
	'NtGdiDdDDISetVidPnSourceOwner', # 0x1d7
	'NtGdiDdDDISetVidPnSourceOwner1', # 0x1d8
	'NtGdiDdDDIShareObjects', # 0x1d9
	'NtGdiDdDDISharedPrimaryLockNotification', # 0x1da
	'NtGdiDdDDISharedPrimaryUnLockNotification', # 0x1db
	'NtGdiDdDDISignalSynchronizationObject', # 0x1dc
	'NtGdiDdDDIUnlock', # 0x1dd
	'NtGdiDdDDIUnpinDirectFlipResources', # 0x1de
	'NtGdiDdDDIUpdateOverlay', # 0x1df
	'NtGdiDdDDIWaitForIdle', # 0x1e0
	'NtGdiDdDDIWaitForSynchronizationObject', # 0x1e1
	'NtGdiDdDDIWaitForVerticalBlankEvent', # 0x1e2
	'NtGdiDdDDIWaitForVerticalBlankEvent2', # 0x1e3
	'NtGdiDdDeleteDirectDrawObject', # 0x1e4
	'NtGdiDdDestroyD3DBuffer', # 0x1e5
	'NtGdiDdDestroyFullscreenSprite', # 0x1e6
	'NtGdiDdDestroyMoComp', # 0x1e7
	'NtGdiDdEndMoCompFrame', # 0x1e8
	'NtGdiDdFlip', # 0x1e9
	'NtGdiDdFlipToGDISurface', # 0x1ea
	'NtGdiDdGetAvailDriverMemory', # 0x1eb
	'NtGdiDdGetBltStatus', # 0x1ec
	'NtGdiDdGetDC', # 0x1ed
	'NtGdiDdGetDriverInfo', # 0x1ee
	'NtGdiDdGetDriverState', # 0x1ef
	'NtGdiDdGetDxHandle', # 0x1f0
	'NtGdiDdGetFlipStatus', # 0x1f1
	'NtGdiDdGetInternalMoCompInfo', # 0x1f2
	'NtGdiDdGetMoCompBuffInfo', # 0x1f3
	'NtGdiDdGetMoCompFormats', # 0x1f4
	'NtGdiDdGetMoCompGuids', # 0x1f5
	'NtGdiDdGetScanLine', # 0x1f6
	'NtGdiDdLock', # 0x1f7
	'NtGdiDdNotifyFullscreenSpriteUpdate', # 0x1f8
	'NtGdiDdQueryDirectDrawObject', # 0x1f9
	'NtGdiDdQueryMoCompStatus', # 0x1fa
	'NtGdiDdQueryVisRgnUniqueness', # 0x1fb
	'NtGdiDdReenableDirectDrawObject', # 0x1fc
	'NtGdiDdReleaseDC', # 0x1fd
	'NtGdiDdRenderMoComp', # 0x1fe
	'NtGdiDdSetColorKey', # 0x1ff
	'NtGdiDdSetExclusiveMode', # 0x200
	'NtGdiDdSetGammaRamp', # 0x201
	'NtGdiDdSetOverlayPosition', # 0x202
	'NtGdiDdUnattachSurface', # 0x203
	'NtGdiDdUnlock', # 0x204
	'NtGdiDdUpdateOverlay', # 0x205
	'NtGdiDdWaitForVerticalBlank', # 0x206
	'NtGdiDeleteColorTransform', # 0x207
	'NtGdiDescribePixelFormat', # 0x208
	'NtGdiDestroyOPMProtectedOutput', # 0x209
	'NtGdiDestroyPhysicalMonitor', # 0x20a
	'NtGdiDoBanding', # 0x20b
	'NtGdiDrawEscape', # 0x20c
	'NtGdiDvpAcquireNotification', # 0x20d
	'NtGdiDvpCanCreateVideoPort', # 0x20e
	'NtGdiDvpColorControl', # 0x20f
	'NtGdiDvpCreateVideoPort', # 0x210
	'NtGdiDvpDestroyVideoPort', # 0x211
	'NtGdiDvpFlipVideoPort', # 0x212
	'NtGdiDvpGetVideoPortBandwidth', # 0x213
	'NtGdiDvpGetVideoPortConnectInfo', # 0x214
	'NtGdiDvpGetVideoPortField', # 0x215
	'NtGdiDvpGetVideoPortFlipStatus', # 0x216
	'NtGdiDvpGetVideoPortInputFormats', # 0x217
	'NtGdiDvpGetVideoPortLine', # 0x218
	'NtGdiDvpGetVideoPortOutputFormats', # 0x219
	'NtGdiDvpGetVideoSignalStatus', # 0x21a
	'NtGdiDvpReleaseNotification', # 0x21b
	'NtGdiDvpUpdateVideoPort', # 0x21c
	'NtGdiDvpWaitForVideoPortSync', # 0x21d
	'NtGdiDwmCreatedBitmapRemotingOutput', # 0x21e
	'NtGdiDxgGenericThunk', # 0x21f
	'NtGdiEllipse', # 0x220
	'NtGdiEnableEudc', # 0x221
	'NtGdiEndDoc', # 0x222
	'NtGdiEndGdiRendering', # 0x223
	'NtGdiEndPage', # 0x224
	'NtGdiEngAlphaBlend', # 0x225
	'NtGdiEngAssociateSurface', # 0x226
	'NtGdiEngBitBlt', # 0x227
	'NtGdiEngCheckAbort', # 0x228
	'NtGdiEngComputeGlyphSet', # 0x229
	'NtGdiEngCopyBits', # 0x22a
	'NtGdiEngCreateBitmap', # 0x22b
	'NtGdiEngCreateClip', # 0x22c
	'NtGdiEngCreateDeviceBitmap', # 0x22d
	'NtGdiEngCreateDeviceSurface', # 0x22e
	'NtGdiEngCreatePalette', # 0x22f
	'NtGdiEngDeleteClip', # 0x230
	'NtGdiEngDeletePalette', # 0x231
	'NtGdiEngDeletePath', # 0x232
	'NtGdiEngDeleteSurface', # 0x233
	'NtGdiEngEraseSurface', # 0x234
	'NtGdiEngFillPath', # 0x235
	'NtGdiEngGradientFill', # 0x236
	'NtGdiEngLineTo', # 0x237
	'NtGdiEngLockSurface', # 0x238
	'NtGdiEngMarkBandingSurface', # 0x239
	'NtGdiEngPaint', # 0x23a
	'NtGdiEngPlgBlt', # 0x23b
	'NtGdiEngStretchBlt', # 0x23c
	'NtGdiEngStretchBltROP', # 0x23d
	'NtGdiEngStrokeAndFillPath', # 0x23e
	'NtGdiEngStrokePath', # 0x23f
	'NtGdiEngTextOut', # 0x240
	'NtGdiEngTransparentBlt', # 0x241
	'NtGdiEngUnlockSurface', # 0x242
	'NtGdiEnumFonts', # 0x243
	'NtGdiEnumObjects', # 0x244
	'NtGdiEudcLoadUnloadLink', # 0x245
	'NtGdiExtFloodFill', # 0x246
	'NtGdiFONTOBJ_cGetAllGlyphHandles', # 0x247
	'NtGdiFONTOBJ_cGetGlyphs', # 0x248
	'NtGdiFONTOBJ_pQueryGlyphAttrs', # 0x249
	'NtGdiFONTOBJ_pfdg', # 0x24a
	'NtGdiFONTOBJ_pifi', # 0x24b
	'NtGdiFONTOBJ_pvTrueTypeFontFile', # 0x24c
	'NtGdiFONTOBJ_pxoGetXform', # 0x24d
	'NtGdiFONTOBJ_vGetInfo', # 0x24e
	'NtGdiFlattenPath', # 0x24f
	'NtGdiFontIsLinked', # 0x250
	'NtGdiForceUFIMapping', # 0x251
	'NtGdiFrameRgn', # 0x252
	'NtGdiFullscreenControl', # 0x253
	'NtGdiGetBoundsRect', # 0x254
	'NtGdiGetCOPPCompatibleOPMInformation', # 0x255
	'NtGdiGetCertificate', # 0x256
	'NtGdiGetCertificateSize', # 0x257
	'NtGdiGetCharABCWidthsW', # 0x258
	'NtGdiGetCharacterPlacementW', # 0x259
	'NtGdiGetColorAdjustment', # 0x25a
	'NtGdiGetColorSpaceforBitmap', # 0x25b
	'NtGdiGetDeviceCaps', # 0x25c
	'NtGdiGetDeviceCapsAll', # 0x25d
	'NtGdiGetDeviceGammaRamp', # 0x25e
	'NtGdiGetDeviceWidth', # 0x25f
	'NtGdiGetDhpdev', # 0x260
	'NtGdiGetETM', # 0x261
	'NtGdiGetEmbUFI', # 0x262
	'NtGdiGetEmbedFonts', # 0x263
	'NtGdiGetEudcTimeStampEx', # 0x264
	'NtGdiGetFontFileData', # 0x265
	'NtGdiGetFontFileInfo', # 0x266
	'NtGdiGetFontResourceInfoInternalW', # 0x267
	'NtGdiGetFontUnicodeRanges', # 0x268
	'NtGdiGetGlyphIndicesW', # 0x269
	'NtGdiGetGlyphIndicesWInternal', # 0x26a
	'NtGdiGetGlyphOutline', # 0x26b
	'NtGdiGetKerningPairs', # 0x26c
	'NtGdiGetLinkedUFIs', # 0x26d
	'NtGdiGetMiterLimit', # 0x26e
	'NtGdiGetMonitorID', # 0x26f
	'NtGdiGetNumberOfPhysicalMonitors', # 0x270
	'NtGdiGetOPMInformation', # 0x271
	'NtGdiGetOPMRandomNumber', # 0x272
	'NtGdiGetObjectBitmapHandle', # 0x273
	'NtGdiGetPath', # 0x274
	'NtGdiGetPerBandInfo', # 0x275
	'NtGdiGetPhysicalMonitorDescription', # 0x276
	'NtGdiGetPhysicalMonitors', # 0x277
	'NtGdiGetRealizationInfo', # 0x278
	'NtGdiGetServerMetaFileBits', # 0x279
	'NtGdiGetSpoolMessage', # 0x27a
	'NtGdiGetStats', # 0x27b
	'NtGdiGetStringBitmapW', # 0x27c
	'NtGdiGetSuggestedOPMProtectedOutputArraySize', # 0x27d
	'NtGdiGetTextExtentExW', # 0x27e
	'NtGdiGetUFI', # 0x27f
	'NtGdiGetUFIPathname', # 0x280
	'NtGdiGradientFill', # 0x281
	'NtGdiHLSurfGetInformation', # 0x282
	'NtGdiHLSurfSetInformation', # 0x283
	'NtGdiHT_Get8BPPFormatPalette', # 0x284
	'NtGdiHT_Get8BPPMaskPalette', # 0x285
	'NtGdiIcmBrushInfo', # 0x286
	'NtGdiInit', # 0x287
	'NtGdiInitSpool', # 0x288
	'NtGdiMakeFontDir', # 0x289
	'NtGdiMakeInfoDC', # 0x28a
	'NtGdiMakeObjectUnXferable', # 0x28b
	'NtGdiMakeObjectXferable', # 0x28c
	'NtGdiMirrorWindowOrg', # 0x28d
	'NtGdiMonoBitmap', # 0x28e
	'NtGdiMoveTo', # 0x28f
	'NtGdiOffsetClipRgn', # 0x290
	'NtGdiPATHOBJ_bEnum', # 0x291
	'NtGdiPATHOBJ_bEnumClipLines', # 0x292
	'NtGdiPATHOBJ_vEnumStart', # 0x293
	'NtGdiPATHOBJ_vEnumStartClipLines', # 0x294
	'NtGdiPATHOBJ_vGetBounds', # 0x295
	'NtGdiPathToRegion', # 0x296
	'NtGdiPlgBlt', # 0x297
	'NtGdiPolyDraw', # 0x298
	'NtGdiPolyTextOutW', # 0x299
	'NtGdiPtInRegion', # 0x29a
	'NtGdiPtVisible', # 0x29b
	'NtGdiQueryFonts', # 0x29c
	'NtGdiRemoveFontResourceW', # 0x29d
	'NtGdiRemoveMergeFont', # 0x29e
	'NtGdiResetDC', # 0x29f
	'NtGdiResizePalette', # 0x2a0
	'NtGdiRoundRect', # 0x2a1
	'NtGdiSTROBJ_bEnum', # 0x2a2
	'NtGdiSTROBJ_bEnumPositionsOnly', # 0x2a3
	'NtGdiSTROBJ_bGetAdvanceWidths', # 0x2a4
	'NtGdiSTROBJ_dwGetCodePage', # 0x2a5
	'NtGdiSTROBJ_vEnumStart', # 0x2a6
	'NtGdiScaleViewportExtEx', # 0x2a7
	'NtGdiScaleWindowExtEx', # 0x2a8
	'NtGdiSelectBrush', # 0x2a9
	'NtGdiSelectClipPath', # 0x2aa
	'NtGdiSelectPen', # 0x2ab
	'NtGdiSetBitmapAttributes', # 0x2ac
	'NtGdiSetBrushAttributes', # 0x2ad
	'NtGdiSetColorAdjustment', # 0x2ae
	'NtGdiSetColorSpace', # 0x2af
	'NtGdiSetDeviceGammaRamp', # 0x2b0
	'NtGdiSetFontXform', # 0x2b1
	'NtGdiSetIcmMode', # 0x2b2
	'NtGdiSetLinkedUFIs', # 0x2b3
	'NtGdiSetMagicColors', # 0x2b4
	'NtGdiSetOPMSigningKeyAndSequenceNumbers', # 0x2b5
	'NtGdiSetPUMPDOBJ', # 0x2b6
	'NtGdiSetPixelFormat', # 0x2b7
	'NtGdiSetRectRgn', # 0x2b8
	'NtGdiSetSizeDevice', # 0x2b9
	'NtGdiSetSystemPaletteUse', # 0x2ba
	'NtGdiSetTextJustification', # 0x2bb
	'NtGdiSetUMPDSandboxState', # 0x2bc
	'NtGdiStartDoc', # 0x2bd
	'NtGdiStartPage', # 0x2be
	'NtGdiStrokeAndFillPath', # 0x2bf
	'NtGdiStrokePath', # 0x2c0
	'NtGdiSwapBuffers', # 0x2c1
	'NtGdiTransparentBlt', # 0x2c2
	'NtGdiUMPDEngFreeUserMem', # 0x2c3
	'NtGdiUnloadPrinterDriver', # 0x2c4
	'NtGdiUnmapMemFont', # 0x2c5
	'NtGdiUpdateColors', # 0x2c6
	'NtGdiUpdateTransform', # 0x2c7
	'NtGdiWidenPath', # 0x2c8
	'NtGdiXFORMOBJ_bApplyXform', # 0x2c9
	'NtGdiXFORMOBJ_iGetXform', # 0x2ca
	'NtGdiXLATEOBJ_cGetPalette', # 0x2cb
	'NtGdiXLATEOBJ_hGetColorTransform', # 0x2cc
	'NtGdiXLATEOBJ_iXlate', # 0x2cd
	'NtNotifyPresentToCompositionSurface', # 0x2ce
	'NtOpenCompositionSurfaceDirtyRegion', # 0x2cf
	'NtOpenCompositionSurfaceSectionInfo', # 0x2d0
	'NtOpenCompositionSurfaceSwapChainHandleInfo', # 0x2d1
	'NtQueryCompositionSurfaceBinding', # 0x2d2
	'NtQueryCompositionSurfaceRenderingRealization', # 0x2d3
	'NtQueryCompositionSurfaceStatistics', # 0x2d4
	'NtSetCompositionSurfaceOutOfFrameDirectFlipNotification', # 0x2d5
	'NtSetCompositionSurfaceStatistics', # 0x2d6
	'NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates', # 0x2d7
	'NtTokenManagerOpenEvent', # 0x2d8
	'NtTokenManagerThread', # 0x2d9
	'NtUnBindCompositionSurface', # 0x2da
	'NtUserAcquireIAMKey', # 0x2db
	'NtUserAddClipboardFormatListener', # 0x2dc
	'NtUserAssociateInputContext', # 0x2dd
	'NtUserAutoPromoteMouseInPointer', # 0x2de
	'NtUserAutoRotateScreen', # 0x2df
	'NtUserBlockInput', # 0x2e0
	'NtUserBuildHimcList', # 0x2e1
	'NtUserBuildPropList', # 0x2e2
	'NtUserCalculatePopupWindowPosition', # 0x2e3
	'NtUserCallHwndOpt', # 0x2e4
	'NtUserCanBrokerForceForeground', # 0x2e5
	'NtUserChangeDisplaySettings', # 0x2e6
	'NtUserChangeWindowMessageFilterEx', # 0x2e7
	'NtUserCheckAccessForIntegrityLevel', # 0x2e8
	'NtUserCheckProcessForClipboardAccess', # 0x2e9
	'NtUserCheckProcessSession', # 0x2ea
	'NtUserCheckWindowThreadDesktop', # 0x2eb
	'NtUserChildWindowFromPointEx', # 0x2ec
	'NtUserClipCursor', # 0x2ed
	'NtUserCreateDCompositionHwndTarget', # 0x2ee
	'NtUserCreateDesktopEx', # 0x2ef
	'NtUserCreateInputContext', # 0x2f0
	'NtUserCreateWindowStation', # 0x2f1
	'NtUserCtxDisplayIOCtl', # 0x2f2
	'NtUserDeferWindowPosAndBand', # 0x2f3
	'NtUserDelegateCapturePointers', # 0x2f4
	'NtUserDelegateInput', # 0x2f5
	'NtUserDestroyDCompositionHwndTarget', # 0x2f6
	'NtUserDestroyInputContext', # 0x2f7
	'NtUserDisableImmersiveOwner', # 0x2f8
	'NtUserDisableProcessWindowFiltering', # 0x2f9
	'NtUserDisableThreadIme', # 0x2fa
	'NtUserDiscardPointerFrameMessages', # 0x2fb
	'NtUserDisplayConfigGetDeviceInfo', # 0x2fc
	'NtUserDisplayConfigSetDeviceInfo', # 0x2fd
	'NtUserDoSoundConnect', # 0x2fe
	'NtUserDoSoundDisconnect', # 0x2ff
	'NtUserDragDetect', # 0x300
	'NtUserDragObject', # 0x301
	'NtUserDrawAnimatedRects', # 0x302
	'NtUserDrawCaption', # 0x303
	'NtUserDrawCaptionTemp', # 0x304
	'NtUserDrawMenuBarTemp', # 0x305
	'NtUserDwmGetRemoteSessionOcclusionEvent', # 0x306
	'NtUserDwmGetRemoteSessionOcclusionState', # 0x307
	'NtUserDwmStartRedirection', # 0x308
	'NtUserDwmStopRedirection', # 0x309
	'NtUserDwmValidateWindow', # 0x30a
	'NtUserEnableIAMAccess', # 0x30b
	'NtUserEnableMouseInPointer', # 0x30c
	'NtUserEnableMouseInputForCursorSuppression', # 0x30d
	'NtUserEndMenu', # 0x30e
	'NtUserEvent', # 0x30f
	'NtUserFlashWindowEx', # 0x310
	'NtUserFrostCrashedWindow', # 0x311
	'NtUserGetAppImeLevel', # 0x312
	'NtUserGetAutoRotationState', # 0x313
	'NtUserGetCIMSSM', # 0x314
	'NtUserGetCaretPos', # 0x315
	'NtUserGetClipCursor', # 0x316
	'NtUserGetClipboardAccessToken', # 0x317
	'NtUserGetClipboardViewer', # 0x318
	'NtUserGetComboBoxInfo', # 0x319
	'NtUserGetCurrentInputMessageSource', # 0x31a
	'NtUserGetCursorInfo', # 0x31b
	'NtUserGetDesktopID', # 0x31c
	'NtUserGetDisplayAutoRotationPreferences', # 0x31d
	'NtUserGetDisplayAutoRotationPreferencesByProcessId', # 0x31e
	'NtUserGetDisplayConfigBufferSizes', # 0x31f
	'NtUserGetGestureConfig', # 0x320
	'NtUserGetGestureExtArgs', # 0x321
	'NtUserGetGestureInfo', # 0x322
	'NtUserGetGlobalIMEStatus', # 0x323
	'NtUserGetGuiResources', # 0x324
	'NtUserGetImeHotKey', # 0x325
	'NtUserGetImeInfoEx', # 0x326
	'NtUserGetInputLocaleInfo', # 0x327
	'NtUserGetInternalWindowPos', # 0x328
	'NtUserGetKeyNameText', # 0x329
	'NtUserGetKeyboardLayoutName', # 0x32a
	'NtUserGetLayeredWindowAttributes', # 0x32b
	'NtUserGetListBoxInfo', # 0x32c
	'NtUserGetMenuIndex', # 0x32d
	'NtUserGetMenuItemRect', # 0x32e
	'NtUserGetMouseMovePointsEx', # 0x32f
	'NtUserGetPointerCursorId', # 0x330
	'NtUserGetPointerDevice', # 0x331
	'NtUserGetPointerDeviceCursors', # 0x332
	'NtUserGetPointerDeviceProperties', # 0x333
	'NtUserGetPointerDeviceRects', # 0x334
	'NtUserGetPointerDevices', # 0x335
	'NtUserGetPointerInfoList', # 0x336
	'NtUserGetPointerType', # 0x337
	'NtUserGetPriorityClipboardFormat', # 0x338
	'NtUserGetProcessUIContextInformation', # 0x339
	'NtUserGetQueueEventStatus', # 0x33a
	'NtUserGetRawInputBuffer', # 0x33b
	'NtUserGetRawInputData', # 0x33c
	'NtUserGetRawInputDeviceInfo', # 0x33d
	'NtUserGetRawInputDeviceList', # 0x33e
	'NtUserGetRawPointerDeviceData', # 0x33f
	'NtUserGetRegisteredRawInputDevices', # 0x340
	'NtUserGetTopLevelWindow', # 0x341
	'NtUserGetTouchInputInfo', # 0x342
	'NtUserGetTouchValidationStatus', # 0x343
	'NtUserGetUpdatedClipboardFormats', # 0x344
	'NtUserGetWOWClass', # 0x345
	'NtUserGetWindowBand', # 0x346
	'NtUserGetWindowCompositionAttribute', # 0x347
	'NtUserGetWindowCompositionInfo', # 0x348
	'NtUserGetWindowDisplayAffinity', # 0x349
	'NtUserGetWindowFeedbackSetting', # 0x34a
	'NtUserGetWindowMinimizeRect', # 0x34b
	'NtUserGetWindowRgnEx', # 0x34c
	'NtUserGhostWindowFromHungWindow', # 0x34d
	'NtUserHandleDelegatedInput', # 0x34e
	'NtUserHardErrorControl', # 0x34f
	'NtUserHidePointerContactVisualization', # 0x350
	'NtUserHiliteMenuItem', # 0x351
	'NtUserHungWindowFromGhostWindow', # 0x352
	'NtUserHwndQueryRedirectionInfo', # 0x353
	'NtUserHwndSetRedirectionInfo', # 0x354
	'NtUserImpersonateDdeClientWindow', # 0x355
	'NtUserInitTask', # 0x356
	'NtUserInitialize', # 0x357
	'NtUserInitializeClientPfnArrays', # 0x358
	'NtUserInitializeTouchInjection', # 0x359
	'NtUserInjectGesture', # 0x35a
	'NtUserInjectTouchInput', # 0x35b
	'NtUserInternalClipCursor', # 0x35c
	'NtUserInternalGetWindowIcon', # 0x35d
	'NtUserIsMouseInPointerEnabled', # 0x35e
	'NtUserIsMouseInputEnabled', # 0x35f
	'NtUserIsTopLevelWindow', # 0x360
	'NtUserIsTouchWindow', # 0x361
	'NtUserLayoutCompleted', # 0x362
	'NtUserLoadKeyboardLayoutEx', # 0x363
	'NtUserLockWindowStation', # 0x364
	'NtUserLockWorkStation', # 0x365
	'NtUserLogicalToPhysicalPoint', # 0x366
	'NtUserMNDragLeave', # 0x367
	'NtUserMNDragOver', # 0x368
	'NtUserMagControl', # 0x369
	'NtUserMagGetContextInformation', # 0x36a
	'NtUserMagSetContextInformation', # 0x36b
	'NtUserMenuItemFromPoint', # 0x36c
	'NtUserMinMaximize', # 0x36d
	'NtUserModifyWindowTouchCapability', # 0x36e
	'NtUserNotifyIMEStatus', # 0x36f
	'NtUserOpenInputDesktop', # 0x370
	'NtUserOpenThreadDesktop', # 0x371
	'NtUserPaintMonitor', # 0x372
	'NtUserPhysicalToLogicalPoint', # 0x373
	'NtUserPrintWindow', # 0x374
	'NtUserPromoteMouseInPointer', # 0x375
	'NtUserPromotePointer', # 0x376
	'NtUserQueryBSDRWindow', # 0x377
	'NtUserQueryDisplayConfig', # 0x378
	'NtUserQueryInformationThread', # 0x379
	'NtUserQueryInputContext', # 0x37a
	'NtUserQuerySendMessage', # 0x37b
	'NtUserRealChildWindowFromPoint', # 0x37c
	'NtUserRealWaitMessageEx', # 0x37d
	'NtUserRegisterBSDRWindow', # 0x37e
	'NtUserRegisterEdgy', # 0x37f
	'NtUserRegisterErrorReportingDialog', # 0x380
	'NtUserRegisterHotKey', # 0x381
	'NtUserRegisterPointerDeviceNotifications', # 0x382
	'NtUserRegisterPointerInputTarget', # 0x383
	'NtUserRegisterRawInputDevices', # 0x384
	'NtUserRegisterServicesProcess', # 0x385
	'NtUserRegisterSessionPort', # 0x386
	'NtUserRegisterTasklist', # 0x387
	'NtUserRegisterTouchHitTestingWindow', # 0x388
	'NtUserRegisterUserApiHook', # 0x389
	'NtUserRemoteConnect', # 0x38a
	'NtUserRemoteRedrawRectangle', # 0x38b
	'NtUserRemoteRedrawScreen', # 0x38c
	'NtUserRemoteStopScreenUpdates', # 0x38d
	'NtUserRemoveClipboardFormatListener', # 0x38e
	'NtUserResolveDesktopForWOW', # 0x38f
	'NtUserSendEventMessage', # 0x390
	'NtUserSetActiveProcess', # 0x391
	'NtUserSetAppImeLevel', # 0x392
	'NtUserSetAutoRotation', # 0x393
	'NtUserSetBrokeredForeground', # 0x394
	'NtUserSetCalibrationData', # 0x395
	'NtUserSetChildWindowNoActivate', # 0x396
	'NtUserSetClassWord', # 0x397
	'NtUserSetCursorContents', # 0x398
	'NtUserSetDisplayAutoRotationPreferences', # 0x399
	'NtUserSetDisplayConfig', # 0x39a
	'NtUserSetDisplayMapping', # 0x39b
	'NtUserSetFallbackForeground', # 0x39c
	'NtUserSetGestureConfig', # 0x39d
	'NtUserSetImeHotKey', # 0x39e
	'NtUserSetImeInfoEx', # 0x39f
	'NtUserSetImeOwnerWindow', # 0x3a0
	'NtUserSetImmersiveBackgroundWindow', # 0x3a1
	'NtUserSetInternalWindowPos', # 0x3a2
	'NtUserSetLayeredWindowAttributes', # 0x3a3
	'NtUserSetMenu', # 0x3a4
	'NtUserSetMenuContextHelpId', # 0x3a5
	'NtUserSetMenuFlagRtoL', # 0x3a6
	'NtUserSetMirrorRendering', # 0x3a7
	'NtUserSetObjectInformation', # 0x3a8
	'NtUserSetProcessDPIAware', # 0x3a9
	'NtUserSetProcessRestrictionExemption', # 0x3aa
	'NtUserSetProcessUIAccessZorder', # 0x3ab
	'NtUserSetSensorPresence', # 0x3ac
	'NtUserSetShellWindowEx', # 0x3ad
	'NtUserSetSysColors', # 0x3ae
	'NtUserSetSystemCursor', # 0x3af
	'NtUserSetSystemTimer', # 0x3b0
	'NtUserSetThreadInputBlocked', # 0x3b1
	'NtUserSetThreadLayoutHandles', # 0x3b2
	'NtUserSetWindowBand', # 0x3b3
	'NtUserSetWindowCompositionAttribute', # 0x3b4
	'NtUserSetWindowCompositionTransition', # 0x3b5
	'NtUserSetWindowDisplayAffinity', # 0x3b6
	'NtUserSetWindowFeedbackSetting', # 0x3b7
	'NtUserSetWindowRgnEx', # 0x3b8
	'NtUserSetWindowStationUser', # 0x3b9
	'NtUserShowSystemCursor', # 0x3ba
	'NtUserShutdownBlockReasonCreate', # 0x3bb
	'NtUserShutdownBlockReasonQuery', # 0x3bc
	'NtUserShutdownReasonDestroy', # 0x3bd
	'NtUserSignalRedirectionStartComplete', # 0x3be
	'NtUserSlicerControl', # 0x3bf
	'NtUserSoundSentry', # 0x3c0
	'NtUserSwitchDesktop', # 0x3c1
	'NtUserTestForInteractiveUser', # 0x3c2
	'NtUserTrackPopupMenuEx', # 0x3c3
	'NtUserUndelegateInput', # 0x3c4
	'NtUserUnloadKeyboardLayout', # 0x3c5
	'NtUserUnlockWindowStation', # 0x3c6
	'NtUserUnregisterHotKey', # 0x3c7
	'NtUserUnregisterSessionPort', # 0x3c8
	'NtUserUnregisterUserApiHook', # 0x3c9
	'NtUserUpdateDefaultDesktopThumbnail', # 0x3ca
	'NtUserUpdateInputContext', # 0x3cb
	'NtUserUpdateInstance', # 0x3cc
	'NtUserUpdateLayeredWindow', # 0x3cd
	'NtUserUpdatePerUserSystemParameters', # 0x3ce
	'NtUserUpdateWindowTransform', # 0x3cf
	'NtUserUserHandleGrantAccess', # 0x3d0
	'NtUserValidateHandleSecure', # 0x3d1
	'NtUserWaitAvailableMessageEx', # 0x3d2
	'NtUserWaitForInputIdle', # 0x3d3
	'NtUserWaitForMsgAndEvent', # 0x3d4
	'NtUserWaitForRedirectionStartComplete', # 0x3d5
	'NtUserWindowFromPhysicalPoint', # 0x3d6
	'NtValidateCompositionSurfaceHandle', # 0x3d7
	'NtUserSetClassLongPtr', # 0x3d8
	'NtUserSetWindowLongPtr', # 0x3d9
	],
]
