syscalls = [
    [
    'NtWorkerFactoryWorkerReady', # 0x0
    'NtYieldExecution', # 0x1
    'NtWriteVirtualMemory', # 0x2
    'NtWriteRequestData', # 0x3
    'NtWriteFileGather', # 0x4
    'NtWriteFile', # 0x5
    'NtWaitLowEventPair', # 0x6
    'NtWaitHighEventPair', # 0x7
    'NtWaitForWorkViaWorkerFactory', # 0x8
    'NtWaitForWnfNotifications', # 0x9
    'NtWaitForSingleObject', # 0xa
    'NtWaitForMultipleObjects32', # 0xb
    'NtWaitForMultipleObjects', # 0xc
    'NtWaitForKeyedEvent', # 0xd
    'NtWaitForDebugEvent', # 0xe
    'NtWaitForAlertByThreadId', # 0xf
    'NtVdmControl', # 0x10
    'NtUnsubscribeWnfStateChange', # 0x11
    'NtUpdateWnfStateData', # 0x12
    'NtUnmapViewOfSection', # 0x13
    'NtUnmapViewOfSectionEx', # 0x14
    'NtUnlockVirtualMemory', # 0x15
    'NtUnlockFile', # 0x16
    'NtUnloadKeyEx', # 0x17
    'NtUnloadKey2', # 0x18
    'NtUnloadKey', # 0x19
    'NtUnloadDriver', # 0x1a
    'NtUmsThreadYield', # 0x1b
    'NtTranslateFilePath', # 0x1c
    'NtTraceEvent', # 0x1d
    'NtTraceControl', # 0x1e
    'NtThawTransactions', # 0x1f
    'NtThawRegistry', # 0x20
    'NtTestAlert', # 0x21
    'NtTerminateThread', # 0x22
    'NtTerminateProcess', # 0x23
    'NtTerminateJobObject', # 0x24
    'NtSystemDebugControl', # 0x25
    'NtSuspendThread', # 0x26
    'NtSuspendProcess', # 0x27
    'NtSubscribeWnfStateChange', # 0x28
    'NtStopProfile', # 0x29
    'NtStartProfile', # 0x2a
    'NtSinglePhaseReject', # 0x2b
    'NtSignalAndWaitForSingleObject', # 0x2c
    'NtShutdownWorkerFactory', # 0x2d
    'NtShutdownSystem', # 0x2e
    'NtSetVolumeInformationFile', # 0x2f
    'NtSetValueKey', # 0x30
    'NtSetUuidSeed', # 0x31
    'NtSetTimerResolution', # 0x32
    'NtSetTimerEx', # 0x33
    'NtSetTimer', # 0x34
    'NtSetThreadExecutionState', # 0x35
    'NtSetSystemTime', # 0x36
    'NtSetSystemPowerState', # 0x37
    'NtSetSystemInformation', # 0x38
    'NtSetSystemEnvironmentValueEx', # 0x39
    'NtSetSystemEnvironmentValue', # 0x3a
    'NtSetSecurityObject', # 0x3b
    'NtSetQuotaInformationFile', # 0x3c
    'NtSetLowWaitHighEventPair', # 0x3d
    'NtSetLowEventPair', # 0x3e
    'NtSetLdtEntries', # 0x3f
    'NtSetIRTimer', # 0x40
    'NtSetIoCompletionEx', # 0x41
    'NtSetIoCompletion', # 0x42
    'NtSetIntervalProfile', # 0x43
    'NtSetInformationWorkerFactory', # 0x44
    'NtSetInformationTransactionManager', # 0x45
    'NtSetInformationTransaction', # 0x46
    'NtSetInformationToken', # 0x47
    'NtSetInformationThread', # 0x48
    'NtSetInformationResourceManager', # 0x49
    'NtSetInformationProcess', # 0x4a
    'NtSetInformationObject', # 0x4b
    'NtSetInformationKey', # 0x4c
    'NtSetInformationJobObject', # 0x4d
    'NtSetInformationFile', # 0x4e
    'NtSetInformationEnlistment', # 0x4f
    'NtSetInformationDebugObject', # 0x50
    'NtSetHighWaitLowEventPair', # 0x51
    'NtSetHighEventPair', # 0x52
    'NtSetEventBoostPriority', # 0x53
    'NtSetEvent', # 0x54
    'NtSetEaFile', # 0x55
    'NtSetDriverEntryOrder', # 0x56
    'NtSetDefaultUILanguage', # 0x57
    'NtSetDefaultLocale', # 0x58
    'NtSetDefaultHardErrorPort', # 0x59
    'NtSetDebugFilterState', # 0x5a
    'NtSetContextThread', # 0x5b
    'NtSetCachedSigningLevel', # 0x5c
    'NtSetBootOptions', # 0x5d
    'NtSetBootEntryOrder', # 0x5e
    'NtSerializeBoot', # 0x5f
    'NtSecureConnectPort', # 0x60
    'NtSaveMergedKeys', # 0x61
    'NtSaveKeyEx', # 0x62
    'NtSaveKey', # 0x63
    'NtRollforwardTransactionManager', # 0x64
    'NtRollbackTransaction', # 0x65
    'NtRollbackEnlistment', # 0x66
    'NtRollbackComplete', # 0x67
    'NtResumeThread', # 0x68
    'NtResumeProcess', # 0x69
    'NtRestoreKey', # 0x6a
    'NtResetWriteWatch', # 0x6b
    'NtResetEvent', # 0x6c
    'NtRequestWaitReplyPort', # 0x6d
    'NtRequestPort', # 0x6e
    'NtReplyWaitReplyPort', # 0x6f
    'NtReplyWaitReceivePortEx', # 0x70
    'NtReplyWaitReceivePort', # 0x71
    'NtReplyPort', # 0x72
    'NtReplacePartitionUnit', # 0x73
    'NtReplaceKey', # 0x74
    'NtRenameTransactionManager', # 0x75
    'NtRenameKey', # 0x76
    'NtRemoveProcessDebug', # 0x77
    'NtRemoveIoCompletionEx', # 0x78
    'NtRemoveIoCompletion', # 0x79
    'NtReleaseWorkerFactoryWorker', # 0x7a
    'NtReleaseSemaphore', # 0x7b
    'NtReleaseMutant', # 0x7c
    'NtReleaseKeyedEvent', # 0x7d
    'NtRegisterThreadTerminatePort', # 0x7e
    'NtRegisterProtocolAddressInformation', # 0x7f
    'NtRecoverTransactionManager', # 0x80
    'NtRecoverResourceManager', # 0x81
    'NtRecoverEnlistment', # 0x82
    'NtReadVirtualMemory', # 0x83
    'NtReadRequestData', # 0x84
    'NtReadOnlyEnlistment', # 0x85
    'NtReadFileScatter', # 0x86
    'NtReadFile', # 0x87
    'NtRaiseHardError', # 0x88
    'NtRaiseException', # 0x89
    'NtQueueApcThreadEx', # 0x8a
    'NtQueueApcThread', # 0x8b
    'NtQueryWnfStateData', # 0x8c
    'NtQueryWnfStateNameInformation', # 0x8d
    'NtQueryVolumeInformationFile', # 0x8e
    'NtQueryVirtualMemory', # 0x8f
    'NtQueryValueKey', # 0x90
    'NtQueryTimerResolution', # 0x91
    'NtQueryTimer', # 0x92
    'NtQuerySystemTime', # 0x93
    'NtQuerySystemInformationEx', # 0x94
    'NtQuerySystemInformation', # 0x95
    'NtQuerySystemEnvironmentValueEx', # 0x96
    'NtQuerySystemEnvironmentValue', # 0x97
    'NtQuerySymbolicLinkObject', # 0x98
    'NtQuerySemaphore', # 0x99
    'NtQuerySecurityObject', # 0x9a
    'NtQuerySecurityAttributesToken', # 0x9b
    'NtQuerySection', # 0x9c
    'NtQueryQuotaInformationFile', # 0x9d
    'NtQueryPortInformationProcess', # 0x9e
    'NtQueryPerformanceCounter', # 0x9f
    'NtQueryOpenSubKeysEx', # 0xa0
    'NtQueryOpenSubKeys', # 0xa1
    'NtQueryObject', # 0xa2
    'NtQueryMutant', # 0xa3
    'NtQueryMultipleValueKey', # 0xa4
    'NtQueryLicenseValue', # 0xa5
    'NtQueryKey', # 0xa6
    'NtQueryIoCompletion', # 0xa7
    'NtQueryIntervalProfile', # 0xa8
    'NtQueryInstallUILanguage', # 0xa9
    'NtQueryInformationWorkerFactory', # 0xaa
    'NtQueryInformationTransactionManager', # 0xab
    'NtQueryInformationTransaction', # 0xac
    'NtQueryInformationToken', # 0xad
    'NtQueryInformationThread', # 0xae
    'NtQueryInformationResourceManager', # 0xaf
    'NtQueryInformationProcess', # 0xb0
    'NtQueryInformationPort', # 0xb1
    'NtQueryInformationJobObject', # 0xb2
    'NtQueryInformationFile', # 0xb3
    'NtQueryInformationEnlistment', # 0xb4
    'NtQueryInformationAtom', # 0xb5
    'NtQueryFullAttributesFile', # 0xb6
    'NtQueryEvent', # 0xb7
    'NtQueryEaFile', # 0xb8
    'NtQueryDriverEntryOrder', # 0xb9
    'NtQueryDirectoryObject', # 0xba
    'NtQueryDirectoryFile', # 0xbb
    'NtQueryDefaultUILanguage', # 0xbc
    'NtQueryDefaultLocale', # 0xbd
    'NtQueryDebugFilterState', # 0xbe
    'NtQueryBootOptions', # 0xbf
    'NtQueryBootEntryOrder', # 0xc0
    'NtQueryAttributesFile', # 0xc1
    'NtPulseEvent', # 0xc2
    'NtProtectVirtualMemory', # 0xc3
    'NtPropagationFailed', # 0xc4
    'NtPropagationComplete', # 0xc5
    'NtPrivilegeObjectAuditAlarm', # 0xc6
    'NtPrivilegedServiceAuditAlarm', # 0xc7
    'NtPrivilegeCheck', # 0xc8
    'NtSetInformationVirtualMemory', # 0xc9
    'NtPrePrepareEnlistment', # 0xca
    'NtPrePrepareComplete', # 0xcb
    'NtPrepareEnlistment', # 0xcc
    'NtPrepareComplete', # 0xcd
    'NtPowerInformation', # 0xce
    'NtPlugPlayControl', # 0xcf
    'NtOpenTransactionManager', # 0xd0
    'NtOpenTransaction', # 0xd1
    'NtOpenTimer', # 0xd2
    'NtOpenThreadTokenEx', # 0xd3
    'NtOpenThreadToken', # 0xd4
    'NtOpenThread', # 0xd5
    'NtOpenSymbolicLinkObject', # 0xd6
    'NtOpenSession', # 0xd7
    'NtOpenSemaphore', # 0xd8
    'NtOpenSection', # 0xd9
    'NtOpenResourceManager', # 0xda
    'NtOpenProcessTokenEx', # 0xdb
    'NtOpenProcessToken', # 0xdc
    'NtOpenProcess', # 0xdd
    'NtOpenPrivateNamespace', # 0xde
    'NtOpenObjectAuditAlarm', # 0xdf
    'NtOpenMutant', # 0xe0
    'NtOpenKeyTransactedEx', # 0xe1
    'NtOpenKeyTransacted', # 0xe2
    'NtOpenKeyEx', # 0xe3
    'NtOpenKeyedEvent', # 0xe4
    'NtOpenKey', # 0xe5
    'NtOpenJobObject', # 0xe6
    'NtOpenIoCompletion', # 0xe7
    'NtOpenFile', # 0xe8
    'NtOpenEventPair', # 0xe9
    'NtOpenEvent', # 0xea
    'NtOpenEnlistment', # 0xeb
    'NtOpenDirectoryObject', # 0xec
    'NtNotifyChangeSession', # 0xed
    'NtNotifyChangeMultipleKeys', # 0xee
    'NtNotifyChangeKey', # 0xef
    'NtNotifyChangeDirectoryFile', # 0xf0
    'NtModifyDriverEntry', # 0xf1
    'NtModifyBootEntry', # 0xf2
    'NtMapViewOfSection', # 0xf3
    'NtMapUserPhysicalPagesScatter', # 0xf4
    'NtMapUserPhysicalPages', # 0xf5
    'NtMapCMFModule', # 0xf6
    'NtMakeTemporaryObject', # 0xf7
    'NtMakePermanentObject', # 0xf8
    'NtLockVirtualMemory', # 0xf9
    'NtLockRegistryKey', # 0xfa
    'NtLockProductActivationKeys', # 0xfb
    'NtLockFile', # 0xfc
    'NtLoadKeyEx', # 0xfd
    'NtLoadKey2', # 0xfe
    'NtLoadKey', # 0xff
    'NtLoadDriver', # 0x100
    'NtListenPort', # 0x101
    'NtIsUILanguageComitted', # 0x102
    'NtIsSystemResumeAutomatic', # 0x103
    'NtIsProcessInJob', # 0x104
    'NtInitiatePowerAction', # 0x105
    'NtInitializeRegistry', # 0x106
    'NtInitializeNlsFiles', # 0x107
    'NtImpersonateThread', # 0x108
    'NtImpersonateClientOfPort', # 0x109
    'NtImpersonateAnonymousToken', # 0x10a
    'NtGetWriteWatch', # 0x10b
    'NtGetNotificationResourceManager', # 0x10c
    'NtGetNlsSectionPtr', # 0x10d
    'NtGetNextThread', # 0x10e
    'NtGetNextProcess', # 0x10f
    'NtGetMUIRegistryInfo', # 0x110
    'NtGetDevicePowerState', # 0x111
    'NtGetCurrentProcessorNumber', # 0x112
    'NtGetContextThread', # 0x113
    'NtGetCachedSigningLevel', # 0x114
    'NtFsControlFile', # 0x115
    'NtFreezeTransactions', # 0x116
    'NtFreezeRegistry', # 0x117
    'NtFreeVirtualMemory', # 0x118
    'NtFreeUserPhysicalPages', # 0x119
    'NtFlushWriteBuffer', # 0x11a
    'NtFlushVirtualMemory', # 0x11b
    'NtFlushProcessWriteBuffers', # 0x11c
    'NtFlushKey', # 0x11d
    'NtFlushInstructionCache', # 0x11e
    'NtFlushInstallUILanguage', # 0x11f
    'NtFlushBuffersFile', # 0x120
    'NtFlushBuffersFileEx', # 0x121
    'NtFindAtom', # 0x122
    'NtFilterToken', # 0x123
    'NtFilterTokenEx', # 0x124
    'NtFilterBootOption', # 0x125
    'NtExtendSection', # 0x126
    'NtEnumerateValueKey', # 0x127
    'NtEnumerateTransactionObject', # 0x128
    'NtEnumerateSystemEnvironmentValuesEx', # 0x129
    'NtEnumerateKey', # 0x12a
    'NtEnumerateDriverEntries', # 0x12b
    'NtEnumerateBootEntries', # 0x12c
    'NtEnableLastKnownGood', # 0x12d
    'NtDuplicateToken', # 0x12e
    'NtDuplicateObject', # 0x12f
    'NtDrawText', # 0x130
    'NtDisplayString', # 0x131
    'NtDisableLastKnownGood', # 0x132
    'NtDeviceIoControlFile', # 0x133
    'NtDeleteWnfStateName', # 0x134
    'NtDeleteWnfStateData', # 0x135
    'NtDeleteValueKey', # 0x136
    'NtDeletePrivateNamespace', # 0x137
    'NtDeleteObjectAuditAlarm', # 0x138
    'NtDeleteKey', # 0x139
    'NtDeleteFile', # 0x13a
    'NtDeleteDriverEntry', # 0x13b
    'NtDeleteBootEntry', # 0x13c
    'NtDeleteAtom', # 0x13d
    'NtDelayExecution', # 0x13e
    'NtDebugContinue', # 0x13f
    'NtDebugActiveProcess', # 0x140
    'NtCreateWorkerFactory', # 0x141
    'NtCreateWnfStateName', # 0x142
    'NtCreateWaitCompletionPacket', # 0x143
    'NtCreateWaitablePort', # 0x144
    'NtCreateUserProcess', # 0x145
    'NtCreateTransactionManager', # 0x146
    'NtCreateTransaction', # 0x147
    'NtCreateToken', # 0x148
    'NtCreateLowBoxToken', # 0x149
    'NtCreateTokenEx', # 0x14a
    'NtCreateTimer', # 0x14b
    'NtCreateThreadEx', # 0x14c
    'NtCreateThread', # 0x14d
    'NtCreateSymbolicLinkObject', # 0x14e
    'NtCreateSemaphore', # 0x14f
    'NtCreateSection', # 0x150
    'NtCreateResourceManager', # 0x151
    'NtCreateProfileEx', # 0x152
    'NtCreateProfile', # 0x153
    'NtCreateProcessEx', # 0x154
    'NtCreateProcess', # 0x155
    'NtCreatePrivateNamespace', # 0x156
    'NtCreatePort', # 0x157
    'NtCreatePagingFile', # 0x158
    'NtCreateNamedPipeFile', # 0x159
    'NtCreateMutant', # 0x15a
    'NtCreateMailslotFile', # 0x15b
    'NtCreateKeyTransacted', # 0x15c
    'NtCreateKeyedEvent', # 0x15d
    'NtCreateKey', # 0x15e
    'NtCreateJobSet', # 0x15f
    'NtCreateJobObject', # 0x160
    'NtCreateIRTimer', # 0x161
    'NtCreateIoCompletion', # 0x162
    'NtCreateFile', # 0x163
    'NtCreateEventPair', # 0x164
    'NtCreateEvent', # 0x165
    'NtCreateEnlistment', # 0x166
    'NtCreateDirectoryObjectEx', # 0x167
    'NtCreateDirectoryObject', # 0x168
    'NtCreateDebugObject', # 0x169
    'NtContinue', # 0x16a
    'NtConnectPort', # 0x16b
    'NtCompressKey', # 0x16c
    'NtCompleteConnectPort', # 0x16d
    'NtCompareTokens', # 0x16e
    'NtCompactKeys', # 0x16f
    'NtCommitTransaction', # 0x170
    'NtCommitEnlistment', # 0x171
    'NtCommitComplete', # 0x172
    'NtCloseObjectAuditAlarm', # 0x173
    'NtClose', # 0x174
    'NtClearEvent', # 0x175
    'NtCancelWaitCompletionPacket', # 0x176
    'NtCancelTimer', # 0x177
    'NtCancelSynchronousIoFile', # 0x178
    'NtCancelIoFileEx', # 0x179
    'NtCancelIoFile', # 0x17a
    'NtCallbackReturn', # 0x17b
    'NtAssociateWaitCompletionPacket', # 0x17c
    'NtAssignProcessToJobObject', # 0x17d
    'NtAreMappedFilesTheSame', # 0x17e
    'NtApphelpCacheControl', # 0x17f
    'NtAlpcSetInformation', # 0x180
    'NtAlpcSendWaitReceivePort', # 0x181
    'NtAlpcRevokeSecurityContext', # 0x182
    'NtAlpcQueryInformationMessage', # 0x183
    'NtAlpcQueryInformation', # 0x184
    'NtAlpcOpenSenderThread', # 0x185
    'NtAlpcOpenSenderProcess', # 0x186
    'NtAlpcImpersonateClientOfPort', # 0x187
    'NtAlpcDisconnectPort', # 0x188
    'NtAlpcDeleteSecurityContext', # 0x189
    'NtAlpcDeleteSectionView', # 0x18a
    'NtAlpcDeleteResourceReserve', # 0x18b
    'NtAlpcDeletePortSection', # 0x18c
    'NtAlpcCreateSecurityContext', # 0x18d
    'NtAlpcCreateSectionView', # 0x18e
    'NtAlpcCreateResourceReserve', # 0x18f
    'NtAlpcCreatePortSection', # 0x190
    'NtAlpcCreatePort', # 0x191
    'NtAlpcConnectPort', # 0x192
    'NtAlpcConnectPortEx', # 0x193
    'NtAlpcCancelMessage', # 0x194
    'NtAlpcAcceptConnectPort', # 0x195
    'NtAllocateVirtualMemory', # 0x196
    'NtAllocateUuids', # 0x197
    'NtAllocateUserPhysicalPages', # 0x198
    'NtAllocateReserveObject', # 0x199
    'NtAllocateLocallyUniqueId', # 0x19a
    'NtAlertThreadByThreadId', # 0x19b
    'NtAlertThread', # 0x19c
    'NtAlertResumeThread', # 0x19d
    'NtAdjustPrivilegesToken', # 0x19e
    'NtAdjustGroupsToken', # 0x19f
    'NtAdjustTokenClaimsAndDeviceGroups', # 0x1a0
    'NtAddDriverEntry', # 0x1a1
    'NtAddBootEntry', # 0x1a2
    'NtAddAtom', # 0x1a3
    'NtAddAtomEx', # 0x1a4
    'NtAccessCheckByTypeResultListAndAuditAlarmByHandle', # 0x1a5
    'NtAccessCheckByTypeResultListAndAuditAlarm', # 0x1a6
    'NtAccessCheckByTypeResultList', # 0x1a7
    'NtAccessCheckByTypeAndAuditAlarm', # 0x1a8
    'NtAccessCheckByType', # 0x1a9
    'NtAccessCheckAndAuditAlarm', # 0x1aa
    'NtAccessCheck', # 0x1ab
    'NtAcceptConnectPort', # 0x1ac
    ],
    [
    'NtUserYieldTask', # 0x0
    'NtGdiWidenPath', # 0x1
    'NtGdiUpdateColors', # 0x2
    'NtGdiUnrealizeObject', # 0x3
    'NtGdiUnmapMemFont', # 0x4
    'NtGdiUnloadPrinterDriver', # 0x5
    'NtGdiTransparentBlt', # 0x6
    'NtGdiTransformPoints', # 0x7
    'NtGdiSwapBuffers', # 0x8
    'NtGdiStrokePath', # 0x9
    'NtGdiStrokeAndFillPath', # 0xa
    'NtGdiStretchDIBitsInternal', # 0xb
    'NtGdiStretchBlt', # 0xc
    'NtGdiStartPage', # 0xd
    'NtGdiStartDoc', # 0xe
    'NtGdiSetSizeDevice', # 0xf
    'NtGdiSetVirtualResolution', # 0x10
    'NtGdiSetTextJustification', # 0x11
    'NtGdiSetSystemPaletteUse', # 0x12
    'NtGdiSetRectRgn', # 0x13
    'NtGdiSetPixelFormat', # 0x14
    'NtGdiSetPixel', # 0x15
    'NtGdiSetOPMSigningKeyAndSequenceNumbers', # 0x16
    'NtGdiSetLayout', # 0x17
    'NtGdiMirrorWindowOrg', # 0x18
    'NtGdiGetDeviceWidth', # 0x19
    'NtGdiSetMiterLimit', # 0x1a
    'NtGdiSetMetaRgn', # 0x1b
    'NtGdiSetMagicColors', # 0x1c
    'NtGdiSetLinkedUFIs', # 0x1d
    'NtGdiSetIcmMode', # 0x1e
    'NtGdiSetFontXform', # 0x1f
    'NtGdiSetFontEnumeration', # 0x20
    'NtGdiSetDIBitsToDeviceInternal', # 0x21
    'NtGdiSetDeviceGammaRamp', # 0x22
    'NtGdiSetColorSpace', # 0x23
    'NtGdiSetColorAdjustment', # 0x24
    'NtGdiSetBrushOrg', # 0x25
    'NtGdiSetBrushAttributes', # 0x26
    'NtGdiSetBoundsRect', # 0x27
    'NtGdiSetBitmapDimension', # 0x28
    'NtGdiSetBitmapBits', # 0x29
    'NtGdiSetBitmapAttributes', # 0x2a
    'NtGdiSelectPen', # 0x2b
    'NtGdiSelectFont', # 0x2c
    'NtGdiSelectClipPath', # 0x2d
    'NtGdiSelectBrush', # 0x2e
    'NtGdiSelectBitmap', # 0x2f
    'NtGdiScaleWindowExtEx', # 0x30
    'NtGdiScaleViewportExtEx', # 0x31
    'NtGdiSaveDC', # 0x32
    'NtGdiRoundRect', # 0x33
    'NtGdiRestoreDC', # 0x34
    'NtGdiResizePalette', # 0x35
    'NtGdiResetDC', # 0x36
    'NtGdiRemoveFontMemResourceEx', # 0x37
    'NtGdiRemoveFontResourceW', # 0x38
    'NtGdiRectVisible', # 0x39
    'NtGdiRectInRegion', # 0x3a
    'NtGdiRectangle', # 0x3b
    'NtGdiQueryFontAssocInfo', # 0x3c
    'NtGdiQueryFonts', # 0x3d
    'NtGdiPtVisible', # 0x3e
    'NtGdiPtInRegion', # 0x3f
    'NtGdiPolyTextOutW', # 0x40
    'NtGdiPolyPolyDraw', # 0x41
    'NtGdiPolyDraw', # 0x42
    'NtGdiPlgBlt', # 0x43
    'NtGdiPathToRegion', # 0x44
    'NtGdiPolyPatBlt', # 0x45
    'NtGdiPatBlt', # 0x46
    'NtGdiOpenDCW', # 0x47
    'NtGdiOffsetRgn', # 0x48
    'NtGdiOffsetClipRgn', # 0x49
    'NtGdiMoveTo', # 0x4a
    'NtGdiMonoBitmap', # 0x4b
    'NtGdiModifyWorldTransform', # 0x4c
    'NtGdiMaskBlt', # 0x4d
    'NtGdiMakeInfoDC', # 0x4e
    'NtGdiMakeFontDir', # 0x4f
    'NtGdiLineTo', # 0x50
    'NtGdiInvertRgn', # 0x51
    'NtGdiIntersectClipRect', # 0x52
    'NtGdiInitSpool', # 0x53
    'NtGdiInit', # 0x54
    'NtGdiIcmBrushInfo', # 0x55
    'NtGdiHfontCreate', # 0x56
    'NtGdiGradientFill', # 0x57
    'NtGdiGetWidthTable', # 0x58
    'NtGdiGetFontUnicodeRanges', # 0x59
    'NtGdiAddEmbFontToDC', # 0x5a
    'NtGdiChangeGhostFont', # 0x5b
    'NtGdiGetEmbedFonts', # 0x5c
    'NtGdiGetUFIPathname', # 0x5d
    'NtGdiGetEmbUFI', # 0x5e
    'NtGdiGetUFI', # 0x5f
    'NtGdiGetTransform', # 0x60
    'NtGdiGetTextMetricsW', # 0x61
    'NtGdiGetTextFaceW', # 0x62
    'NtGdiGetTextExtentExW', # 0x63
    'NtGdiGetTextExtent', # 0x64
    'NtGdiGetTextCharsetInfo', # 0x65
    'NtGdiGetSystemPaletteUse', # 0x66
    'NtGdiGetSuggestedOPMProtectedOutputArraySize', # 0x67
    'NtGdiGetStringBitmapW', # 0x68
    'NtGdiGetStockObject', # 0x69
    'NtGdiGetStats', # 0x6a
    'NtGdiGetSpoolMessage', # 0x6b
    'NtGdiGetServerMetaFileBits', # 0x6c
    'NtGdiGetRgnBox', # 0x6d
    'NtGdiGetRegionData', # 0x6e
    'NtGdiGetRealizationInfo', # 0x6f
    'NtGdiGetRasterizerCaps', # 0x70
    'NtGdiGetRandomRgn', # 0x71
    'NtGdiGetPixel', # 0x72
    'NtGdiGetPath', # 0x73
    'NtGdiGetOutlineTextMetricsInternalW', # 0x74
    'NtGdiGetOPMRandomNumber', # 0x75
    'NtGdiGetObjectBitmapHandle', # 0x76
    'NtGdiGetNearestPaletteIndex', # 0x77
    'NtGdiGetNearestColor', # 0x78
    'NtGdiGetMonitorID', # 0x79
    'NtGdiGetMiterLimit', # 0x7a
    'NtGdiGetLinkedUFIs', # 0x7b
    'NtGdiGetKerningPairs', # 0x7c
    'NtGdiGetOPMInformation', # 0x7d
    'NtGdiGetGlyphOutline', # 0x7e
    'NtGdiGetGlyphIndicesWInternal', # 0x7f
    'NtGdiGetGlyphIndicesW', # 0x80
    'NtGdiGetFontResourceInfoInternalW', # 0x81
    'NtGdiGetFontFileInfo', # 0x82
    'NtGdiGetFontFileData', # 0x83
    'NtGdiGetFontData', # 0x84
    'NtGdiGetEudcTimeStampEx', # 0x85
    'NtGdiGetETM', # 0x86
    'NtGdiGetDIBitsInternal', # 0x87
    'NtGdiGetDeviceCapsAll', # 0x88
    'NtGdiGetDeviceGammaRamp', # 0x89
    'NtGdiGetDeviceCaps', # 0x8a
    'NtGdiGetDCPoint', # 0x8b
    'NtGdiGetDCObject', # 0x8c
    'NtGdiGetDCforBitmap', # 0x8d
    'NtGdiGetDCDword', # 0x8e
    'NtGdiGetCOPPCompatibleOPMInformation', # 0x8f
    'NtGdiGetColorSpaceforBitmap', # 0x90
    'NtGdiGetColorAdjustment', # 0x91
    'NtGdiGetCharWidthInfo', # 0x92
    'NtGdiGetCharWidthW', # 0x93
    'NtGdiGetCharSet', # 0x94
    'NtGdiGetCharacterPlacementW', # 0x95
    'NtGdiGetCharABCWidthsW', # 0x96
    'NtGdiGetCertificateSize', # 0x97
    'NtGdiGetCertificate', # 0x98
    'NtGdiGetBoundsRect', # 0x99
    'NtGdiGetBitmapDimension', # 0x9a
    'NtGdiGetBitmapBits', # 0x9b
    'NtGdiGetAppClipBox', # 0x9c
    'NtGdiGetAndSetDCDword', # 0x9d
    'NtGdiFullscreenControl', # 0x9e
    'NtGdiFrameRgn', # 0x9f
    'NtGdiForceUFIMapping', # 0xa0
    'NtGdiFlush', # 0xa1
    'NtGdiFlattenPath', # 0xa2
    'NtGdiFillRgn', # 0xa3
    'NtGdiFillPath', # 0xa4
    'NtGdiExtTextOutW', # 0xa5
    'NtGdiExtSelectClipRgn', # 0xa6
    'NtGdiExtGetObjectW', # 0xa7
    'NtGdiExtFloodFill', # 0xa8
    'NtGdiExtEscape', # 0xa9
    'NtGdiExtCreateRegion', # 0xaa
    'NtGdiExtCreatePen', # 0xab
    'NtGdiExcludeClipRect', # 0xac
    'NtGdiEudcLoadUnloadLink', # 0xad
    'NtGdiEqualRgn', # 0xae
    'NtGdiEnumObjects', # 0xaf
    'NtGdiEnumFonts', # 0xb0
    'NtGdiEndPath', # 0xb1
    'NtGdiEndPage', # 0xb2
    'NtGdiEndGdiRendering', # 0xb3
    'NtGdiEndDoc', # 0xb4
    'NtGdiEnableEudc', # 0xb5
    'NtGdiEllipse', # 0xb6
    'NtGdiDrawEscape', # 0xb7
    'NtGdiDoPalette', # 0xb8
    'NtGdiDoBanding', # 0xb9
    'NtGdiGetPerBandInfo', # 0xba
    'NtGdiDestroyOPMProtectedOutput', # 0xbb
    'NtGdiDescribePixelFormat', # 0xbc
    'NtGdiDeleteObjectApp', # 0xbd
    'NtGdiDeleteColorTransform', # 0xbe
    'NtGdiDeleteColorSpace', # 0xbf
    'NtGdiDeleteClientObj', # 0xc0
    'NtGdiDxgGenericThunk', # 0xc1
    'NtGdiDvpReleaseNotification', # 0xc2
    'NtGdiDvpAcquireNotification', # 0xc3
    'NtGdiDvpWaitForVideoPortSync', # 0xc4
    'NtGdiDvpUpdateVideoPort', # 0xc5
    'NtGdiDvpGetVideoSignalStatus', # 0xc6
    'NtGdiDvpGetVideoPortConnectInfo', # 0xc7
    'NtGdiDvpGetVideoPortOutputFormats', # 0xc8
    'NtGdiDvpGetVideoPortLine', # 0xc9
    'NtGdiDvpGetVideoPortInputFormats', # 0xca
    'NtGdiDvpGetVideoPortFlipStatus', # 0xcb
    'NtGdiDvpGetVideoPortField', # 0xcc
    'NtGdiDvpGetVideoPortBandwidth', # 0xcd
    'NtGdiDvpFlipVideoPort', # 0xce
    'NtGdiDvpDestroyVideoPort', # 0xcf
    'NtGdiDvpCreateVideoPort', # 0xd0
    'NtGdiDvpColorControl', # 0xd1
    'NtGdiDvpCanCreateVideoPort', # 0xd2
    'NtGdiDdWaitForVerticalBlank', # 0xd3
    'NtGdiDdUpdateOverlay', # 0xd4
    'NtGdiDdUnlockD3D', # 0xd5
    'NtGdiDdUnlock', # 0xd6
    'NtGdiDdUnattachSurface', # 0xd7
    'NtGdiDdSetOverlayPosition', # 0xd8
    'NtGdiDdCreateSurfaceEx', # 0xd9
    'NtGdiDdSetGammaRamp', # 0xda
    'NtGdiDdSetExclusiveMode', # 0xdb
    'NtGdiDdSetColorKey', # 0xdc
    'NtGdiDdResetVisrgn', # 0xdd
    'NtGdiDdRenderMoComp', # 0xde
    'NtGdiDdReleaseDC', # 0xdf
    'NtGdiDdReenableDirectDrawObject', # 0xe0
    'NtGdiDdQueryMoCompStatus', # 0xe1
    'NtGdiDdQueryDirectDrawObject', # 0xe2
    'NtGdiDdLockD3D', # 0xe3
    'NtGdiDdLock', # 0xe4
    'NtGdiDdGetScanLine', # 0xe5
    'NtGdiDdGetMoCompFormats', # 0xe6
    'NtGdiDdGetMoCompGuids', # 0xe7
    'NtGdiDdGetMoCompBuffInfo', # 0xe8
    'NtGdiDdGetInternalMoCompInfo', # 0xe9
    'NtGdiDdGetFlipStatus', # 0xea
    'NtGdiDdGetDxHandle', # 0xeb
    'NtGdiDdGetDriverInfo', # 0xec
    'NtGdiDdGetDC', # 0xed
    'NtGdiDdGetBltStatus', # 0xee
    'NtGdiDdGetAvailDriverMemory', # 0xef
    'NtGdiDdFlipToGDISurface', # 0xf0
    'NtGdiDdFlip', # 0xf1
    'NtGdiDdEndMoCompFrame', # 0xf2
    'NtGdiDdDestroyD3DBuffer', # 0xf3
    'NtGdiDdDestroySurface', # 0xf4
    'NtGdiDdDestroyMoComp', # 0xf5
    'NtGdiDdDeleteSurfaceObject', # 0xf6
    'NtGdiDdDeleteDirectDrawObject', # 0xf7
    'NtGdiDdCreateSurfaceObject', # 0xf8
    'NtGdiDdCreateMoComp', # 0xf9
    'NtGdiDdCreateD3DBuffer', # 0xfa
    'NtGdiDdCreateSurface', # 0xfb
    'NtGdiDdCreateDirectDrawObject', # 0xfc
    'NtGdiDdColorControl', # 0xfd
    'NtGdiDdCanCreateD3DBuffer', # 0xfe
    'NtGdiDdCanCreateSurface', # 0xff
    'NtGdiDdBlt', # 0x100
    'NtGdiDdBeginMoCompFrame', # 0x101
    'NtGdiDdAttachSurface', # 0x102
    'NtGdiDdAlphaBlt', # 0x103
    'NtGdiDdAddAttachedSurface', # 0x104
    'NtGdiDdGetDriverState', # 0x105
    'NtGdiD3dDrawPrimitives2', # 0x106
    'NtGdiD3dValidateTextureStageState', # 0x107
    'NtGdiD3dContextDestroyAll', # 0x108
    'NtGdiD3dContextDestroy', # 0x109
    'NtGdiD3dContextCreate', # 0x10a
    'NtGdiCreateSolidBrush', # 0x10b
    'NtGdiCreateServerMetaFile', # 0x10c
    'NtGdiCreateRoundRectRgn', # 0x10d
    'NtGdiCreateRectRgn', # 0x10e
    'NtGdiCreatePen', # 0x10f
    'NtGdiCreatePatternBrushInternal', # 0x110
    'NtGdiCreatePaletteInternal', # 0x111
    'NtGdiCreateOPMProtectedOutputs', # 0x112
    'NtGdiCreateMetafileDC', # 0x113
    'NtGdiCreateHatchBrushInternal', # 0x114
    'NtGdiCreateHalftonePalette', # 0x115
    'NtGdiCreateEllipticRgn', # 0x116
    'NtGdiCreateSessionMappedDIBSection', # 0x117
    'NtGdiCreateDIBSection', # 0x118
    'NtGdiCreateDIBitmapInternal', # 0x119
    'NtGdiCreateDIBBrush', # 0x11a
    'NtGdiCreateCompatibleDC', # 0x11b
    'NtGdiCreateCompatibleBitmap', # 0x11c
    'NtGdiCreateColorTransform', # 0x11d
    'NtGdiCreateColorSpace', # 0x11e
    'NtGdiCreateClientObj', # 0x11f
    'NtGdiCreateBitmapFromDxSurface2', # 0x120
    'NtGdiCreateBitmapFromDxSurface', # 0x121
    'NtGdiCreateBitmap', # 0x122
    'NtGdiConvertMetafileRect', # 0x123
    'NtGdiConfigureOPMProtectedOutput', # 0x124
    'NtGdiComputeXformCoefficients', # 0x125
    'NtGdiCombineTransform', # 0x126
    'NtGdiCombineRgn', # 0x127
    'NtGdiColorCorrectPalette', # 0x128
    'NtGdiClearBrushAttributes', # 0x129
    'NtGdiClearBitmapAttributes', # 0x12a
    'NtGdiCloseFigure', # 0x12b
    'NtGdiCheckBitmapBits', # 0x12c
    'NtGdiCancelDC', # 0x12d
    'NtGdiBitBlt', # 0x12e
    'NtGdiBeginPath', # 0x12f
    'NtGdiBeginGdiRendering', # 0x130
    'NtGdiArcInternal', # 0x131
    'NtGdiFontIsLinked', # 0x132
    'NtGdiAnyLinkedFonts', # 0x133
    'NtGdiAngleArc', # 0x134
    'NtGdiAlphaBlend', # 0x135
    'NtGdiAddRemoteMMInstanceToDC', # 0x136
    'NtGdiRemoveMergeFont', # 0x137
    'NtGdiAddFontMemResourceEx', # 0x138
    'NtGdiAddRemoteFontToDC', # 0x139
    'NtGdiAddFontResourceW', # 0x13a
    'NtGdiAbortPath', # 0x13b
    'NtGdiAbortDoc', # 0x13c
    'NtUserDefSetText', # 0x13d
    'NtUserDeferWindowPosAndBand', # 0x13e
    'NtUserDdeInitialize', # 0x13f
    'NtUserCanBrokerForceForeground', # 0x140
    'NtUserCreateWindowStation', # 0x141
    'NtUserCreateWindowEx', # 0x142
    'NtUserCreateLocalMemHandle', # 0x143
    'NtUserCreateInputContext', # 0x144
    'NtUserCreateDesktopEx', # 0x145
    'NtUserCreateCaret', # 0x146
    'NtUserCreateAcceleratorTable', # 0x147
    'NtUserCountClipboardFormats', # 0x148
    'NtUserCopyAcceleratorTable', # 0x149
    'NtUserConvertMemHandle', # 0x14a
    'NtUserConsoleControl', # 0x14b
    'NtUserCloseWindowStation', # 0x14c
    'NtUserCloseDesktop', # 0x14d
    'NtUserCloseClipboard', # 0x14e
    'NtUserClipCursor', # 0x14f
    'NtUserChildWindowFromPointEx', # 0x150
    'NtUserCheckMenuItem', # 0x151
    'NtUserCheckWindowThreadDesktop', # 0x152
    'NtUserDwmValidateWindow', # 0x153
    'NtUserCheckAccessForIntegrityLevel', # 0x154
    'NtUserDisplayConfigSetDeviceInfo', # 0x155
    'NtUserDisplayConfigGetDeviceInfo', # 0x156
    'NtUserQueryDisplayConfig', # 0x157
    'NtUserSetDisplayConfig', # 0x158
    'NtUserGetDisplayConfigBufferSizes', # 0x159
    'NtUserChangeDisplaySettings', # 0x15a
    'NtUserChangeClipboardChain', # 0x15b
    'NtUserCallTwoParam', # 0x15c
    'NtUserCallOneParam', # 0x15d
    'NtUserCallNoParam', # 0x15e
    'NtUserCallNextHookEx', # 0x15f
    'NtUserCallMsgFilter', # 0x160
    'NtUserCallHwndParamLock', # 0x161
    'NtUserCallHwndParam', # 0x162
    'NtUserCallHwndOpt', # 0x163
    'NtUserCallHwndLock', # 0x164
    'NtUserCallHwnd', # 0x165
    'NtUserBuildPropList', # 0x166
    'NtUserBuildNameList', # 0x167
    'NtUserBuildHwndList', # 0x168
    'NtUserBuildHimcList', # 0x169
    'NtUserBlockInput', # 0x16a
    'NtUserBitBltSysBmp', # 0x16b
    'NtUserBeginPaint', # 0x16c
    'NtUserAttachThreadInput', # 0x16d
    'NtUserAssociateInputContext', # 0x16e
    'NtUserAlterWindowStyle', # 0x16f
    'NtUserAddClipboardFormatListener', # 0x170
    'NtUserActivateKeyboardLayout', # 0x171
    'NtUserDelegateCapturePointers', # 0x172
    'NtUserDelegateInput', # 0x173
    'NtUserDispatchMessage', # 0x174
    'NtUserDisableProcessWindowFiltering', # 0x175
    'NtUserDisableThreadIme', # 0x176
    'NtUserDestroyWindow', # 0x177
    'NtUserDestroyMenu', # 0x178
    'NtUserDestroyInputContext', # 0x179
    'NtUserDestroyCursor', # 0x17a
    'NtUserDestroyAcceleratorTable', # 0x17b
    'NtUserDeleteMenu', # 0x17c
    'NtUserDoSoundDisconnect', # 0x17d
    'NtUserDoSoundConnect', # 0x17e
    'NtUserGhostWindowFromHungWindow', # 0x17f
    'NtUserGetWOWClass', # 0x180
    'NtUserGetWindowPlacement', # 0x181
    'NtUserGetWindowDisplayAffinity', # 0x182
    'NtUserGetWindowDC', # 0x183
    'NtUserGetWindowCompositionAttribute', # 0x184
    'NtUserGetWindowCompositionInfo', # 0x185
    'NtUserGetWindowBand', # 0x186
    'NtUserGetUpdateRgn', # 0x187
    'NtUserGetUpdateRect', # 0x188
    'NtUserGetUpdatedClipboardFormats', # 0x189
    'NtUserGetTopLevelWindow', # 0x18a
    'NtUserGetTitleBarInfo', # 0x18b
    'NtUserGetThreadState', # 0x18c
    'NtUserGetThreadDesktop', # 0x18d
    'NtUserGetSystemMenu', # 0x18e
    'NtUserGetScrollBarInfo', # 0x18f
    'NtUserGetRegisteredRawInputDevices', # 0x190
    'NtUserGetRawInputDeviceList', # 0x191
    'NtUserGetRawInputDeviceInfo', # 0x192
    'NtUserGetRawInputData', # 0x193
    'NtUserGetRawInputBuffer', # 0x194
    'NtUserGetProcessWindowStation', # 0x195
    'NtUserGetPriorityClipboardFormat', # 0x196
    'NtUserGetOpenClipboardWindow', # 0x197
    'NtUserGetObjectInformation', # 0x198
    'NtUserGetMouseMovePointsEx', # 0x199
    'NtUserGetMessage', # 0x19a
    'NtUserGetMenuItemRect', # 0x19b
    'NtUserGetMenuIndex', # 0x19c
    'NtUserGetMenuBarInfo', # 0x19d
    'NtUserGetListBoxInfo', # 0x19e
    'NtUserGetKeyState', # 0x19f
    'NtUserGetKeyNameText', # 0x1a0
    'NtUserGetKeyboardState', # 0x1a1
    'NtUserGetKeyboardLayoutName', # 0x1a2
    'NtUserGetKeyboardLayoutList', # 0x1a3
    'NtUserGetInternalWindowPos', # 0x1a4
    'NtUserGetInputLocaleInfo', # 0x1a5
    'NtUserGetImeInfoEx', # 0x1a6
    'NtUserGetImeHotKey', # 0x1a7
    'NtUserGetIconSize', # 0x1a8
    'NtUserGetIconInfo', # 0x1a9
    'NtUserGetGUIThreadInfo', # 0x1aa
    'NtUserGetGuiResources', # 0x1ab
    'NtUserGetGlobalIMEStatus', # 0x1ac
    'NtUserGetForegroundWindow', # 0x1ad
    'NtUserGetDoubleClickTime', # 0x1ae
    'NtUserGetDesktopID', # 0x1af
    'NtUserGetDCEx', # 0x1b0
    'NtUserGetDC', # 0x1b1
    'NtUserGetCursorInfo', # 0x1b2
    'NtUserGetCursorFrameInfo', # 0x1b3
    'NtUserGetCurrentInputMessageSource', # 0x1b4
    'NtUserGetCIMSSM', # 0x1b5
    'NtUserGetCPD', # 0x1b6
    'NtUserGetControlColor', # 0x1b7
    'NtUserGetControlBrush', # 0x1b8
    'NtUserGetComboBoxInfo', # 0x1b9
    'NtUserGetClipCursor', # 0x1ba
    'NtUserGetClipboardViewer', # 0x1bb
    'NtUserGetClipboardSequenceNumber', # 0x1bc
    'NtUserGetClipboardOwner', # 0x1bd
    'NtUserGetClipboardFormatName', # 0x1be
    'NtUserGetClipboardData', # 0x1bf
    'NtUserGetClassName', # 0x1c0
    'NtUserGetClassInfoEx', # 0x1c1
    'NtUserGetCaretPos', # 0x1c2
    'NtUserGetCaretBlinkTime', # 0x1c3
    'NtUserGetAtomName', # 0x1c4
    'NtUserGetAsyncKeyState', # 0x1c5
    'NtUserGetAppImeLevel', # 0x1c6
    'NtUserGetAncestor', # 0x1c7
    'NtUserGetAltTabInfo', # 0x1c8
    'NtUserFrostCrashedWindow', # 0x1c9
    'NtUserFlashWindowEx', # 0x1ca
    'NtUserFindWindowEx', # 0x1cb
    'NtUserFindExistingCursorIcon', # 0x1cc
    'NtUserFillWindow', # 0x1cd
    'NtUserExcludeUpdateRgn', # 0x1ce
    'NtUserEvent', # 0x1cf
    'NtUserEnumDisplaySettings', # 0x1d0
    'NtUserEnumDisplayMonitors', # 0x1d1
    'NtUserEnumDisplayDevices', # 0x1d2
    'NtUserEndPaint', # 0x1d3
    'NtUserEndMenu', # 0x1d4
    'NtUserEndDeferWindowPosEx', # 0x1d5
    'NtUserEnableScrollBar', # 0x1d6
    'NtUserEnableMenuItem', # 0x1d7
    'NtUserEmptyClipboard', # 0x1d8
    'NtUserDrawMenuBarTemp', # 0x1d9
    'NtUserDrawIconEx', # 0x1da
    'NtUserDrawCaptionTemp', # 0x1db
    'NtUserDrawCaption', # 0x1dc
    'NtUserDrawAnimatedRects', # 0x1dd
    'NtUserDragObject', # 0x1de
    'NtUserDragDetect', # 0x1df
    'NtUserHandleDelegatedInput', # 0x1e0
    'NtUserRealChildWindowFromPoint', # 0x1e1
    'NtUserQueryWindow', # 0x1e2
    'NtUserQuerySendMessage', # 0x1e3
    'NtUserQueryInputContext', # 0x1e4
    'NtUserQueryInformationThread', # 0x1e5
    'NtUserQueryBSDRWindow', # 0x1e6
    'NtUserProcessConnect', # 0x1e7
    'NtUserPrintWindow', # 0x1e8
    'NtUserPostThreadMessage', # 0x1e9
    'NtUserPostMessage', # 0x1ea
    'NtUserPhysicalToLogicalPoint', # 0x1eb
    'NtUserPeekMessage', # 0x1ec
    'NtUserPaintMonitor', # 0x1ed
    'NtUserPaintDesktop', # 0x1ee
    'NtUserOpenWindowStation', # 0x1ef
    'NtUserOpenThreadDesktop', # 0x1f0
    'NtUserOpenInputDesktop', # 0x1f1
    'NtUserOpenDesktop', # 0x1f2
    'NtUserOpenClipboard', # 0x1f3
    'NtUserNotifyWinEvent', # 0x1f4
    'NtUserNotifyProcessCreate', # 0x1f5
    'NtUserNotifyIMEStatus', # 0x1f6
    'NtUserMoveWindow', # 0x1f7
    'NtUserModifyUserStartupInfoFlags', # 0x1f8
    'NtUserMNDragOver', # 0x1f9
    'NtUserMNDragLeave', # 0x1fa
    'NtUserMinMaximize', # 0x1fb
    'NtUserMessageCall', # 0x1fc
    'NtUserMenuItemFromPoint', # 0x1fd
    'NtUserMapVirtualKeyEx', # 0x1fe
    'NtUserLayoutCompleted', # 0x1ff
    'NtUserLogicalToPhysicalPoint', # 0x200
    'NtUserLockWorkStation', # 0x201
    'NtUserLockWindowUpdate', # 0x202
    'NtUserLockWindowStation', # 0x203
    'NtUserLoadKeyboardLayoutEx', # 0x204
    'NtUserKillTimer', # 0x205
    'NtUserIsTopLevelWindow', # 0x206
    'NtUserIsClipboardFormatAvailable', # 0x207
    'NtUserInvalidateRgn', # 0x208
    'NtUserInvalidateRect', # 0x209
    'NtUserInternalGetWindowIcon', # 0x20a
    'NtUserInternalGetWindowText', # 0x20b
    'NtUserInitTask', # 0x20c
    'NtUserInitializeClientPfnArrays', # 0x20d
    'NtUserInitialize', # 0x20e
    'NtUserImpersonateDdeClientWindow', # 0x20f
    'NtUserHungWindowFromGhostWindow', # 0x210
    'NtUserHiliteMenuItem', # 0x211
    'NtUserHideCaret', # 0x212
    'NtUserHardErrorControl', # 0x213
    'NtUserRealInternalGetMessage', # 0x214
    'NtUserRealWaitMessageEx', # 0x215
    'NtUserTranslateMessage', # 0x216
    'NtUserTranslateAccelerator', # 0x217
    'NtUserPaintMenuBar', # 0x218
    'NtUserCalcMenuBar', # 0x219
    'NtUserCalculatePopupWindowPosition', # 0x21a
    'NtUserTrackPopupMenuEx', # 0x21b
    'NtUserTrackMouseEvent', # 0x21c
    'NtUserToUnicodeEx', # 0x21d
    'NtUserThunkedMenuItemInfo', # 0x21e
    'NtUserThunkedMenuInfo', # 0x21f
    'NtUserTestForInteractiveUser', # 0x220
    'NtUserSendEventMessage', # 0x221
    'NtUserSystemParametersInfo', # 0x222
    'NtUserSwitchDesktop', # 0x223
    'NtUserSoundSentry', # 0x224
    'NtUserShutdownReasonDestroy', # 0x225
    'NtUserShutdownBlockReasonQuery', # 0x226
    'NtUserShutdownBlockReasonCreate', # 0x227
    'NtUserShowWindowAsync', # 0x228
    'NtUserShowWindow', # 0x229
    'NtUserShowScrollBar', # 0x22a
    'NtUserShowCaret', # 0x22b
    'NtUserSetWinEventHook', # 0x22c
    'NtUserSetWindowWord', # 0x22d
    'NtUserSetWindowStationUser', # 0x22e
    'NtUserSetWindowsHookEx', # 0x22f
    'NtUserSetWindowsHookAW', # 0x230
    'NtUserSetWindowRgnEx', # 0x231
    'NtUserGetWindowRgnEx', # 0x232
    'NtUserSetWindowRgn', # 0x233
    'NtUserSetWindowPos', # 0x234
    'NtUserSetWindowPlacement', # 0x235
    'NtUserSetWindowLong', # 0x236
    'NtUserSetWindowFNID', # 0x237
    'NtUserSetWindowDisplayAffinity', # 0x238
    'NtUserSetWindowCompositionTransition', # 0x239
    'NtUserUpdateDefaultDesktopThumbnail', # 0x23a
    'NtUserSetWindowCompositionAttribute', # 0x23b
    'NtUserSetWindowBand', # 0x23c
    'NtUserSetProcessUIAccessZorder', # 0x23d
    'NtUserSetProcessDPIAware', # 0x23e
    'NtUserSetTimer', # 0x23f
    'NtUserSetThreadState', # 0x240
    'NtUserSetThreadLayoutHandles', # 0x241
    'NtUserSetThreadDesktop', # 0x242
    'NtUserSetThreadInputBlocked', # 0x243
    'NtUserSetSystemTimer', # 0x244
    'NtUserSetSystemMenu', # 0x245
    'NtUserSetSystemCursor', # 0x246
    'NtUserSetSysColors', # 0x247
    'NtUserSetShellWindowEx', # 0x248
    'NtUserSetImmersiveBackgroundWindow', # 0x249
    'NtUserSetScrollInfo', # 0x24a
    'NtUserSetProp', # 0x24b
    'NtUserGetProp', # 0x24c
    'NtUserSetProcessWindowStation', # 0x24d
    'NtUserSetParent', # 0x24e
    'NtUserSetObjectInformation', # 0x24f
    'NtUserSetMenuFlagRtoL', # 0x250
    'NtUserSetMenuDefaultItem', # 0x251
    'NtUserSetMenuContextHelpId', # 0x252
    'NtUserSetMenu', # 0x253
    'NtUserSetKeyboardState', # 0x254
    'NtUserSetInternalWindowPos', # 0x255
    'NtUserSetInformationThread', # 0x256
    'NtUserSetImeOwnerWindow', # 0x257
    'NtUserSetImeInfoEx', # 0x258
    'NtUserSetImeHotKey', # 0x259
    'NtUserSetFocus', # 0x25a
    'NtUserSetCursorIconData', # 0x25b
    'NtUserSetCursorContents', # 0x25c
    'NtUserSetCursor', # 0x25d
    'NtUserSetClipboardViewer', # 0x25e
    'NtUserSetClipboardData', # 0x25f
    'NtUserSetClassWord', # 0x260
    'NtUserSetClassLong', # 0x261
    'NtUserSetChildWindowNoActivate', # 0x262
    'NtUserSetCapture', # 0x263
    'NtUserSetAppImeLevel', # 0x264
    'NtUserSetActiveWindow', # 0x265
    'NtUserSendInput', # 0x266
    'NtUserSelectPalette', # 0x267
    'NtUserScrollWindowEx', # 0x268
    'NtUserScrollDC', # 0x269
    'NtUserSBGetParms', # 0x26a
    'NtUserResolveDesktopForWOW', # 0x26b
    'NtUserRemoveProp', # 0x26c
    'NtUserRemoveMenu', # 0x26d
    'NtUserRemoveClipboardFormatListener', # 0x26e
    'NtUserRegisterWindowMessage', # 0x26f
    'NtUserRegisterTasklist', # 0x270
    'NtUserRegisterServicesProcess', # 0x271
    'NtUserRegisterRawInputDevices', # 0x272
    'NtUserRegisterHotKey', # 0x273
    'NtUserRegisterUserApiHook', # 0x274
    'NtUserRegisterErrorReportingDialog', # 0x275
    'NtUserRegisterClassExWOW', # 0x276
    'NtUserRegisterBSDRWindow', # 0x277
    'NtUserRedrawWindow', # 0x278
    'NtUserUndelegateInput', # 0x279
    'NtUserGetWindowMinimizeRect', # 0x27a
    'NtUserDwmStopRedirection', # 0x27b
    'NtUserDwmStartRedirection', # 0x27c
    'NtUserDwmGetRemoteSessionOcclusionEvent', # 0x27d
    'NtUserDwmGetRemoteSessionOcclusionState', # 0x27e
    'NtUserUpdateWindowTransform', # 0x27f
    'NtUserCheckProcessSession', # 0x280
    'NtUserUnregisterSessionPort', # 0x281
    'NtUserRegisterSessionPort', # 0x282
    'NtUserCtxDisplayIOCtl', # 0x283
    'NtUserRemoteStopScreenUpdates', # 0x284
    'NtUserRemoteRedrawScreen', # 0x285
    'NtUserRemoteRedrawRectangle', # 0x286
    'NtUserRemoteConnect', # 0x287
    'NtUserWaitAvailableMessageEx', # 0x288
    'NtUserWindowFromPoint', # 0x289
    'NtUserWindowFromPhysicalPoint', # 0x28a
    'NtUserWaitMessage', # 0x28b
    'NtUserWaitForMsgAndEvent', # 0x28c
    'NtUserWaitForInputIdle', # 0x28d
    'NtUserVkKeyScanEx', # 0x28e
    'NtUserValidateTimerCallback', # 0x28f
    'NtUserValidateRect', # 0x290
    'NtUserValidateHandleSecure', # 0x291
    'NtUserUserHandleGrantAccess', # 0x292
    'NtUserUpdatePerUserSystemParameters', # 0x293
    'NtUserSetLayeredWindowAttributes', # 0x294
    'NtUserGetLayeredWindowAttributes', # 0x295
    'NtUserUpdateLayeredWindow', # 0x296
    'NtUserUpdateInstance', # 0x297
    'NtUserUpdateInputContext', # 0x298
    'NtUserUnregisterHotKey', # 0x299
    'NtUserUnregisterUserApiHook', # 0x29a
    'NtUserUnregisterClass', # 0x29b
    'NtUserUnlockWindowStation', # 0x29c
    'NtUserUnloadKeyboardLayout', # 0x29d
    'NtUserUnhookWinEvent', # 0x29e
    'NtUserUnhookWindowsHookEx', # 0x29f
    'NtUserGetTouchInputInfo', # 0x2a0
    'NtUserIsTouchWindow', # 0x2a1
    'NtUserModifyWindowTouchCapability', # 0x2a2
    'NtGdiEngStretchBltROP', # 0x2a3
    'NtGdiEngTextOut', # 0x2a4
    'NtGdiEngTransparentBlt', # 0x2a5
    'NtGdiEngGradientFill', # 0x2a6
    'NtGdiEngAlphaBlend', # 0x2a7
    'NtGdiEngLineTo', # 0x2a8
    'NtGdiEngPaint', # 0x2a9
    'NtGdiEngStrokeAndFillPath', # 0x2aa
    'NtGdiEngFillPath', # 0x2ab
    'NtGdiEngStrokePath', # 0x2ac
    'NtGdiEngMarkBandingSurface', # 0x2ad
    'NtGdiEngPlgBlt', # 0x2ae
    'NtGdiEngStretchBlt', # 0x2af
    'NtGdiEngBitBlt', # 0x2b0
    'NtGdiEngLockSurface', # 0x2b1
    'NtGdiEngUnlockSurface', # 0x2b2
    'NtGdiEngEraseSurface', # 0x2b3
    'NtGdiEngDeleteSurface', # 0x2b4
    'NtGdiEngDeletePalette', # 0x2b5
    'NtGdiEngCopyBits', # 0x2b6
    'NtGdiEngComputeGlyphSet', # 0x2b7
    'NtGdiEngCreatePalette', # 0x2b8
    'NtGdiEngCreateDeviceBitmap', # 0x2b9
    'NtGdiEngCreateDeviceSurface', # 0x2ba
    'NtGdiEngCreateBitmap', # 0x2bb
    'NtGdiEngAssociateSurface', # 0x2bc
    'NtUserSetWindowFeedbackSetting', # 0x2bd
    'NtUserRegisterEdgy', # 0x2be
    'NtUserGetWindowFeedbackSetting', # 0x2bf
    'NtUserHidePointerContactVisualization', # 0x2c0
    'NtUserGetTouchValidationStatus', # 0x2c1
    'NtUserInitializeTouchInjection', # 0x2c2
    'NtUserInjectTouchInput', # 0x2c3
    'NtUserRegisterTouchHitTestingWindow', # 0x2c4
    'NtUserSetDisplayMapping', # 0x2c5
    'NtUserSetCalibrationData', # 0x2c6
    'NtUserGetRawPointerDeviceData', # 0x2c7
    'NtUserGetPointerDeviceCursors', # 0x2c8
    'NtUserGetPointerDeviceRects', # 0x2c9
    'NtUserRegisterPointerDeviceNotifications', # 0x2ca
    'NtUserGetPointerDeviceProperties', # 0x2cb
    'NtUserGetPointerDevice', # 0x2cc
    'NtUserGetPointerDevices', # 0x2cd
    'NtUserPromotePointer', # 0x2ce
    'NtUserDiscardPointerFrameMessages', # 0x2cf
    'NtUserRegisterPointerInputTarget', # 0x2d0
    'NtUserGetPointerInfoList', # 0x2d1
    'NtUserGetPointerCursorId', # 0x2d2
    'NtUserGetPointerType', # 0x2d3
    'NtUserGetGestureConfig', # 0x2d4
    'NtUserSetGestureConfig', # 0x2d5
    'NtUserGetGestureExtArgs', # 0x2d6
    'NtUserGetGestureInfo', # 0x2d7
    'NtUserInjectGesture', # 0x2d8
    'NtUserChangeWindowMessageFilterEx', # 0x2d9
    'NtGdiXLATEOBJ_hGetColorTransform', # 0x2da
    'NtGdiXLATEOBJ_iXlate', # 0x2db
    'NtGdiXLATEOBJ_cGetPalette', # 0x2dc
    'NtGdiEngDeleteClip', # 0x2dd
    'NtGdiEngCreateClip', # 0x2de
    'NtGdiEngDeletePath', # 0x2df
    'NtGdiCLIPOBJ_ppoGetPath', # 0x2e0
    'NtGdiCLIPOBJ_cEnumStart', # 0x2e1
    'NtGdiCLIPOBJ_bEnum', # 0x2e2
    'NtGdiBRUSHOBJ_hGetColorTransform', # 0x2e3
    'NtGdiBRUSHOBJ_pvGetRbrush', # 0x2e4
    'NtGdiBRUSHOBJ_pvAllocRbrush', # 0x2e5
    'NtGdiBRUSHOBJ_ulGetBrushColor', # 0x2e6
    'NtGdiXFORMOBJ_iGetXform', # 0x2e7
    'NtGdiXFORMOBJ_bApplyXform', # 0x2e8
    'NtGdiFONTOBJ_pQueryGlyphAttrs', # 0x2e9
    'NtGdiFONTOBJ_pfdg', # 0x2ea
    'NtGdiFONTOBJ_pifi', # 0x2eb
    'NtGdiFONTOBJ_cGetGlyphs', # 0x2ec
    'NtGdiFONTOBJ_pxoGetXform', # 0x2ed
    'NtGdiFONTOBJ_vGetInfo', # 0x2ee
    'NtGdiFONTOBJ_cGetAllGlyphHandles', # 0x2ef
    'NtGdiFONTOBJ_pvTrueTypeFontFile', # 0x2f0
    'NtGdiSTROBJ_dwGetCodePage', # 0x2f1
    'NtGdiSTROBJ_vEnumStart', # 0x2f2
    'NtGdiSTROBJ_bGetAdvanceWidths', # 0x2f3
    'NtGdiSTROBJ_bEnumPositionsOnly', # 0x2f4
    'NtGdiSTROBJ_bEnum', # 0x2f5
    'NtGdiPATHOBJ_bEnumClipLines', # 0x2f6
    'NtGdiPATHOBJ_vEnumStartClipLines', # 0x2f7
    'NtGdiPATHOBJ_vEnumStart', # 0x2f8
    'NtGdiPATHOBJ_bEnum', # 0x2f9
    'NtGdiPATHOBJ_vGetBounds', # 0x2fa
    'NtGdiEngCheckAbort', # 0x2fb
    'NtGdiGetDhpdev', # 0x2fc
    'NtGdiHT_Get8BPPMaskPalette', # 0x2fd
    'NtGdiHT_Get8BPPFormatPalette', # 0x2fe
    'NtGdiUpdateTransform', # 0x2ff
    'NtGdiUMPDEngFreeUserMem', # 0x300
    'NtGdiBRUSHOBJ_DeleteRbrush', # 0x301
    'NtGdiSetPUMPDOBJ', # 0x302
    'NtGdiSetUMPDSandboxState', # 0x303
    'NtGdiDrawStream', # 0x304
    'NtGdiHLSurfSetInformation', # 0x305
    'NtGdiHLSurfGetInformation', # 0x306
    'NtGdiDwmCreatedBitmapRemotingOutput', # 0x307
    'NtGdiDdDDIGetScanLine', # 0x308
    'NtGdiDdDDIReleaseProcessVidPnSourceOwners', # 0x309
    'NtGdiDdDDIGetProcessSchedulingPriorityClass', # 0x30a
    'NtGdiDdDDISetProcessSchedulingPriorityClass', # 0x30b
    'NtGdiDdDDIGetContextSchedulingPriority', # 0x30c
    'NtGdiDdDDISetContextSchedulingPriority', # 0x30d
    'NtGdiDdDDIDestroyDCFromMemory', # 0x30e
    'NtGdiDdDDICreateDCFromMemory', # 0x30f
    'NtGdiDdDDIGetDeviceState', # 0x310
    'NtGdiDdDDISetGammaRamp', # 0x311
    'NtGdiDdDDIWaitForVerticalBlankEvent', # 0x312
    'NtGdiDdDDIDestroyOverlay', # 0x313
    'NtGdiDdDDIFlipOverlay', # 0x314
    'NtGdiDdDDIUpdateOverlay', # 0x315
    'NtGdiDdDDICreateOverlay', # 0x316
    'NtGdiDdDDIGetPresentQueueEvent', # 0x317
    'NtGdiDdDDIGetPresentHistory', # 0x318
    'NtGdiDdDDISetVidPnSourceOwner1', # 0x319
    'NtGdiDdDDISetVidPnSourceOwner', # 0x31a
    'NtGdiDdDDIQueryStatistics', # 0x31b
    'NtGdiDdDDIEscape', # 0x31c
    'NtGdiDdDDIGetSharedPrimaryHandle', # 0x31d
    'NtGdiDdDDICloseAdapter', # 0x31e
    'NtGdiDdDDIOpenAdapterFromLuid', # 0x31f
    'NtGdiDdDDIEnumAdapters', # 0x320
    'NtGdiDdDDIOpenAdapterFromHdc', # 0x321
    'NtGdiDdDDIOpenAdapterFromDeviceName', # 0x322
    'NtGdiDdDDIRender', # 0x323
    'NtGdiDdDDIPresent', # 0x324
    'NtGdiDdDDIGetMultisampleMethodList', # 0x325
    'NtGdiDdDDISetDisplayMode', # 0x326
    'NtGdiDdDDIGetDisplayModeList', # 0x327
    'NtGdiDdDDIUnlock', # 0x328
    'NtGdiDdDDILock', # 0x329
    'NtGdiDdDDIQueryAdapterInfo', # 0x32a
    'NtGdiDdDDIGetRuntimeData', # 0x32b
    'NtGdiDdDDISignalSynchronizationObject', # 0x32c
    'NtGdiDdDDIWaitForSynchronizationObject', # 0x32d
    'NtGdiDdDDIDestroySynchronizationObject', # 0x32e
    'NtGdiDdDDIOpenSynchronizationObject', # 0x32f
    'NtGdiDdDDICreateSynchronizationObject', # 0x330
    'NtGdiDdDDIDestroyContext', # 0x331
    'NtGdiDdDDICreateContext', # 0x332
    'NtGdiDdDDIDestroyDevice', # 0x333
    'NtGdiDdDDICreateDevice', # 0x334
    'NtGdiDdDDIQueryAllocationResidency', # 0x335
    'NtGdiDdDDISetAllocationPriority', # 0x336
    'NtGdiDdDDIDestroyAllocation', # 0x337
    'NtGdiDdDDIOpenResourceFromNtHandle', # 0x338
    'NtGdiDdDDIOpenSyncObjectFromNtHandle', # 0x339
    'NtGdiDdDDIOpenResource', # 0x33a
    'NtGdiDdDDIOpenNtHandleFromName', # 0x33b
    'NtGdiDdDDIShareObjects', # 0x33c
    'NtGdiDdDDIQueryResourceInfoFromNtHandle', # 0x33d
    'NtGdiDdDDIQueryResourceInfo', # 0x33e
    'NtGdiDdDDICreateAllocation', # 0x33f
    'NtGdiDdDDIOutputDuplReleaseFrame', # 0x340
    'NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName', # 0x341
    'NtGdiDdDDIOutputDuplPresent', # 0x342
    'NtGdiDdDDIReleaseKeyedMutex2', # 0x343
    'NtGdiDdDDIAcquireKeyedMutex2', # 0x344
    'NtGdiDdDDIOpenKeyedMutex2', # 0x345
    'NtGdiDdDDICreateKeyedMutex2', # 0x346
    'NtGdiDdDDIOutputDuplGetPointerShapeData', # 0x347
    'NtGdiDdDDIOutputDuplGetMetaData', # 0x348
    'NtGdiDdDDIOutputDuplGetFrameInfo', # 0x349
    'NtGdiDdDDIDestroyOutputDupl', # 0x34a
    'NtGdiDdDDICreateOutputDupl', # 0x34b
    'NtGdiDdDDIReclaimAllocations', # 0x34c
    'NtGdiDdDDIOfferAllocations', # 0x34d
    'NtGdiDdDDICheckSharedResourceAccess', # 0x34e
    'NtGdiDdDDICheckVidPnExclusiveOwnership', # 0x34f
    'NtGdiDdDDIGetOverlayState', # 0x350
    'NtGdiDdDDIConfigureSharedResource', # 0x351
    'NtGdiDdDDIReleaseKeyedMutex', # 0x352
    'NtGdiDdDDIAcquireKeyedMutex', # 0x353
    'NtGdiDdDDIDestroyKeyedMutex', # 0x354
    'NtGdiDdDDIOpenKeyedMutex', # 0x355
    'NtGdiDdDDICreateKeyedMutex', # 0x356
    'NtGdiDdDDISharedPrimaryUnLockNotification', # 0x357
    'NtGdiDdDDISharedPrimaryLockNotification', # 0x358
    'NtGdiDdDDISetDisplayPrivateDriverFormat', # 0x359
    'NtGdiDdDDICheckExclusiveOwnership', # 0x35a
    'NtGdiDdDDICheckMonitorPowerState', # 0x35b
    'NtGdiDdDDIWaitForIdle', # 0x35c
    'NtGdiDdDDICheckOcclusion', # 0x35d
    'NtGdiDdDDIInvalidateActiveVidPn', # 0x35e
    'NtGdiDdDDIPollDisplayChildren', # 0x35f
    'NtGdiDdDDISetQueuedLimit', # 0x360
    'NtGdiDdDDIPinDirectFlipResources', # 0x361
    'NtGdiDdDDIUnpinDirectFlipResources', # 0x362
    'NtGdiDdDDIWaitForVerticalBlankEvent2', # 0x363
    'NtGdiDdDDISetContextInProcessSchedulingPriority', # 0x364
    'NtGdiDdDDIGetContextInProcessSchedulingPriority', # 0x365
    'NtGdiDdDDIGetSharedResourceAdapterLuid', # 0x366
    'NtGdiDdDDISetStereoEnabled', # 0x367
    'NtGdiMakeObjectUnXferable', # 0x368
    'NtGdiMakeObjectXferable', # 0x369
    'NtGdiDestroyPhysicalMonitor', # 0x36a
    'NtGdiGetPhysicalMonitorDescription', # 0x36b
    'NtGdiGetPhysicalMonitors', # 0x36c
    'NtGdiGetNumberOfPhysicalMonitors', # 0x36d
    'NtGdiDDCCIGetTimingReport', # 0x36e
    'NtGdiDDCCIGetCapabilitiesString', # 0x36f
    'NtGdiDDCCIGetCapabilitiesStringLength', # 0x370
    'NtGdiDDCCISaveCurrentSettings', # 0x371
    'NtGdiDDCCISetVCPFeature', # 0x372
    'NtGdiDDCCIGetVCPFeature', # 0x373
    'NtGdiDdQueryVisRgnUniqueness', # 0x374
    'NtGdiDdDestroyFullscreenSprite', # 0x375
    'NtGdiDdNotifyFullscreenSpriteUpdate', # 0x376
    'NtGdiDdCreateFullscreenSprite', # 0x377
    'NtUserShowSystemCursor', # 0x378
    'NtUserSetMirrorRendering', # 0x379
    'NtUserMagGetContextInformation', # 0x37a
    'NtUserMagSetContextInformation', # 0x37b
    'NtUserMagControl', # 0x37c
    'NtUserSlicerControl', # 0x37d
    'NtUserHwndSetRedirectionInfo', # 0x37e
    'NtUserHwndQueryRedirectionInfo', # 0x37f
    'NtCreateCompositionSurfaceHandle', # 0x380
    'NtValidateCompositionSurfaceHandle', # 0x381
    'NtBindCompositionSurface', # 0x382
    'NtUnBindCompositionSurface', # 0x383
    'NtQueryCompositionSurfaceBinding', # 0x384
    'NtNotifyPresentToCompositionSurface', # 0x385
    'NtQueryCompositionSurfaceStatistics', # 0x386
    'NtOpenCompositionSurfaceSectionInfo', # 0x387
    'NtOpenCompositionSurfaceSwapChainHandleInfo', # 0x388
    'NtQueryCompositionSurfaceRenderingRealization', # 0x389
    'NtOpenCompositionSurfaceDirtyRegion', # 0x38a
    'NtSetCompositionSurfaceOutOfFrameDirectFlipNotification', # 0x38b
    'NtSetCompositionSurfaceStatistics', # 0x38c
    'NtTokenManagerOpenEvent', # 0x38d
    'NtTokenManagerThread', # 0x38e
    'NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates', # 0x38f
    'NtDCompositionBeginFrame', # 0x390
    'NtDCompositionConfirmFrame', # 0x391
    'NtDCompositionRetireFrame', # 0x392
    'NtDCompositionDiscardFrame', # 0x393
    'NtDCompositionGetFrameSurfaceUpdates', # 0x394
    'NtDCompositionGetFrameLegacyTokens', # 0x395
    'NtDCompositionDestroyConnectionContext', # 0x396
    'NtDCompositionGetConnectionContextBatch', # 0x397
    'NtDCompositionGetFrameStatistics', # 0x398
    'NtDCompositionGetDeletedResources', # 0x399
    'NtDCompositionSetResourceDeletedNotificationTag', # 0x39a
    'NtDCompositionCreateConnectionContext', # 0x39b
    'NtDCompositionDestroyChannel', # 0x39c
    'NtDCompositionReleaseAllResources', # 0x39d
    'NtDCompositionSubmitDWMBatch', # 0x39e
    'NtDCompositionCommitChannel', # 0x39f
    'NtDCompositionWaitForChannel', # 0x3a0
    'NtDCompositionSetChannelCommitCompletionEvent', # 0x3a1
    'NtDCompositionTelemetryTouchInteractionBegin', # 0x3a2
    'NtDCompositionTelemetryTouchInteractionUpdate', # 0x3a3
    'NtDCompositionTelemetryTouchInteractionEnd', # 0x3a4
    'NtDCompositionCurrentBatchId', # 0x3a5
    'NtDCompositionReleaseResource', # 0x3a6
    'NtDCompositionRemoveCrossDeviceVisualChild', # 0x3a7
    'NtDCompositionRemoveVisualChild', # 0x3a8
    'NtDCompositionAddCrossDeviceVisualChild', # 0x3a9
    'NtDCompositionAddVisualChild', # 0x3aa
    'NtDCompositionReplaceVisualChildren', # 0x3ab
    'NtDCompositionSetResourceAnimationProperty', # 0x3ac
    'NtDCompositionSetResourceReferenceArrayProperty', # 0x3ad
    'NtDCompositionSetResourceReferenceProperty', # 0x3ae
    'NtDCompositionSetResourceBufferProperty', # 0x3af
    'NtDCompositionSetResourceIntegerProperty', # 0x3b0
    'NtDCompositionSetResourceFloatProperty', # 0x3b1
    'NtDCompositionCreateResource', # 0x3b2
    'NtDCompositionCreateDwmChannel', # 0x3b3
    'NtDCompositionCreateChannel', # 0x3b4
    'NtDCompositionSynchronize', # 0x3b5
    'NtDCompositionDwmSyncFlush', # 0x3b6
    'NtDCompositionValidateAndReferenceSystemVisualForHwndTarget', # 0x3b7
    'NtDCompositionSignalGpuFence', # 0x3b8
    'NtDCompositionGetChannels', # 0x3b9
    'NtDCompositionConnectPipe', # 0x3ba
    'NtUserDestroyDCompositionHwndTarget', # 0x3bb
    'NtUserCreateDCompositionHwndTarget', # 0x3bc
    'NtUserWaitForRedirectionStartComplete', # 0x3bd
    'NtUserSignalRedirectionStartComplete', # 0x3be
    'NtUserSetActiveProcess', # 0x3bf
    'NtUserGetDisplayAutoRotationPreferencesByProcessId', # 0x3c0
    'NtUserGetDisplayAutoRotationPreferences', # 0x3c1
    'NtUserSetDisplayAutoRotationPreferences', # 0x3c2
    'NtUserSetAutoRotation', # 0x3c3
    'NtUserGetAutoRotationState', # 0x3c4
    'NtUserAutoRotateScreen', # 0x3c5
    'NtUserSetSensorPresence', # 0x3c6
    'NtUserAcquireIAMKey', # 0x3c7
    'NtUserSetFallbackForeground', # 0x3c8
    'NtUserSetBrokeredForeground', # 0x3c9
    'NtUserDisableImmersiveOwner', # 0x3ca
    'NtUserEnableIAMAccess', # 0x3cb
    'NtUserGetProcessUIContextInformation', # 0x3cc
    'NtUserSetProcessRestrictionExemption', # 0x3cd
    'NtUserEnableMouseInPointer', # 0x3ce
    'NtUserIsMouseInPointerEnabled', # 0x3cf
    'NtUserPromoteMouseInPointer', # 0x3d0
    'NtUserAutoPromoteMouseInPointer', # 0x3d1
    'NtUserEnableMouseInputForCursorSuppression', # 0x3d2
    'NtUserIsMouseInputEnabled', # 0x3d3
    'NtUserInternalClipCursor', # 0x3d4
    'NtUserCheckProcessForClipboardAccess', # 0x3d5
    'NtUserGetClipboardAccessToken', # 0x3d6
    'NtUserGetQueueEventStatus', # 0x3d7
    ],
]
