syscalls = [
    [
    'NtWorkerFactoryWorkerReady', # 0x0
    'NtAcceptConnectPort', # 0x1
    'NtYieldExecution', # 0x2
    'NtWriteVirtualMemory', # 0x3
    'NtWriteRequestData', # 0x4
    'NtWriteFileGather', # 0x5
    'NtWriteFile', # 0x6
    'NtWaitLowEventPair', # 0x7
    'NtWaitHighEventPair', # 0x8
    'NtWaitForWorkViaWorkerFactory', # 0x9
    'NtWaitForSingleObject', # 0xa
    'NtWaitForMultipleObjects32', # 0xb
    'NtWaitForMultipleObjects', # 0xc
    'NtWaitForKeyedEvent', # 0xd
    'NtWaitForDebugEvent', # 0xe
    'NtWaitForAlertByThreadId', # 0xf
    'NtVdmControl', # 0x10
    'NtUnsubscribeWnfStateChange', # 0x11
    'NtUpdateWnfStateData', # 0x12
    'NtUnmapViewOfSection', # 0x13
    'NtUnmapViewOfSectionEx', # 0x14
    'NtUnlockVirtualMemory', # 0x15
    'NtUnlockFile', # 0x16
    'NtUnloadKeyEx', # 0x17
    'NtUnloadKey2', # 0x18
    'NtUnloadKey', # 0x19
    'NtUnloadDriver', # 0x1a
    'NtUmsThreadYield', # 0x1b
    'NtTranslateFilePath', # 0x1c
    'NtTraceEvent', # 0x1d
    'NtTraceControl', # 0x1e
    'NtThawTransactions', # 0x1f
    'NtThawRegistry', # 0x20
    'NtTestAlert', # 0x21
    'NtTerminateThread', # 0x22
    'NtTerminateProcess', # 0x23
    'NtTerminateJobObject', # 0x24
    'NtSystemDebugControl', # 0x25
    'NtSuspendThread', # 0x26
    'NtSuspendProcess', # 0x27
    'NtSubscribeWnfStateChange', # 0x28
    'NtStopProfile', # 0x29
    'NtStartProfile', # 0x2a
    'NtSinglePhaseReject', # 0x2b
    'NtSignalAndWaitForSingleObject', # 0x2c
    'NtShutdownWorkerFactory', # 0x2d
    'NtShutdownSystem', # 0x2e
    'NtSetWnfProcessNotificationEvent', # 0x2f
    'NtSetVolumeInformationFile', # 0x30
    'NtSetValueKey', # 0x31
    'NtSetUuidSeed', # 0x32
    'NtSetTimerResolution', # 0x33
    'NtSetTimerEx', # 0x34
    'NtSetTimer', # 0x35
    'NtSetThreadExecutionState', # 0x36
    'NtSetSystemTime', # 0x37
    'NtSetSystemPowerState', # 0x38
    'NtSetSystemInformation', # 0x39
    'NtSetSystemEnvironmentValueEx', # 0x3a
    'NtSetSystemEnvironmentValue', # 0x3b
    'NtSetSecurityObject', # 0x3c
    'NtSetQuotaInformationFile', # 0x3d
    'NtSetLowWaitHighEventPair', # 0x3e
    'NtSetLowEventPair', # 0x3f
    'NtSetLdtEntries', # 0x40
    'NtSetIRTimer', # 0x41
    'NtSetTimer2', # 0x42
    'NtCancelTimer2', # 0x43
    'NtSetIoCompletionEx', # 0x44
    'NtSetIoCompletion', # 0x45
    'NtSetIntervalProfile', # 0x46
    'NtSetInformationWorkerFactory', # 0x47
    'NtSetInformationTransactionManager', # 0x48
    'NtSetInformationTransaction', # 0x49
    'NtSetInformationToken', # 0x4a
    'NtSetInformationThread', # 0x4b
    'NtSetInformationResourceManager', # 0x4c
    'NtSetInformationProcess', # 0x4d
    'NtSetInformationObject', # 0x4e
    'NtSetInformationKey', # 0x4f
    'NtSetInformationJobObject', # 0x50
    'NtSetInformationFile', # 0x51
    'NtSetInformationEnlistment', # 0x52
    'NtSetInformationDebugObject', # 0x53
    'NtSetHighWaitLowEventPair', # 0x54
    'NtSetHighEventPair', # 0x55
    'NtSetEventBoostPriority', # 0x56
    'NtSetEvent', # 0x57
    'NtSetEaFile', # 0x58
    'NtSetDriverEntryOrder', # 0x59
    'NtSetDefaultUILanguage', # 0x5a
    'NtSetDefaultLocale', # 0x5b
    'NtSetDefaultHardErrorPort', # 0x5c
    'NtSetDebugFilterState', # 0x5d
    'NtSetContextThread', # 0x5e
    'NtSetCachedSigningLevel', # 0x5f
    'NtSetBootOptions', # 0x60
    'NtSetBootEntryOrder', # 0x61
    'NtSerializeBoot', # 0x62
    'NtSecureConnectPort', # 0x63
    'NtSaveMergedKeys', # 0x64
    'NtSaveKeyEx', # 0x65
    'NtSaveKey', # 0x66
    'NtRollforwardTransactionManager', # 0x67
    'NtRollbackTransaction', # 0x68
    'NtRollbackEnlistment', # 0x69
    'NtRollbackComplete', # 0x6a
    'NtResumeThread', # 0x6b
    'NtResumeProcess', # 0x6c
    'NtRestoreKey', # 0x6d
    'NtResetWriteWatch', # 0x6e
    'NtResetEvent', # 0x6f
    'NtRequestWaitReplyPort', # 0x70
    'NtRequestPort', # 0x71
    'NtReplyWaitReplyPort', # 0x72
    'NtReplyWaitReceivePortEx', # 0x73
    'NtReplyWaitReceivePort', # 0x74
    'NtReplyPort', # 0x75
    'NtReplacePartitionUnit', # 0x76
    'NtReplaceKey', # 0x77
    'NtRenameTransactionManager', # 0x78
    'NtRenameKey', # 0x79
    'NtRemoveProcessDebug', # 0x7a
    'NtRemoveIoCompletionEx', # 0x7b
    'NtRemoveIoCompletion', # 0x7c
    'NtReleaseWorkerFactoryWorker', # 0x7d
    'NtReleaseSemaphore', # 0x7e
    'NtReleaseMutant', # 0x7f
    'NtReleaseKeyedEvent', # 0x80
    'NtRegisterThreadTerminatePort', # 0x81
    'NtRegisterProtocolAddressInformation', # 0x82
    'NtRecoverTransactionManager', # 0x83
    'NtRecoverResourceManager', # 0x84
    'NtRecoverEnlistment', # 0x85
    'NtReadVirtualMemory', # 0x86
    'NtReadRequestData', # 0x87
    'NtReadOnlyEnlistment', # 0x88
    'NtReadFileScatter', # 0x89
    'NtReadFile', # 0x8a
    'NtRaiseHardError', # 0x8b
    'NtRaiseException', # 0x8c
    'NtQueueApcThreadEx', # 0x8d
    'NtQueueApcThread', # 0x8e
    'NtQueryWnfStateData', # 0x8f
    'NtQueryWnfStateNameInformation', # 0x90
    'NtQueryVolumeInformationFile', # 0x91
    'NtQueryVirtualMemory', # 0x92
    'NtQueryValueKey', # 0x93
    'NtQueryTimerResolution', # 0x94
    'NtQueryTimer', # 0x95
    'NtQuerySystemTime', # 0x96
    'NtQuerySystemInformationEx', # 0x97
    'NtQuerySystemInformation', # 0x98
    'NtQuerySystemEnvironmentValueEx', # 0x99
    'NtQuerySystemEnvironmentValue', # 0x9a
    'NtQuerySymbolicLinkObject', # 0x9b
    'NtQuerySemaphore', # 0x9c
    'NtQuerySecurityObject', # 0x9d
    'NtQuerySecurityAttributesToken', # 0x9e
    'NtQuerySection', # 0x9f
    'NtQueryQuotaInformationFile', # 0xa0
    'NtQueryPortInformationProcess', # 0xa1
    'NtQueryPerformanceCounter', # 0xa2
    'NtQueryOpenSubKeysEx', # 0xa3
    'NtQueryOpenSubKeys', # 0xa4
    'NtQueryObject', # 0xa5
    'NtQueryMutant', # 0xa6
    'NtQueryMultipleValueKey', # 0xa7
    'NtQueryLicenseValue', # 0xa8
    'NtQueryKey', # 0xa9
    'NtQueryIoCompletion', # 0xaa
    'NtQueryIntervalProfile', # 0xab
    'NtQueryInstallUILanguage', # 0xac
    'NtQueryInformationWorkerFactory', # 0xad
    'NtQueryInformationTransactionManager', # 0xae
    'NtQueryInformationTransaction', # 0xaf
    'NtQueryInformationToken', # 0xb0
    'NtQueryInformationThread', # 0xb1
    'NtQueryInformationResourceManager', # 0xb2
    'NtQueryInformationProcess', # 0xb3
    'NtQueryInformationPort', # 0xb4
    'NtQueryInformationJobObject', # 0xb5
    'NtQueryInformationFile', # 0xb6
    'NtQueryInformationEnlistment', # 0xb7
    'NtQueryInformationAtom', # 0xb8
    'NtQueryFullAttributesFile', # 0xb9
    'NtQueryEvent', # 0xba
    'NtQueryEaFile', # 0xbb
    'NtQueryDriverEntryOrder', # 0xbc
    'NtQueryDirectoryObject', # 0xbd
    'NtQueryDirectoryFile', # 0xbe
    'NtQueryDefaultUILanguage', # 0xbf
    'NtQueryDefaultLocale', # 0xc0
    'NtQueryDebugFilterState', # 0xc1
    'NtQueryBootOptions', # 0xc2
    'NtQueryBootEntryOrder', # 0xc3
    'NtQueryAttributesFile', # 0xc4
    'NtPulseEvent', # 0xc5
    'NtProtectVirtualMemory', # 0xc6
    'NtPropagationFailed', # 0xc7
    'NtPropagationComplete', # 0xc8
    'NtPrivilegeObjectAuditAlarm', # 0xc9
    'NtPrivilegedServiceAuditAlarm', # 0xca
    'NtPrivilegeCheck', # 0xcb
    'NtSetInformationVirtualMemory', # 0xcc
    'NtPrePrepareEnlistment', # 0xcd
    'NtPrePrepareComplete', # 0xce
    'NtPrepareEnlistment', # 0xcf
    'NtPrepareComplete', # 0xd0
    'NtPowerInformation', # 0xd1
    'NtPlugPlayControl', # 0xd2
    'NtOpenTransactionManager', # 0xd3
    'NtOpenTransaction', # 0xd4
    'NtOpenTimer', # 0xd5
    'NtOpenThreadTokenEx', # 0xd6
    'NtOpenThreadToken', # 0xd7
    'NtOpenThread', # 0xd8
    'NtOpenSymbolicLinkObject', # 0xd9
    'NtOpenSession', # 0xda
    'NtOpenSemaphore', # 0xdb
    'NtOpenSection', # 0xdc
    'NtOpenResourceManager', # 0xdd
    'NtOpenProcessTokenEx', # 0xde
    'NtOpenProcessToken', # 0xdf
    'NtOpenProcess', # 0xe0
    'NtOpenPrivateNamespace', # 0xe1
    'NtOpenObjectAuditAlarm', # 0xe2
    'NtOpenMutant', # 0xe3
    'NtOpenKeyTransactedEx', # 0xe4
    'NtOpenKeyTransacted', # 0xe5
    'NtOpenKeyEx', # 0xe6
    'NtOpenKeyedEvent', # 0xe7
    'NtOpenKey', # 0xe8
    'NtOpenJobObject', # 0xe9
    'NtOpenIoCompletion', # 0xea
    'NtOpenFile', # 0xeb
    'NtOpenEventPair', # 0xec
    'NtOpenEvent', # 0xed
    'NtOpenEnlistment', # 0xee
    'NtOpenDirectoryObject', # 0xef
    'NtNotifyChangeSession', # 0xf0
    'NtNotifyChangeMultipleKeys', # 0xf1
    'NtNotifyChangeKey', # 0xf2
    'NtNotifyChangeDirectoryFile', # 0xf3
    'NtModifyDriverEntry', # 0xf4
    'NtModifyBootEntry', # 0xf5
    'NtMapViewOfSection', # 0xf6
    'NtMapUserPhysicalPagesScatter', # 0xf7
    'NtMapUserPhysicalPages', # 0xf8
    'NtMapCMFModule', # 0xf9
    'NtMakeTemporaryObject', # 0xfa
    'NtMakePermanentObject', # 0xfb
    'NtLockVirtualMemory', # 0xfc
    'NtLockRegistryKey', # 0xfd
    'NtLockProductActivationKeys', # 0xfe
    'NtLockFile', # 0xff
    'NtLoadKeyEx', # 0x100
    'NtLoadKey2', # 0x101
    'NtLoadKey', # 0x102
    'NtLoadDriver', # 0x103
    'NtListenPort', # 0x104
    'NtIsUILanguageComitted', # 0x105
    'NtIsSystemResumeAutomatic', # 0x106
    'NtIsProcessInJob', # 0x107
    'NtInitiatePowerAction', # 0x108
    'NtInitializeRegistry', # 0x109
    'NtInitializeNlsFiles', # 0x10a
    'NtImpersonateThread', # 0x10b
    'NtImpersonateClientOfPort', # 0x10c
    'NtImpersonateAnonymousToken', # 0x10d
    'NtGetWriteWatch', # 0x10e
    'NtGetNotificationResourceManager', # 0x10f
    'NtGetNlsSectionPtr', # 0x110
    'NtGetNextThread', # 0x111
    'NtGetNextProcess', # 0x112
    'NtGetMUIRegistryInfo', # 0x113
    'NtGetDevicePowerState', # 0x114
    'NtGetCurrentProcessorNumber', # 0x115
    'NtGetContextThread', # 0x116
    'NtGetCompleteWnfStateSubscription', # 0x117
    'NtGetCachedSigningLevel', # 0x118
    'NtFsControlFile', # 0x119
    'NtFreezeTransactions', # 0x11a
    'NtFreezeRegistry', # 0x11b
    'NtFreeVirtualMemory', # 0x11c
    'NtFreeUserPhysicalPages', # 0x11d
    'NtFlushWriteBuffer', # 0x11e
    'NtFlushVirtualMemory', # 0x11f
    'NtFlushProcessWriteBuffers', # 0x120
    'NtFlushKey', # 0x121
    'NtFlushInstructionCache', # 0x122
    'NtFlushInstallUILanguage', # 0x123
    'NtFlushBuffersFile', # 0x124
    'NtFlushBuffersFileEx', # 0x125
    'NtFindAtom', # 0x126
    'NtFilterToken', # 0x127
    'NtFilterTokenEx', # 0x128
    'NtFilterBootOption', # 0x129
    'NtExtendSection', # 0x12a
    'NtEnumerateValueKey', # 0x12b
    'NtEnumerateTransactionObject', # 0x12c
    'NtEnumerateSystemEnvironmentValuesEx', # 0x12d
    'NtEnumerateKey', # 0x12e
    'NtEnumerateDriverEntries', # 0x12f
    'NtEnumerateBootEntries', # 0x130
    'NtEnableLastKnownGood', # 0x131
    'NtDuplicateToken', # 0x132
    'NtDuplicateObject', # 0x133
    'NtDrawText', # 0x134
    'NtDisplayString', # 0x135
    'NtDisableLastKnownGood', # 0x136
    'NtDeviceIoControlFile', # 0x137
    'NtDeleteWnfStateName', # 0x138
    'NtDeleteWnfStateData', # 0x139
    'NtDeleteValueKey', # 0x13a
    'NtDeletePrivateNamespace', # 0x13b
    'NtDeleteObjectAuditAlarm', # 0x13c
    'NtDeleteKey', # 0x13d
    'NtDeleteFile', # 0x13e
    'NtDeleteDriverEntry', # 0x13f
    'NtDeleteBootEntry', # 0x140
    'NtDeleteAtom', # 0x141
    'NtDelayExecution', # 0x142
    'NtDebugContinue', # 0x143
    'NtDebugActiveProcess', # 0x144
    'NtCreateWorkerFactory', # 0x145
    'NtCreateWnfStateName', # 0x146
    'NtCreateWaitCompletionPacket', # 0x147
    'NtCreateWaitablePort', # 0x148
    'NtCreateUserProcess', # 0x149
    'NtCreateTransactionManager', # 0x14a
    'NtCreateTransaction', # 0x14b
    'NtCreateToken', # 0x14c
    'NtCreateLowBoxToken', # 0x14d
    'NtCreateTokenEx', # 0x14e
    'NtCreateTimer', # 0x14f
    'NtCreateThreadEx', # 0x150
    'NtCreateThread', # 0x151
    'NtCreateSymbolicLinkObject', # 0x152
    'NtCreateSemaphore', # 0x153
    'NtCreateSection', # 0x154
    'NtCreateResourceManager', # 0x155
    'NtCreateProfileEx', # 0x156
    'NtCreateProfile', # 0x157
    'NtCreateProcessEx', # 0x158
    'NtCreateProcess', # 0x159
    'NtCreatePrivateNamespace', # 0x15a
    'NtCreatePort', # 0x15b
    'NtCreatePagingFile', # 0x15c
    'NtCreateNamedPipeFile', # 0x15d
    'NtCreateMutant', # 0x15e
    'NtCreateMailslotFile', # 0x15f
    'NtCreateKeyTransacted', # 0x160
    'NtCreateKeyedEvent', # 0x161
    'NtCreateKey', # 0x162
    'NtCreateJobSet', # 0x163
    'NtCreateJobObject', # 0x164
    'NtCreateIRTimer', # 0x165
    'NtCreateTimer2', # 0x166
    'NtCreateIoCompletion', # 0x167
    'NtCreateFile', # 0x168
    'NtCreateEventPair', # 0x169
    'NtCreateEvent', # 0x16a
    'NtCreateEnlistment', # 0x16b
    'NtCreateDirectoryObjectEx', # 0x16c
    'NtCreateDirectoryObject', # 0x16d
    'NtCreateDebugObject', # 0x16e
    'NtContinue', # 0x16f
    'NtConnectPort', # 0x170
    'NtCompressKey', # 0x171
    'NtCompleteConnectPort', # 0x172
    'NtCompareTokens', # 0x173
    'NtCompactKeys', # 0x174
    'NtCommitTransaction', # 0x175
    'NtCommitEnlistment', # 0x176
    'NtCommitComplete', # 0x177
    'NtCloseObjectAuditAlarm', # 0x178
    'NtClose', # 0x179
    'NtClearEvent', # 0x17a
    'NtCancelWaitCompletionPacket', # 0x17b
    'NtCancelTimer', # 0x17c
    'NtCancelSynchronousIoFile', # 0x17d
    'NtCancelIoFileEx', # 0x17e
    'NtCancelIoFile', # 0x17f
    'NtCallbackReturn', # 0x180
    'NtAssociateWaitCompletionPacket', # 0x181
    'NtAssignProcessToJobObject', # 0x182
    'NtAreMappedFilesTheSame', # 0x183
    'NtApphelpCacheControl', # 0x184
    'NtAlpcSetInformation', # 0x185
    'NtAlpcSendWaitReceivePort', # 0x186
    'NtAlpcRevokeSecurityContext', # 0x187
    'NtAlpcQueryInformationMessage', # 0x188
    'NtAlpcQueryInformation', # 0x189
    'NtAlpcOpenSenderThread', # 0x18a
    'NtAlpcOpenSenderProcess', # 0x18b
    'NtAlpcImpersonateClientOfPort', # 0x18c
    'NtAlpcDisconnectPort', # 0x18d
    'NtAlpcDeleteSecurityContext', # 0x18e
    'NtAlpcDeleteSectionView', # 0x18f
    'NtAlpcDeleteResourceReserve', # 0x190
    'NtAlpcDeletePortSection', # 0x191
    'NtAlpcCreateSecurityContext', # 0x192
    'NtAlpcCreateSectionView', # 0x193
    'NtAlpcCreateResourceReserve', # 0x194
    'NtAlpcCreatePortSection', # 0x195
    'NtAlpcCreatePort', # 0x196
    'NtAlpcConnectPort', # 0x197
    'NtAlpcConnectPortEx', # 0x198
    'NtAlpcCancelMessage', # 0x199
    'NtAlpcAcceptConnectPort', # 0x19a
    'NtAllocateVirtualMemory', # 0x19b
    'NtAllocateUuids', # 0x19c
    'NtAllocateUserPhysicalPages', # 0x19d
    'NtAllocateReserveObject', # 0x19e
    'NtAllocateLocallyUniqueId', # 0x19f
    'NtAlertThreadByThreadId', # 0x1a0
    'NtAlertThread', # 0x1a1
    'NtAlertResumeThread', # 0x1a2
    'NtAdjustPrivilegesToken', # 0x1a3
    'NtAdjustGroupsToken', # 0x1a4
    'NtAdjustTokenClaimsAndDeviceGroups', # 0x1a5
    'NtAddDriverEntry', # 0x1a6
    'NtAddBootEntry', # 0x1a7
    'NtAddAtom', # 0x1a8
    'NtAddAtomEx', # 0x1a9
    'NtAccessCheckByTypeResultListAndAuditAlarmByHandle', # 0x1aa
    'NtAccessCheckByTypeResultListAndAuditAlarm', # 0x1ab
    'NtAccessCheckByTypeResultList', # 0x1ac
    'NtAccessCheckByTypeAndAuditAlarm', # 0x1ad
    'NtAccessCheckByType', # 0x1ae
    'NtAccessCheckAndAuditAlarm', # 0x1af
    'NtAccessCheck', # 0x1b0
    ],
    [
    'NtUserYieldTask', # 0x0
    'NtUserSetSensorPresence', # 0x1
    'NtGdiWidenPath', # 0x2
    'NtGdiUpdateColors', # 0x3
    'NtGdiUnrealizeObject', # 0x4
    'NtGdiUnmapMemFont', # 0x5
    'NtGdiUnloadPrinterDriver', # 0x6
    'NtGdiTransparentBlt', # 0x7
    'NtGdiTransformPoints', # 0x8
    'NtGdiSwapBuffers', # 0x9
    'NtGdiStrokePath', # 0xa
    'NtGdiStrokeAndFillPath', # 0xb
    'NtGdiStretchDIBitsInternal', # 0xc
    'NtGdiStretchBlt', # 0xd
    'NtGdiStartPage', # 0xe
    'NtGdiStartDoc', # 0xf
    'NtGdiSetSizeDevice', # 0x10
    'NtGdiSetVirtualResolution', # 0x11
    'NtGdiSetTextJustification', # 0x12
    'NtGdiSetSystemPaletteUse', # 0x13
    'NtGdiSetRectRgn', # 0x14
    'NtGdiSetPixelFormat', # 0x15
    'NtGdiSetPixel', # 0x16
    'NtGdiSetOPMSigningKeyAndSequenceNumbers', # 0x17
    'NtGdiSetLayout', # 0x18
    'NtGdiMirrorWindowOrg', # 0x19
    'NtGdiGetDeviceWidth', # 0x1a
    'NtGdiSetMiterLimit', # 0x1b
    'NtGdiSetMetaRgn', # 0x1c
    'NtGdiSetMagicColors', # 0x1d
    'NtGdiSetLinkedUFIs', # 0x1e
    'NtGdiSetIcmMode', # 0x1f
    'NtGdiSetFontXform', # 0x20
    'NtGdiSetFontEnumeration', # 0x21
    'NtGdiSetDIBitsToDeviceInternal', # 0x22
    'NtGdiSetDeviceGammaRamp', # 0x23
    'NtGdiSetColorSpace', # 0x24
    'NtGdiSetColorAdjustment', # 0x25
    'NtGdiSetBrushOrg', # 0x26
    'NtGdiSetBrushAttributes', # 0x27
    'NtGdiSetBoundsRect', # 0x28
    'NtGdiSetBitmapDimension', # 0x29
    'NtGdiSetBitmapBits', # 0x2a
    'NtGdiSetBitmapAttributes', # 0x2b
    'NtGdiSelectPen', # 0x2c
    'NtGdiSelectFont', # 0x2d
    'NtGdiSelectClipPath', # 0x2e
    'NtGdiSelectBrush', # 0x2f
    'NtGdiSelectBitmap', # 0x30
    'NtGdiScaleWindowExtEx', # 0x31
    'NtGdiScaleViewportExtEx', # 0x32
    'NtGdiSaveDC', # 0x33
    'NtGdiRoundRect', # 0x34
    'NtGdiRestoreDC', # 0x35
    'NtGdiResizePalette', # 0x36
    'NtGdiResetDC', # 0x37
    'NtGdiRemoveFontMemResourceEx', # 0x38
    'NtGdiRemoveFontResourceW', # 0x39
    'NtGdiRectVisible', # 0x3a
    'NtGdiRectInRegion', # 0x3b
    'NtGdiRectangle', # 0x3c
    'NtGdiQueryFontAssocInfo', # 0x3d
    'NtGdiQueryFonts', # 0x3e
    'NtGdiPtVisible', # 0x3f
    'NtGdiPtInRegion', # 0x40
    'NtGdiPolyTextOutW', # 0x41
    'NtGdiPolyPolyDraw', # 0x42
    'NtGdiPolyDraw', # 0x43
    'NtGdiPlgBlt', # 0x44
    'NtGdiPathToRegion', # 0x45
    'NtGdiPolyPatBlt', # 0x46
    'NtGdiPatBlt', # 0x47
    'NtGdiOpenDCW', # 0x48
    'NtGdiOffsetRgn', # 0x49
    'NtGdiOffsetClipRgn', # 0x4a
    'NtGdiMoveTo', # 0x4b
    'NtGdiMonoBitmap', # 0x4c
    'NtGdiModifyWorldTransform', # 0x4d
    'NtGdiMaskBlt', # 0x4e
    'NtGdiMakeInfoDC', # 0x4f
    'NtGdiMakeFontDir', # 0x50
    'NtGdiLineTo', # 0x51
    'NtGdiInvertRgn', # 0x52
    'NtGdiIntersectClipRect', # 0x53
    'NtGdiInitSpool', # 0x54
    'NtGdiInit', # 0x55
    'NtGdiIcmBrushInfo', # 0x56
    'NtGdiHfontCreate', # 0x57
    'NtGdiGradientFill', # 0x58
    'NtGdiGetWidthTable', # 0x59
    'NtGdiGetFontUnicodeRanges', # 0x5a
    'NtGdiAddEmbFontToDC', # 0x5b
    'NtGdiChangeGhostFont', # 0x5c
    'NtGdiGetEmbedFonts', # 0x5d
    'NtGdiGetUFIPathname', # 0x5e
    'NtGdiGetEmbUFI', # 0x5f
    'NtGdiGetUFI', # 0x60
    'NtGdiGetTransform', # 0x61
    'NtGdiGetTextMetricsW', # 0x62
    'NtGdiGetTextFaceW', # 0x63
    'NtGdiGetTextExtentExW', # 0x64
    'NtGdiGetTextExtent', # 0x65
    'NtGdiGetTextCharsetInfo', # 0x66
    'NtGdiGetSystemPaletteUse', # 0x67
    'NtGdiGetSuggestedOPMProtectedOutputArraySize', # 0x68
    'NtGdiGetStringBitmapW', # 0x69
    'NtGdiGetStockObject', # 0x6a
    'NtGdiGetStats', # 0x6b
    'NtGdiGetSpoolMessage', # 0x6c
    'NtGdiGetServerMetaFileBits', # 0x6d
    'NtGdiGetRgnBox', # 0x6e
    'NtGdiGetRegionData', # 0x6f
    'NtGdiGetRealizationInfo', # 0x70
    'NtGdiGetRasterizerCaps', # 0x71
    'NtGdiGetRandomRgn', # 0x72
    'NtGdiGetPixel', # 0x73
    'NtGdiGetPath', # 0x74
    'NtGdiGetOutlineTextMetricsInternalW', # 0x75
    'NtGdiGetOPMRandomNumber', # 0x76
    'NtGdiGetObjectBitmapHandle', # 0x77
    'NtGdiGetNearestPaletteIndex', # 0x78
    'NtGdiGetNearestColor', # 0x79
    'NtGdiGetMonitorID', # 0x7a
    'NtGdiGetMiterLimit', # 0x7b
    'NtGdiGetLinkedUFIs', # 0x7c
    'NtGdiGetKerningPairs', # 0x7d
    'NtGdiGetOPMInformation', # 0x7e
    'NtGdiGetGlyphOutline', # 0x7f
    'NtGdiGetGlyphIndicesWInternal', # 0x80
    'NtGdiGetGlyphIndicesW', # 0x81
    'NtGdiGetFontResourceInfoInternalW', # 0x82
    'NtGdiGetFontFileInfo', # 0x83
    'NtGdiGetFontFileData', # 0x84
    'NtGdiGetFontData', # 0x85
    'NtGdiGetEudcTimeStampEx', # 0x86
    'NtGdiGetETM', # 0x87
    'NtGdiGetDIBitsInternal', # 0x88
    'NtGdiGetDeviceCapsAll', # 0x89
    'NtGdiGetDeviceGammaRamp', # 0x8a
    'NtGdiGetDeviceCaps', # 0x8b
    'NtGdiGetDCPoint', # 0x8c
    'NtGdiGetDCObject', # 0x8d
    'NtGdiGetDCforBitmap', # 0x8e
    'NtGdiGetDCDword', # 0x8f
    'NtGdiGetCurrentDpiInfo', # 0x90
    'NtGdiGetCOPPCompatibleOPMInformation', # 0x91
    'NtGdiGetColorSpaceforBitmap', # 0x92
    'NtGdiGetColorAdjustment', # 0x93
    'NtGdiGetCharWidthInfo', # 0x94
    'NtGdiGetCharWidthW', # 0x95
    'NtGdiGetCharSet', # 0x96
    'NtGdiGetCharacterPlacementW', # 0x97
    'NtGdiGetCharABCWidthsW', # 0x98
    'NtGdiGetCertificateSize', # 0x99
    'NtGdiGetCertificate', # 0x9a
    'NtGdiGetBoundsRect', # 0x9b
    'NtGdiGetBitmapDimension', # 0x9c
    'NtGdiGetBitmapBits', # 0x9d
    'NtGdiGetAppClipBox', # 0x9e
    'NtGdiGetAndSetDCDword', # 0x9f
    'NtGdiFullscreenControl', # 0xa0
    'NtGdiFrameRgn', # 0xa1
    'NtGdiForceUFIMapping', # 0xa2
    'NtGdiFlush', # 0xa3
    'NtGdiFlattenPath', # 0xa4
    'NtGdiFillRgn', # 0xa5
    'NtGdiFillPath', # 0xa6
    'NtGdiExtTextOutW', # 0xa7
    'NtGdiExtSelectClipRgn', # 0xa8
    'NtGdiExtGetObjectW', # 0xa9
    'NtGdiExtFloodFill', # 0xaa
    'NtGdiExtEscape', # 0xab
    'NtGdiExtCreateRegion', # 0xac
    'NtGdiExtCreatePen', # 0xad
    'NtGdiExcludeClipRect', # 0xae
    'NtGdiEudcLoadUnloadLink', # 0xaf
    'NtGdiEqualRgn', # 0xb0
    'NtGdiEnumObjects', # 0xb1
    'NtGdiEnumFonts', # 0xb2
    'NtGdiEndPath', # 0xb3
    'NtGdiEndPage', # 0xb4
    'NtGdiEndGdiRendering', # 0xb5
    'NtGdiEndDoc', # 0xb6
    'NtGdiEnableEudc', # 0xb7
    'NtGdiEllipse', # 0xb8
    'NtGdiDrawEscape', # 0xb9
    'NtGdiDoPalette', # 0xba
    'NtGdiDoBanding', # 0xbb
    'NtGdiGetPerBandInfo', # 0xbc
    'NtGdiDestroyOPMProtectedOutput', # 0xbd
    'NtGdiDescribePixelFormat', # 0xbe
    'NtGdiDeleteObjectApp', # 0xbf
    'NtGdiDeleteColorTransform', # 0xc0
    'NtGdiDeleteColorSpace', # 0xc1
    'NtGdiDeleteClientObj', # 0xc2
    'NtGdiDxgGenericThunk', # 0xc3
    'NtGdiDvpReleaseNotification', # 0xc4
    'NtGdiDvpAcquireNotification', # 0xc5
    'NtGdiDvpWaitForVideoPortSync', # 0xc6
    'NtGdiDvpUpdateVideoPort', # 0xc7
    'NtGdiDvpGetVideoSignalStatus', # 0xc8
    'NtGdiDvpGetVideoPortConnectInfo', # 0xc9
    'NtGdiDvpGetVideoPortOutputFormats', # 0xca
    'NtGdiDvpGetVideoPortLine', # 0xcb
    'NtGdiDvpGetVideoPortInputFormats', # 0xcc
    'NtGdiDvpGetVideoPortFlipStatus', # 0xcd
    'NtGdiDvpGetVideoPortField', # 0xce
    'NtGdiDvpGetVideoPortBandwidth', # 0xcf
    'NtGdiDvpFlipVideoPort', # 0xd0
    'NtGdiDvpDestroyVideoPort', # 0xd1
    'NtGdiDvpCreateVideoPort', # 0xd2
    'NtGdiDvpColorControl', # 0xd3
    'NtGdiDvpCanCreateVideoPort', # 0xd4
    'NtGdiDdWaitForVerticalBlank', # 0xd5
    'NtGdiDdUpdateOverlay', # 0xd6
    'NtGdiDdUnlockD3D', # 0xd7
    'NtGdiDdUnlock', # 0xd8
    'NtGdiDdUnattachSurface', # 0xd9
    'NtGdiDdSetOverlayPosition', # 0xda
    'NtGdiDdCreateSurfaceEx', # 0xdb
    'NtGdiDdSetGammaRamp', # 0xdc
    'NtGdiDdSetExclusiveMode', # 0xdd
    'NtGdiDdSetColorKey', # 0xde
    'NtGdiDdResetVisrgn', # 0xdf
    'NtGdiDdRenderMoComp', # 0xe0
    'NtGdiDdReleaseDC', # 0xe1
    'NtGdiDdReenableDirectDrawObject', # 0xe2
    'NtGdiDdQueryMoCompStatus', # 0xe3
    'NtGdiDdQueryDirectDrawObject', # 0xe4
    'NtGdiDdLockD3D', # 0xe5
    'NtGdiDdLock', # 0xe6
    'NtGdiDdGetScanLine', # 0xe7
    'NtGdiDdGetMoCompFormats', # 0xe8
    'NtGdiDdGetMoCompGuids', # 0xe9
    'NtGdiDdGetMoCompBuffInfo', # 0xea
    'NtGdiDdGetInternalMoCompInfo', # 0xeb
    'NtGdiDdGetFlipStatus', # 0xec
    'NtGdiDdGetDxHandle', # 0xed
    'NtGdiDdGetDriverInfo', # 0xee
    'NtGdiDdGetDC', # 0xef
    'NtGdiDdGetBltStatus', # 0xf0
    'NtGdiDdGetAvailDriverMemory', # 0xf1
    'NtGdiDdFlipToGDISurface', # 0xf2
    'NtGdiDdFlip', # 0xf3
    'NtGdiDdEndMoCompFrame', # 0xf4
    'NtGdiDdDestroyD3DBuffer', # 0xf5
    'NtGdiDdDestroySurface', # 0xf6
    'NtGdiDdDestroyMoComp', # 0xf7
    'NtGdiDdDeleteSurfaceObject', # 0xf8
    'NtGdiDdDeleteDirectDrawObject', # 0xf9
    'NtGdiDdCreateSurfaceObject', # 0xfa
    'NtGdiDdCreateMoComp', # 0xfb
    'NtGdiDdCreateD3DBuffer', # 0xfc
    'NtGdiDdCreateSurface', # 0xfd
    'NtGdiDdCreateDirectDrawObject', # 0xfe
    'NtGdiDdColorControl', # 0xff
    'NtGdiDdCanCreateD3DBuffer', # 0x100
    'NtGdiDdCanCreateSurface', # 0x101
    'NtGdiDdBlt', # 0x102
    'NtGdiDdBeginMoCompFrame', # 0x103
    'NtGdiDdAttachSurface', # 0x104
    'NtGdiDdAlphaBlt', # 0x105
    'NtGdiDdAddAttachedSurface', # 0x106
    'NtGdiDdGetDriverState', # 0x107
    'NtGdiD3dDrawPrimitives2', # 0x108
    'NtGdiD3dValidateTextureStageState', # 0x109
    'NtGdiD3dContextDestroyAll', # 0x10a
    'NtGdiD3dContextDestroy', # 0x10b
    'NtGdiD3dContextCreate', # 0x10c
    'NtGdiCreateSolidBrush', # 0x10d
    'NtGdiCreateServerMetaFile', # 0x10e
    'NtGdiCreateRoundRectRgn', # 0x10f
    'NtGdiCreateRectRgn', # 0x110
    'NtGdiCreatePen', # 0x111
    'NtGdiCreatePatternBrushInternal', # 0x112
    'NtGdiCreatePaletteInternal', # 0x113
    'NtGdiCreateOPMProtectedOutputs', # 0x114
    'NtGdiCreateMetafileDC', # 0x115
    'NtGdiCreateHatchBrushInternal', # 0x116
    'NtGdiCreateHalftonePalette', # 0x117
    'NtGdiCreateEllipticRgn', # 0x118
    'NtGdiCreateSessionMappedDIBSection', # 0x119
    'NtGdiCreateDIBSection', # 0x11a
    'NtGdiCreateDIBitmapInternal', # 0x11b
    'NtGdiCreateDIBBrush', # 0x11c
    'NtGdiCreateCompatibleDC', # 0x11d
    'NtGdiCreateCompatibleBitmap', # 0x11e
    'NtGdiCreateColorTransform', # 0x11f
    'NtGdiCreateColorSpace', # 0x120
    'NtGdiCreateClientObj', # 0x121
    'NtGdiCreateBitmapFromDxSurface2', # 0x122
    'NtGdiCreateBitmapFromDxSurface', # 0x123
    'NtGdiCreateBitmap', # 0x124
    'NtGdiConvertMetafileRect', # 0x125
    'NtGdiConfigureOPMProtectedOutput', # 0x126
    'NtGdiComputeXformCoefficients', # 0x127
    'NtGdiCombineTransform', # 0x128
    'NtGdiCombineRgn', # 0x129
    'NtGdiColorCorrectPalette', # 0x12a
    'NtGdiClearBrushAttributes', # 0x12b
    'NtGdiClearBitmapAttributes', # 0x12c
    'NtGdiCloseFigure', # 0x12d
    'NtGdiCheckBitmapBits', # 0x12e
    'NtGdiCancelDC', # 0x12f
    'NtGdiBitBlt', # 0x130
    'NtGdiBeginPath', # 0x131
    'NtGdiBeginGdiRendering', # 0x132
    'NtGdiArcInternal', # 0x133
    'NtGdiFontIsLinked', # 0x134
    'NtGdiAnyLinkedFonts', # 0x135
    'NtGdiAngleArc', # 0x136
    'NtGdiAlphaBlend', # 0x137
    'NtGdiAddRemoteMMInstanceToDC', # 0x138
    'NtGdiRemoveMergeFont', # 0x139
    'NtGdiAddFontMemResourceEx', # 0x13a
    'NtGdiAddRemoteFontToDC', # 0x13b
    'NtGdiAddFontResourceW', # 0x13c
    'NtGdiAbortPath', # 0x13d
    'NtGdiAbortDoc', # 0x13e
    'NtUserDefSetText', # 0x13f
    'NtUserDeferWindowPosAndBand', # 0x140
    'NtUserDdeInitialize', # 0x141
    'NtUserCanBrokerForceForeground', # 0x142
    'NtUserCreateWindowStation', # 0x143
    'NtUserCreateWindowEx', # 0x144
    'NtUserCreateLocalMemHandle', # 0x145
    'NtUserCreateInputContext', # 0x146
    'NtUserCreateDesktopEx', # 0x147
    'NtUserCreateCaret', # 0x148
    'NtUserCreateAcceleratorTable', # 0x149
    'NtUserCountClipboardFormats', # 0x14a
    'NtUserCopyAcceleratorTable', # 0x14b
    'NtUserConvertMemHandle', # 0x14c
    'NtUserConsoleControl', # 0x14d
    'NtUserCloseWindowStation', # 0x14e
    'NtUserCloseDesktop', # 0x14f
    'NtUserCloseClipboard', # 0x150
    'NtUserClipCursor', # 0x151
    'NtUserChildWindowFromPointEx', # 0x152
    'NtUserCheckMenuItem', # 0x153
    'NtUserCheckWindowThreadDesktop', # 0x154
    'NtUserDwmValidateWindow', # 0x155
    'NtUserCheckAccessForIntegrityLevel', # 0x156
    'NtUserDisplayConfigSetDeviceInfo', # 0x157
    'NtUserDisplayConfigGetDeviceInfo', # 0x158
    'NtUserQueryDisplayConfig', # 0x159
    'NtUserSetDisplayConfig', # 0x15a
    'NtUserGetDisplayConfigBufferSizes', # 0x15b
    'NtUserChangeDisplaySettings', # 0x15c
    'NtUserChangeClipboardChain', # 0x15d
    'NtUserCallTwoParam', # 0x15e
    'NtUserCallOneParam', # 0x15f
    'NtUserCallNoParam', # 0x160
    'NtUserCallNextHookEx', # 0x161
    'NtUserCallMsgFilter', # 0x162
    'NtUserCallHwndParamLock', # 0x163
    'NtUserCallHwndParam', # 0x164
    'NtUserCallHwndOpt', # 0x165
    'NtUserCallHwndLock', # 0x166
    'NtUserCallHwnd', # 0x167
    'NtUserBuildPropList', # 0x168
    'NtUserBuildNameList', # 0x169
    'NtUserBuildHwndList', # 0x16a
    'NtUserBuildHimcList', # 0x16b
    'NtUserBlockInput', # 0x16c
    'NtUserBitBltSysBmp', # 0x16d
    'NtUserBeginPaint', # 0x16e
    'NtUserAttachThreadInput', # 0x16f
    'NtUserAssociateInputContext', # 0x170
    'NtUserAlterWindowStyle', # 0x171
    'NtUserAddClipboardFormatListener', # 0x172
    'NtUserActivateKeyboardLayout', # 0x173
    'NtUserDelegateCapturePointers', # 0x174
    'NtUserDelegateInput', # 0x175
    'NtUserDispatchMessage', # 0x176
    'NtUserDisableProcessWindowFiltering', # 0x177
    'NtUserDisableThreadIme', # 0x178
    'NtUserDestroyWindow', # 0x179
    'NtUserDestroyMenu', # 0x17a
    'NtUserDestroyInputContext', # 0x17b
    'NtUserDestroyCursor', # 0x17c
    'NtUserDestroyAcceleratorTable', # 0x17d
    'NtUserDeleteMenu', # 0x17e
    'NtUserDoSoundDisconnect', # 0x17f
    'NtUserDoSoundConnect', # 0x180
    'NtUserGhostWindowFromHungWindow', # 0x181
    'NtUserGetWOWClass', # 0x182
    'NtUserGetWindowPlacement', # 0x183
    'NtUserGetWindowDisplayAffinity', # 0x184
    'NtUserGetWindowDC', # 0x185
    'NtUserGetWindowCompositionAttribute', # 0x186
    'NtUserGetWindowCompositionInfo', # 0x187
    'NtUserGetWindowBand', # 0x188
    'NtUserGetUpdateRgn', # 0x189
    'NtUserGetUpdateRect', # 0x18a
    'NtUserGetUpdatedClipboardFormats', # 0x18b
    'NtUserGetTopLevelWindow', # 0x18c
    'NtUserGetTitleBarInfo', # 0x18d
    'NtUserGetThreadState', # 0x18e
    'NtUserGetThreadDesktop', # 0x18f
    'NtUserGetSystemMenu', # 0x190
    'NtUserGetScrollBarInfo', # 0x191
    'NtUserGetRegisteredRawInputDevices', # 0x192
    'NtUserGetRawInputDeviceList', # 0x193
    'NtUserGetRawInputDeviceInfo', # 0x194
    'NtUserGetRawInputData', # 0x195
    'NtUserGetRawInputBuffer', # 0x196
    'NtUserGetProcessWindowStation', # 0x197
    'NtUserGetPriorityClipboardFormat', # 0x198
    'NtUserGetOpenClipboardWindow', # 0x199
    'NtUserGetObjectInformation', # 0x19a
    'NtUserGetMouseMovePointsEx', # 0x19b
    'NtUserGetMessage', # 0x19c
    'NtUserGetMenuItemRect', # 0x19d
    'NtUserGetMenuIndex', # 0x19e
    'NtUserGetMenuBarInfo', # 0x19f
    'NtUserGetListBoxInfo', # 0x1a0
    'NtUserGetKeyState', # 0x1a1
    'NtUserGetKeyNameText', # 0x1a2
    'NtUserGetKeyboardState', # 0x1a3
    'NtUserGetKeyboardLayoutName', # 0x1a4
    'NtUserGetKeyboardLayoutList', # 0x1a5
    'NtUserGetInternalWindowPos', # 0x1a6
    'NtUserGetInputLocaleInfo', # 0x1a7
    'NtUserGetImeInfoEx', # 0x1a8
    'NtUserGetImeHotKey', # 0x1a9
    'NtUserGetIconSize', # 0x1aa
    'NtUserGetIconInfo', # 0x1ab
    'NtUserGetGUIThreadInfo', # 0x1ac
    'NtUserGetGuiResources', # 0x1ad
    'NtUserGetForegroundWindow', # 0x1ae
    'NtUserGetDoubleClickTime', # 0x1af
    'NtUserGetDesktopID', # 0x1b0
    'NtUserGetDCEx', # 0x1b1
    'NtUserGetDC', # 0x1b2
    'NtUserGetCursorInfo', # 0x1b3
    'NtUserGetCursorFrameInfo', # 0x1b4
    'NtUserGetCurrentInputMessageSource', # 0x1b5
    'NtUserGetCIMSSM', # 0x1b6
    'NtUserGetCPD', # 0x1b7
    'NtUserGetControlColor', # 0x1b8
    'NtUserGetControlBrush', # 0x1b9
    'NtUserGetComboBoxInfo', # 0x1ba
    'NtUserGetClipCursor', # 0x1bb
    'NtUserGetClipboardViewer', # 0x1bc
    'NtUserGetClipboardSequenceNumber', # 0x1bd
    'NtUserGetClipboardOwner', # 0x1be
    'NtUserGetClipboardFormatName', # 0x1bf
    'NtUserGetClipboardData', # 0x1c0
    'NtUserGetClassName', # 0x1c1
    'NtUserGetClassInfoEx', # 0x1c2
    'NtUserGetCaretPos', # 0x1c3
    'NtUserGetCaretBlinkTime', # 0x1c4
    'NtUserGetAtomName', # 0x1c5
    'NtUserGetAsyncKeyState', # 0x1c6
    'NtUserGetAppImeLevel', # 0x1c7
    'NtUserGetAncestor', # 0x1c8
    'NtUserGetAltTabInfo', # 0x1c9
    'NtUserFrostCrashedWindow', # 0x1ca
    'NtUserFlashWindowEx', # 0x1cb
    'NtUserFindWindowEx', # 0x1cc
    'NtUserFindExistingCursorIcon', # 0x1cd
    'NtUserFillWindow', # 0x1ce
    'NtUserExcludeUpdateRgn', # 0x1cf
    'NtUserEvent', # 0x1d0
    'NtUserEnumDisplaySettings', # 0x1d1
    'NtUserEnumDisplayMonitors', # 0x1d2
    'NtUserEnumDisplayDevices', # 0x1d3
    'NtUserEndPaint', # 0x1d4
    'NtUserEndMenu', # 0x1d5
    'NtUserEndDeferWindowPosEx', # 0x1d6
    'NtUserEnableScrollBar', # 0x1d7
    'NtUserEnableMenuItem', # 0x1d8
    'NtUserEmptyClipboard', # 0x1d9
    'NtUserDrawMenuBarTemp', # 0x1da
    'NtUserDrawIconEx', # 0x1db
    'NtUserDrawCaptionTemp', # 0x1dc
    'NtUserDrawCaption', # 0x1dd
    'NtUserDrawAnimatedRects', # 0x1de
    'NtUserDragObject', # 0x1df
    'NtUserDragDetect', # 0x1e0
    'NtUserHandleDelegatedInput', # 0x1e1
    'NtUserRealChildWindowFromPoint', # 0x1e2
    'NtUserQueryWindow', # 0x1e3
    'NtUserQuerySendMessage', # 0x1e4
    'NtUserQueryInputContext', # 0x1e5
    'NtUserQueryInformationThread', # 0x1e6
    'NtUserQueryBSDRWindow', # 0x1e7
    'NtUserPerMonitorDPIPhysicalToLogicalPoint', # 0x1e8
    'NtUserProcessConnect', # 0x1e9
    'NtUserPrintWindow', # 0x1ea
    'NtUserPostThreadMessage', # 0x1eb
    'NtUserPostMessage', # 0x1ec
    'NtUserPhysicalToLogicalPoint', # 0x1ed
    'NtUserPeekMessage', # 0x1ee
    'NtUserPaintMonitor', # 0x1ef
    'NtUserPaintDesktop', # 0x1f0
    'NtUserOpenWindowStation', # 0x1f1
    'NtUserOpenThreadDesktop', # 0x1f2
    'NtUserOpenInputDesktop', # 0x1f3
    'NtUserOpenDesktop', # 0x1f4
    'NtUserOpenClipboard', # 0x1f5
    'NtUserNotifyWinEvent', # 0x1f6
    'NtUserNotifyProcessCreate', # 0x1f7
    'NtUserNotifyIMEStatus', # 0x1f8
    'NtUserMoveWindow', # 0x1f9
    'NtUserModifyUserStartupInfoFlags', # 0x1fa
    'NtUserMNDragOver', # 0x1fb
    'NtUserMNDragLeave', # 0x1fc
    'NtUserMinMaximize', # 0x1fd
    'NtUserMessageCall', # 0x1fe
    'NtUserMenuItemFromPoint', # 0x1ff
    'NtUserMapVirtualKeyEx', # 0x200
    'NtUserLayoutCompleted', # 0x201
    'NtUserLogicalToPerMonitorDPIPhysicalPoint', # 0x202
    'NtUserLogicalToPhysicalPoint', # 0x203
    'NtUserLockWorkStation', # 0x204
    'NtUserLockWindowUpdate', # 0x205
    'NtUserLockWindowStation', # 0x206
    'NtUserLoadKeyboardLayoutEx', # 0x207
    'NtUserKillTimer', # 0x208
    'NtUserIsTopLevelWindow', # 0x209
    'NtUserIsClipboardFormatAvailable', # 0x20a
    'NtUserInvalidateRgn', # 0x20b
    'NtUserInvalidateRect', # 0x20c
    'NtUserInternalGetWindowIcon', # 0x20d
    'NtUserInternalGetWindowText', # 0x20e
    'NtUserInitTask', # 0x20f
    'NtUserInitializeClientPfnArrays', # 0x210
    'NtUserInitialize', # 0x211
    'NtUserImpersonateDdeClientWindow', # 0x212
    'NtUserHungWindowFromGhostWindow', # 0x213
    'NtUserHiliteMenuItem', # 0x214
    'NtUserHideCaret', # 0x215
    'NtUserHardErrorControl', # 0x216
    'NtUserRealInternalGetMessage', # 0x217
    'NtUserRealWaitMessageEx', # 0x218
    'NtUserTranslateMessage', # 0x219
    'NtUserTranslateAccelerator', # 0x21a
    'NtUserPaintMenuBar', # 0x21b
    'NtUserCalcMenuBar', # 0x21c
    'NtUserCalculatePopupWindowPosition', # 0x21d
    'NtUserTrackPopupMenuEx', # 0x21e
    'NtUserTrackMouseEvent', # 0x21f
    'NtUserToUnicodeEx', # 0x220
    'NtUserThunkedMenuItemInfo', # 0x221
    'NtUserThunkedMenuInfo', # 0x222
    'NtUserTestForInteractiveUser', # 0x223
    'NtUserSendEventMessage', # 0x224
    'NtUserSystemParametersInfo', # 0x225
    'NtUserSwitchDesktop', # 0x226
    'NtUserSoundSentry', # 0x227
    'NtUserShutdownReasonDestroy', # 0x228
    'NtUserShutdownBlockReasonQuery', # 0x229
    'NtUserShutdownBlockReasonCreate', # 0x22a
    'NtUserShowWindowAsync', # 0x22b
    'NtUserShowWindow', # 0x22c
    'NtUserShowScrollBar', # 0x22d
    'NtUserShowCaret', # 0x22e
    'NtUserSetWinEventHook', # 0x22f
    'NtUserSetWindowWord', # 0x230
    'NtUserSetWindowStationUser', # 0x231
    'NtUserSetWindowsHookEx', # 0x232
    'NtUserSetWindowsHookAW', # 0x233
    'NtUserSetWindowRgnEx', # 0x234
    'NtUserGetWindowRgnEx', # 0x235
    'NtUserSetWindowRgn', # 0x236
    'NtUserSetWindowPos', # 0x237
    'NtUserSetWindowPlacement', # 0x238
    'NtUserSetWindowLong', # 0x239
    'NtUserSetWindowFNID', # 0x23a
    'NtUserSetWindowDisplayAffinity', # 0x23b
    'NtUserSetWindowCompositionTransition', # 0x23c
    'NtUserUpdateDefaultDesktopThumbnail', # 0x23d
    'NtUserSetWindowCompositionAttribute', # 0x23e
    'NtUserSetWindowBand', # 0x23f
    'NtUserSetProcessUIAccessZorder', # 0x240
    'NtUserSetProcessDpiAwareness', # 0x241
    'NtUserSetTimer', # 0x242
    'NtUserSetThreadState', # 0x243
    'NtUserSetThreadLayoutHandles', # 0x244
    'NtUserSetThreadDesktop', # 0x245
    'NtUserSetThreadInputBlocked', # 0x246
    'NtUserSetSystemTimer', # 0x247
    'NtUserSetSystemMenu', # 0x248
    'NtUserSetSystemCursor', # 0x249
    'NtUserSetSysColors', # 0x24a
    'NtUserSetShellWindowEx', # 0x24b
    'NtUserSetImmersiveBackgroundWindow', # 0x24c
    'NtUserSetScrollInfo', # 0x24d
    'NtUserSetProp', # 0x24e
    'NtUserGetProp', # 0x24f
    'NtUserSetProcessWindowStation', # 0x250
    'NtUserSetParent', # 0x251
    'NtUserSetObjectInformation', # 0x252
    'NtUserSetMenuFlagRtoL', # 0x253
    'NtUserSetMenuDefaultItem', # 0x254
    'NtUserSetMenuContextHelpId', # 0x255
    'NtUserSetMenu', # 0x256
    'NtUserSetKeyboardState', # 0x257
    'NtUserSetInternalWindowPos', # 0x258
    'NtUserSetInformationThread', # 0x259
    'NtUserSetImeOwnerWindow', # 0x25a
    'NtUserSetImeInfoEx', # 0x25b
    'NtUserSetImeHotKey', # 0x25c
    'NtUserSetFocus', # 0x25d
    'NtUserSetCursorIconData', # 0x25e
    'NtUserSetCursorContents', # 0x25f
    'NtUserSetCursor', # 0x260
    'NtUserSetClipboardViewer', # 0x261
    'NtUserSetClipboardData', # 0x262
    'NtUserSetClassWord', # 0x263
    'NtUserSetClassLong', # 0x264
    'NtUserSetChildWindowNoActivate', # 0x265
    'NtUserSetCapture', # 0x266
    'NtUserSetAppImeLevel', # 0x267
    'NtUserSetActiveWindow', # 0x268
    'NtUserSendInput', # 0x269
    'NtUserSelectPalette', # 0x26a
    'NtUserScrollWindowEx', # 0x26b
    'NtUserScrollDC', # 0x26c
    'NtUserSBGetParms', # 0x26d
    'NtUserResolveDesktopForWOW', # 0x26e
    'NtUserRemoveProp', # 0x26f
    'NtUserRemoveMenu', # 0x270
    'NtUserRemoveClipboardFormatListener', # 0x271
    'NtUserRegisterWindowMessage', # 0x272
    'NtUserRegisterTasklist', # 0x273
    'NtUserRegisterServicesProcess', # 0x274
    'NtUserRegisterRawInputDevices', # 0x275
    'NtUserRegisterHotKey', # 0x276
    'NtUserRegisterUserApiHook', # 0x277
    'NtUserRegisterErrorReportingDialog', # 0x278
    'NtUserRegisterClassExWOW', # 0x279
    'NtUserRegisterBSDRWindow', # 0x27a
    'NtUserRedrawWindow', # 0x27b
    'NtUserUndelegateInput', # 0x27c
    'NtUserGetWindowMinimizeRect', # 0x27d
    'NtUserDwmStopRedirection', # 0x27e
    'NtUserDwmStartRedirection', # 0x27f
    'NtUserDwmGetRemoteSessionOcclusionEvent', # 0x280
    'NtUserDwmGetRemoteSessionOcclusionState', # 0x281
    'NtUserUpdateWindowTransform', # 0x282
    'NtUserCheckProcessSession', # 0x283
    'NtUserUnregisterSessionPort', # 0x284
    'NtUserRegisterSessionPort', # 0x285
    'NtUserCtxDisplayIOCtl', # 0x286
    'NtUserRemoteStopScreenUpdates', # 0x287
    'NtUserRemoteRedrawScreen', # 0x288
    'NtUserRemoteRedrawRectangle', # 0x289
    'NtUserRemoteConnect', # 0x28a
    'NtUserWaitAvailableMessageEx', # 0x28b
    'NtUserWindowFromPoint', # 0x28c
    'NtUserWindowFromPhysicalPoint', # 0x28d
    'NtUserWaitMessage', # 0x28e
    'NtUserWaitForMsgAndEvent', # 0x28f
    'NtUserWaitForInputIdle', # 0x290
    'NtUserVkKeyScanEx', # 0x291
    'NtUserValidateTimerCallback', # 0x292
    'NtUserValidateRect', # 0x293
    'NtUserValidateHandleSecure', # 0x294
    'NtUserUserHandleGrantAccess', # 0x295
    'NtUserUpdatePerUserSystemParameters', # 0x296
    'NtUserSetLayeredWindowAttributes', # 0x297
    'NtUserGetLayeredWindowAttributes', # 0x298
    'NtUserUpdateLayeredWindow', # 0x299
    'NtUserUpdateInstance', # 0x29a
    'NtUserUpdateInputContext', # 0x29b
    'NtUserUnregisterHotKey', # 0x29c
    'NtUserUnregisterUserApiHook', # 0x29d
    'NtUserUnregisterClass', # 0x29e
    'NtUserUnlockWindowStation', # 0x29f
    'NtUserUnloadKeyboardLayout', # 0x2a0
    'NtUserUnhookWinEvent', # 0x2a1
    'NtUserUnhookWindowsHookEx', # 0x2a2
    'NtUserGetTouchInputInfo', # 0x2a3
    'NtUserIsTouchWindow', # 0x2a4
    'NtUserModifyWindowTouchCapability', # 0x2a5
    'NtGdiEngStretchBltROP', # 0x2a6
    'NtGdiEngTextOut', # 0x2a7
    'NtGdiEngTransparentBlt', # 0x2a8
    'NtGdiEngGradientFill', # 0x2a9
    'NtGdiEngAlphaBlend', # 0x2aa
    'NtGdiEngLineTo', # 0x2ab
    'NtGdiEngPaint', # 0x2ac
    'NtGdiEngStrokeAndFillPath', # 0x2ad
    'NtGdiEngFillPath', # 0x2ae
    'NtGdiEngStrokePath', # 0x2af
    'NtGdiEngMarkBandingSurface', # 0x2b0
    'NtGdiEngPlgBlt', # 0x2b1
    'NtGdiEngStretchBlt', # 0x2b2
    'NtGdiEngBitBlt', # 0x2b3
    'NtGdiEngLockSurface', # 0x2b4
    'NtGdiEngUnlockSurface', # 0x2b5
    'NtGdiEngEraseSurface', # 0x2b6
    'NtGdiEngDeleteSurface', # 0x2b7
    'NtGdiEngDeletePalette', # 0x2b8
    'NtGdiEngCopyBits', # 0x2b9
    'NtGdiEngComputeGlyphSet', # 0x2ba
    'NtGdiEngCreatePalette', # 0x2bb
    'NtGdiEngCreateDeviceBitmap', # 0x2bc
    'NtGdiEngCreateDeviceSurface', # 0x2bd
    'NtGdiEngCreateBitmap', # 0x2be
    'NtGdiEngAssociateSurface', # 0x2bf
    'NtUserSetWindowFeedbackSetting', # 0x2c0
    'NtUserRegisterEdgy', # 0x2c1
    'NtUserGetWindowFeedbackSetting', # 0x2c2
    'NtUserHidePointerContactVisualization', # 0x2c3
    'NtUserGetTouchValidationStatus', # 0x2c4
    'NtUserInitializeTouchInjection', # 0x2c5
    'NtUserInjectTouchInput', # 0x2c6
    'NtUserRegisterTouchHitTestingWindow', # 0x2c7
    'NtUserSetDisplayMapping', # 0x2c8
    'NtUserSetCalibrationData', # 0x2c9
    'NtUserGetPhysicalDeviceRect', # 0x2ca
    'NtUserRegisterTouchPadCapable', # 0x2cb
    'NtUserGetRawPointerDeviceData', # 0x2cc
    'NtUserGetPointerDeviceCursors', # 0x2cd
    'NtUserGetPointerDeviceRects', # 0x2ce
    'NtUserRegisterPointerDeviceNotifications', # 0x2cf
    'NtUserGetPointerDeviceProperties', # 0x2d0
    'NtUserGetPointerDevice', # 0x2d1
    'NtUserGetPointerDevices', # 0x2d2
    'NtUserEnableTouchPad', # 0x2d3
    'NtUserGetPrecisionTouchPadConfiguration', # 0x2d4
    'NtUserSetPrecisionTouchPadConfiguration', # 0x2d5
    'NtUserPromotePointer', # 0x2d6
    'NtUserDiscardPointerFrameMessages', # 0x2d7
    'NtUserRegisterPointerInputTarget', # 0x2d8
    'NtUserGetPointerInputTransform', # 0x2d9
    'NtUserGetPointerInfoList', # 0x2da
    'NtUserGetPointerCursorId', # 0x2db
    'NtUserGetPointerType', # 0x2dc
    'NtUserGetGestureConfig', # 0x2dd
    'NtUserSetGestureConfig', # 0x2de
    'NtUserGetGestureExtArgs', # 0x2df
    'NtUserGetGestureInfo', # 0x2e0
    'NtUserInjectGesture', # 0x2e1
    'NtUserChangeWindowMessageFilterEx', # 0x2e2
    'NtGdiXLATEOBJ_hGetColorTransform', # 0x2e3
    'NtGdiXLATEOBJ_iXlate', # 0x2e4
    'NtGdiXLATEOBJ_cGetPalette', # 0x2e5
    'NtGdiEngDeleteClip', # 0x2e6
    'NtGdiEngCreateClip', # 0x2e7
    'NtGdiEngDeletePath', # 0x2e8
    'NtGdiCLIPOBJ_ppoGetPath', # 0x2e9
    'NtGdiCLIPOBJ_cEnumStart', # 0x2ea
    'NtGdiCLIPOBJ_bEnum', # 0x2eb
    'NtGdiBRUSHOBJ_hGetColorTransform', # 0x2ec
    'NtGdiBRUSHOBJ_pvGetRbrush', # 0x2ed
    'NtGdiBRUSHOBJ_pvAllocRbrush', # 0x2ee
    'NtGdiBRUSHOBJ_ulGetBrushColor', # 0x2ef
    'NtGdiXFORMOBJ_iGetXform', # 0x2f0
    'NtGdiXFORMOBJ_bApplyXform', # 0x2f1
    'NtGdiFONTOBJ_pQueryGlyphAttrs', # 0x2f2
    'NtGdiFONTOBJ_pfdg', # 0x2f3
    'NtGdiFONTOBJ_pifi', # 0x2f4
    'NtGdiFONTOBJ_cGetGlyphs', # 0x2f5
    'NtGdiFONTOBJ_pxoGetXform', # 0x2f6
    'NtGdiFONTOBJ_vGetInfo', # 0x2f7
    'NtGdiFONTOBJ_cGetAllGlyphHandles', # 0x2f8
    'NtGdiFONTOBJ_pvTrueTypeFontFile', # 0x2f9
    'NtGdiSTROBJ_dwGetCodePage', # 0x2fa
    'NtGdiSTROBJ_vEnumStart', # 0x2fb
    'NtGdiSTROBJ_bGetAdvanceWidths', # 0x2fc
    'NtGdiSTROBJ_bEnumPositionsOnly', # 0x2fd
    'NtGdiSTROBJ_bEnum', # 0x2fe
    'NtGdiPATHOBJ_bEnumClipLines', # 0x2ff
    'NtGdiPATHOBJ_vEnumStartClipLines', # 0x300
    'NtGdiPATHOBJ_vEnumStart', # 0x301
    'NtGdiPATHOBJ_bEnum', # 0x302
    'NtGdiPATHOBJ_vGetBounds', # 0x303
    'NtGdiEngCheckAbort', # 0x304
    'NtGdiGetDhpdev', # 0x305
    'NtGdiHT_Get8BPPMaskPalette', # 0x306
    'NtGdiHT_Get8BPPFormatPalette', # 0x307
    'NtGdiUpdateTransform', # 0x308
    'NtGdiUMPDEngFreeUserMem', # 0x309
    'NtGdiBRUSHOBJ_DeleteRbrush', # 0x30a
    'NtGdiSetPUMPDOBJ', # 0x30b
    'NtGdiSetUMPDSandboxState', # 0x30c
    'NtGdiDrawStream', # 0x30d
    'NtGdiHLSurfSetInformation', # 0x30e
    'NtGdiHLSurfGetInformation', # 0x30f
    'NtGdiDwmCreatedBitmapRemotingOutput', # 0x310
    'NtGdiDdDDIGetScanLine', # 0x311
    'NtGdiDdDDIReleaseProcessVidPnSourceOwners', # 0x312
    'NtGdiDdDDIGetProcessSchedulingPriorityClass', # 0x313
    'NtGdiDdDDISetProcessSchedulingPriorityClass', # 0x314
    'NtGdiDdDDIGetContextSchedulingPriority', # 0x315
    'NtGdiDdDDISetContextSchedulingPriority', # 0x316
    'NtGdiDdDDIDestroyDCFromMemory', # 0x317
    'NtGdiDdDDICreateDCFromMemory', # 0x318
    'NtGdiDdDDIGetDeviceState', # 0x319
    'NtGdiDdDDISetGammaRamp', # 0x31a
    'NtGdiDdDDIWaitForVerticalBlankEvent', # 0x31b
    'NtGdiDdDDIDestroyOverlay', # 0x31c
    'NtGdiDdDDIFlipOverlay', # 0x31d
    'NtGdiDdDDIUpdateOverlay', # 0x31e
    'NtGdiDdDDICreateOverlay', # 0x31f
    'NtGdiDdDDIGetPresentQueueEvent', # 0x320
    'NtGdiDdDDIGetPresentHistory', # 0x321
    'NtGdiDdDDISetVidPnSourceOwner1', # 0x322
    'NtGdiDdDDISetVidPnSourceOwner', # 0x323
    'NtGdiDdDDIQueryStatistics', # 0x324
    'NtGdiDdDDIEscape', # 0x325
    'NtGdiDdDDIGetSharedPrimaryHandle', # 0x326
    'NtGdiDdDDICloseAdapter', # 0x327
    'NtGdiDdDDIOpenAdapterFromLuid', # 0x328
    'NtGdiDdDDIEnumAdapters', # 0x329
    'NtGdiDdDDIOpenAdapterFromHdc', # 0x32a
    'NtGdiDdDDIOpenAdapterFromDeviceName', # 0x32b
    'NtGdiDdDDIRender', # 0x32c
    'NtGdiDdDDIPresent', # 0x32d
    'NtGdiDdDDIGetMultisampleMethodList', # 0x32e
    'NtGdiDdDDISetDisplayMode', # 0x32f
    'NtGdiDdDDIGetDisplayModeList', # 0x330
    'NtGdiDdDDIUnlock', # 0x331
    'NtGdiDdDDILock', # 0x332
    'NtGdiDdDDIQueryAdapterInfo', # 0x333
    'NtGdiDdDDIGetRuntimeData', # 0x334
    'NtGdiDdDDISignalSynchronizationObject', # 0x335
    'NtGdiDdDDIWaitForSynchronizationObject', # 0x336
    'NtGdiDdDDIDestroySynchronizationObject', # 0x337
    'NtGdiDdDDIOpenSynchronizationObject', # 0x338
    'NtGdiDdDDICreateSynchronizationObject', # 0x339
    'NtGdiDdDDIDestroyContext', # 0x33a
    'NtGdiDdDDICreateContext', # 0x33b
    'NtGdiDdDDIDestroyDevice', # 0x33c
    'NtGdiDdDDICreateDevice', # 0x33d
    'NtGdiDdDDIQueryAllocationResidency', # 0x33e
    'NtGdiDdDDISetAllocationPriority', # 0x33f
    'NtGdiDdDDIDestroyAllocation', # 0x340
    'NtGdiDdDDIOpenResourceFromNtHandle', # 0x341
    'NtGdiDdDDIOpenSyncObjectFromNtHandle', # 0x342
    'NtGdiDdDDIOpenResource', # 0x343
    'NtGdiDdDDIOpenNtHandleFromName', # 0x344
    'NtGdiDdDDIShareObjects', # 0x345
    'NtGdiDdDDIQueryResourceInfoFromNtHandle', # 0x346
    'NtGdiDdDDIQueryResourceInfo', # 0x347
    'NtGdiDdDDICreateAllocation', # 0x348
    'NtGdiDdDDIOutputDuplReleaseFrame', # 0x349
    'NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName', # 0x34a
    'NtGdiDdDDIOutputDuplPresent', # 0x34b
    'NtGdiDdDDIReleaseKeyedMutex2', # 0x34c
    'NtGdiDdDDIAcquireKeyedMutex2', # 0x34d
    'NtGdiDdDDIOpenKeyedMutex2', # 0x34e
    'NtGdiDdDDICreateKeyedMutex2', # 0x34f
    'NtGdiDdDDIOutputDuplGetPointerShapeData', # 0x350
    'NtGdiDdDDIOutputDuplGetMetaData', # 0x351
    'NtGdiDdDDIOutputDuplGetFrameInfo', # 0x352
    'NtGdiDdDDIDestroyOutputDupl', # 0x353
    'NtGdiDdDDICreateOutputDupl', # 0x354
    'NtGdiDdDDIReclaimAllocations', # 0x355
    'NtGdiDdDDIOfferAllocations', # 0x356
    'NtGdiDdDDICheckSharedResourceAccess', # 0x357
    'NtGdiDdDDICheckVidPnExclusiveOwnership', # 0x358
    'NtGdiDdDDIGetOverlayState', # 0x359
    'NtGdiDdDDIConfigureSharedResource', # 0x35a
    'NtGdiDdDDIReleaseKeyedMutex', # 0x35b
    'NtGdiDdDDIAcquireKeyedMutex', # 0x35c
    'NtGdiDdDDIDestroyKeyedMutex', # 0x35d
    'NtGdiDdDDIOpenKeyedMutex', # 0x35e
    'NtGdiDdDDICreateKeyedMutex', # 0x35f
    'NtGdiDdDDISharedPrimaryUnLockNotification', # 0x360
    'NtGdiDdDDISharedPrimaryLockNotification', # 0x361
    'NtGdiDdDDISetDisplayPrivateDriverFormat', # 0x362
    'NtGdiDdDDICheckExclusiveOwnership', # 0x363
    'NtGdiDdDDICheckMonitorPowerState', # 0x364
    'NtGdiDdDDIWaitForIdle', # 0x365
    'NtGdiDdDDICheckOcclusion', # 0x366
    'NtGdiDdDDIInvalidateActiveVidPn', # 0x367
    'NtGdiDdDDIPollDisplayChildren', # 0x368
    'NtGdiDdDDISetQueuedLimit', # 0x369
    'NtGdiDdDDIPinDirectFlipResources', # 0x36a
    'NtGdiDdDDIUnpinDirectFlipResources', # 0x36b
    'NtGdiDdDDIWaitForVerticalBlankEvent2', # 0x36c
    'NtGdiDdDDISetContextInProcessSchedulingPriority', # 0x36d
    'NtGdiDdDDIGetContextInProcessSchedulingPriority', # 0x36e
    'NtGdiDdDDIGetSharedResourceAdapterLuid', # 0x36f
    'NtGdiDdDDISetStereoEnabled', # 0x370
    'NtGdiDdDDIPresentMultiPlaneOverlay', # 0x371
    'NtGdiDdDDICheckMultiPlaneOverlaySupport', # 0x372
    'NtGdiDdDDIGetCachedHybridQueryValue', # 0x373
    'NtGdiDdDDICacheHybridQueryValue', # 0x374
    'NtGdiDdDDINetDispGetNextChunkInfo', # 0x375
    'NtGdiDdDDINetDispQueryMiracastDisplayDeviceSupport', # 0x376
    'NtGdiDdDDINetDispStartMiracastDisplayDevice', # 0x377
    'NtGdiDdDDINetDispStopMiracastDisplayDevice', # 0x378
    'NtGdiDdDDINetDispQueryMiracastDisplayDeviceStatus', # 0x379
    'NtGdiMakeObjectUnXferable', # 0x37a
    'NtGdiMakeObjectXferable', # 0x37b
    'NtGdiDestroyPhysicalMonitor', # 0x37c
    'NtGdiGetPhysicalMonitorDescription', # 0x37d
    'NtGdiGetPhysicalMonitors', # 0x37e
    'NtGdiGetNumberOfPhysicalMonitors', # 0x37f
    'NtGdiDDCCIGetTimingReport', # 0x380
    'NtGdiDDCCIGetCapabilitiesString', # 0x381
    'NtGdiDDCCIGetCapabilitiesStringLength', # 0x382
    'NtGdiDDCCISaveCurrentSettings', # 0x383
    'NtGdiDDCCISetVCPFeature', # 0x384
    'NtGdiDDCCIGetVCPFeature', # 0x385
    'NtGdiDdQueryVisRgnUniqueness', # 0x386
    'NtGdiDdDestroyFullscreenSprite', # 0x387
    'NtGdiDdNotifyFullscreenSpriteUpdate', # 0x388
    'NtGdiDdCreateFullscreenSprite', # 0x389
    'NtUserShowSystemCursor', # 0x38a
    'NtUserSetMirrorRendering', # 0x38b
    'NtUserMagGetContextInformation', # 0x38c
    'NtUserMagSetContextInformation', # 0x38d
    'NtUserMagControl', # 0x38e
    'NtUserSlicerControl', # 0x38f
    'NtUserHwndSetRedirectionInfo', # 0x390
    'NtUserHwndQueryRedirectionInfo', # 0x391
    'NtCreateCompositionSurfaceHandle', # 0x392
    'NtValidateCompositionSurfaceHandle', # 0x393
    'NtBindCompositionSurface', # 0x394
    'NtUnBindCompositionSurface', # 0x395
    'NtQueryCompositionSurfaceBinding', # 0x396
    'NtNotifyPresentToCompositionSurface', # 0x397
    'NtQueryCompositionSurfaceStatistics', # 0x398
    'NtOpenCompositionSurfaceSectionInfo', # 0x399
    'NtOpenCompositionSurfaceSwapChainHandleInfo', # 0x39a
    'NtQueryCompositionSurfaceRenderingRealization', # 0x39b
    'NtOpenCompositionSurfaceDirtyRegion', # 0x39c
    'NtSetCompositionSurfaceOutOfFrameDirectFlipNotification', # 0x39d
    'NtSetCompositionSurfaceStatistics', # 0x39e
    'NtSetCompositionSurfaceBufferCompositionMode', # 0x39f
    'NtSetCompositionSurfaceIndependentFlipInfo', # 0x3a0
    'NtCreateCompositionInputSink', # 0x3a1
    'NtDuplicateCompositionInputSink', # 0x3a2
    'NtQueryCompositionInputSink', # 0x3a3
    'NtQueryCompositionInputSinkLuid', # 0x3a4
    'NtUpdateInputSinkTransforms', # 0x3a5
    'NtCompositionInputThread', # 0x3a6
    'NtTokenManagerOpenSection', # 0x3a7
    'NtTokenManagerOpenEvent', # 0x3a8
    'NtTokenManagerThread', # 0x3a9
    'NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates', # 0x3aa
    'NtTokenManagerDeleteOutstandingDirectFlipTokens', # 0x3ab
    'NtTokenManagerCreateCompositionTokenHandle', # 0x3ac
    'NtDCompositionBeginFrame', # 0x3ad
    'NtDCompositionConfirmFrame', # 0x3ae
    'NtDCompositionRetireFrame', # 0x3af
    'NtDCompositionDiscardFrame', # 0x3b0
    'NtDCompositionGetFrameSurfaceUpdates', # 0x3b1
    'NtDCompositionGetFrameLegacyTokens', # 0x3b2
    'NtDCompositionDestroyConnection', # 0x3b3
    'NtDCompositionGetConnectionBatch', # 0x3b4
    'NtDCompositionGetFrameStatistics', # 0x3b5
    'NtDCompositionGetDeletedResources', # 0x3b6
    'NtDCompositionSetResourceDeletedNotificationTag', # 0x3b7
    'NtDCompositionCreateConnection', # 0x3b8
    'NtDCompositionDestroyChannel', # 0x3b9
    'NtDCompositionReleaseAllResources', # 0x3ba
    'NtDCompositionSubmitDWMBatch', # 0x3bb
    'NtDCompositionCommitChannel', # 0x3bc
    'NtDCompositionWaitForChannel', # 0x3bd
    'NtDCompositionSetChannelCommitCompletionEvent', # 0x3be
    'NtDCompositionTelemetryTouchInteractionBegin', # 0x3bf
    'NtDCompositionTelemetryTouchInteractionUpdate', # 0x3c0
    'NtDCompositionTelemetryTouchInteractionEnd', # 0x3c1
    'NtDCompositionTelemetrySetApplicationId', # 0x3c2
    'NtDCompositionTelemetryAnimationScenarioBegin', # 0x3c3
    'NtDCompositionTelemetryAnimationScenarioReference', # 0x3c4
    'NtDCompositionTelemetryAnimationScenarioUnreference', # 0x3c5
    'NtDCompositionCurrentBatchId', # 0x3c6
    'NtDCompositionReleaseResource', # 0x3c7
    'NtDCompositionRemoveCrossDeviceVisualChild', # 0x3c8
    'NtDCompositionRemoveVisualChild', # 0x3c9
    'NtDCompositionAddCrossDeviceVisualChild', # 0x3ca
    'NtDCompositionAddVisualChild', # 0x3cb
    'NtDCompositionReplaceVisualChildren', # 0x3cc
    'NtDCompositionSetResourceAnimationProperty', # 0x3cd
    'NtDCompositionSetResourceReferenceArrayProperty', # 0x3ce
    'NtDCompositionSetResourceReferenceProperty', # 0x3cf
    'NtDCompositionSetResourceBufferProperty', # 0x3d0
    'NtDCompositionSetResourceIntegerProperty', # 0x3d1
    'NtDCompositionSetResourceFloatProperty', # 0x3d2
    'NtDCompositionSetResourceHandleProperty', # 0x3d3
    'NtDCompositionCreateResource', # 0x3d4
    'NtDCompositionOpenSharedResource', # 0x3d5
    'NtDCompositionOpenSharedResourceHandle', # 0x3d6
    'NtDCompositionCreateDwmChannel', # 0x3d7
    'NtDCompositionCreateChannel', # 0x3d8
    'NtDCompositionSynchronize', # 0x3d9
    'NtDCompositionDwmSyncFlush', # 0x3da
    'NtDCompositionReferenceSharedResourceOnDwmChannel', # 0x3db
    'NtDCompositionSignalGpuFence', # 0x3dc
    'NtDCompositionCreateAndBindSharedSection', # 0x3dd
    'NtDCompositionSetDebugCounter', # 0x3de
    'NtDCompositionGetChannels', # 0x3df
    'NtDCompositionConnectPipe', # 0x3e0
    'NtDCompositionRegisterThumbnailVisual', # 0x3e1
    'NtDCompositionDuplicateHandleToProcess', # 0x3e2
    'NtUserDestroyDCompositionHwndTarget', # 0x3e3
    'NtUserCreateDCompositionHwndTarget', # 0x3e4
    'NtUserWaitForRedirectionStartComplete', # 0x3e5
    'NtUserSignalRedirectionStartComplete', # 0x3e6
    'NtUserSetActiveProcess', # 0x3e7
    'NtUserGetDisplayAutoRotationPreferencesByProcessId', # 0x3e8
    'NtUserGetDisplayAutoRotationPreferences', # 0x3e9
    'NtUserSetDisplayAutoRotationPreferences', # 0x3ea
    'NtUserSetAutoRotation', # 0x3eb
    'NtUserGetAutoRotationState', # 0x3ec
    'NtUserAutoRotateScreen', # 0x3ed
    'NtUserAcquireIAMKey', # 0x3ee
    'NtUserSetActivationFilter', # 0x3ef
    'NtUserSetFallbackForeground', # 0x3f0
    'NtUserSetBrokeredForeground', # 0x3f1
    'NtUserDisableImmersiveOwner', # 0x3f2
    'NtUserClearForeground', # 0x3f3
    'NtUserEnableIAMAccess', # 0x3f4
    'NtUserGetProcessUIContextInformation', # 0x3f5
    'NtUserSetProcessRestrictionExemption', # 0x3f6
    'NtUserEnableMouseInPointer', # 0x3f7
    'NtUserIsMouseInPointerEnabled', # 0x3f8
    'NtUserPromoteMouseInPointer', # 0x3f9
    'NtUserAutoPromoteMouseInPointer', # 0x3fa
    'NtUserEnableMouseInputForCursorSuppression', # 0x3fb
    'NtUserIsMouseInputEnabled', # 0x3fc
    'NtUserInternalClipCursor', # 0x3fd
    'NtUserCheckProcessForClipboardAccess', # 0x3fe
    'NtUserGetClipboardAccessToken', # 0x3ff
    'NtUserGetQueueEventStatus', # 0x400
    'NtUserCompositionInputSinkLuidFromPoint', # 0x401
    'NtUserUpdateWindowInputSinkHints', # 0x402
    'NtUserTransformPoint', # 0x403
    'NtUserTransformRect', # 0x404
    'NtUserGetHimetricScaleFactorFromPixelLocation', # 0x405
    'NtUserGetProcessDpiAwareness', # 0x406
    'NtUserGetDpiForMonitor', # 0x407
    'NtUserReportInertia', # 0x408
    'NtUserLinkDpiCursor', # 0x409
    'NtUserGetCursorDims', # 0x40a
    'NtUserGetOwnerTransformedMonitorRect', # 0x40b
    ],
]
