# Volatility
# Copyright (c) 2008 Volatile Systems
# Copyright (c) 2008 Brendan Dolan-Gavitt <bdolangavitt@wesleyan.edu>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details. 
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
#

"""
@author:       Brendan Dolan-Gavitt
@license:      GNU General Public License 2.0 or later
@contact:      bdolangavitt@wesleyan.edu

This file provides support for windows XP SP2. We provide a profile
for SP2.
"""

#pylint: disable-msg=C0111

import copy
import windows
import xp_sp2_x86_vtypes
import xp_sp2_x86_syscalls
import crash_vtypes
import hibernate_vtypes
import kdbg_vtypes
import tcpip_vtypes
import ssdt_vtypes
import volatility.debug as debug #pylint: disable-msg=W0611

# These are updates applied to the autogenerated vtypes. In particular
# they are types that are not defined in the autogenerated set.

overlay = copy.deepcopy(windows.windows_overlay)

vtypes = copy.deepcopy(xp_sp2_x86_vtypes.nt_types)

vtypes.update(crash_vtypes.crash_vtypes)
vtypes.update(hibernate_vtypes.hibernate_vtypes)
vtypes.update(kdbg_vtypes.kdbg_vtypes)
vtypes.update(tcpip_vtypes.tcpip_vtypes)
vtypes.update(ssdt_vtypes.ssdt_vtypes)

overlay['VOLATILITY_MAGIC'][1]['DTBSignature'][1] = ['VolatilityMagic', dict(value = "\x03\x00\x1b\x00")]
overlay['VOLATILITY_MAGIC'][1]['KDBGHeader'][1] = ['VolatilityMagic', dict(value = '\x00\x00\x00\x00\x00\x00\x00\x00KDBG\x90\x02')]
overlay['_EPROCESS'][1].update({'VadRoot': [ None, ['pointer', ['_MMVAD']]]})

class WinXPSP2x86(windows.AbstractWindowsX86):
    """ A Profile for Windows XP SP2 x86 """
    _md_major = 5
    _md_minor = 1
    overlay = overlay
    abstract_types = vtypes
    syscalls = xp_sp2_x86_syscalls.syscalls
