obj-m += module.o
KDIR ?= /lib/modules/3.5.0-23-generic/build

-include version.mk

all: dwarf 

dwarf: module.c
	$(MAKE) -C $(KDIR) CONFIG_DEBUG_INFO=y M="$(PWD)" modules
	dwarfdump -di module.ko > module.dwarf
	$(MAKE) -C $(KDIR) M="$(PWD)" clean

clean:
	$(MAKE) -C $(KDIR) M="$(PWD)" clean
	rm -f module.dwarf
